---
title: "Global Mix Mozambique cleaning"
author: "Holin Chen"
date: "9/30/2021"
output: html_document
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = FALSE, error= FALSE, cache = F}
rm(list=ls())

library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```


```{r imports, echo=FALSE, message = FALSE, warning=FALSE, include=FALSE}
# Load packages
source("../scripts/00_load_libraries.R")
library(stringr)
library(Hmisc)
# load data
# library(REDCapR)

# new data downloaded on 08092022
# new data downloaded on 09142022, with some subtle updates to aim 2 missing sensor IDs

```

```{r raw-data, echo=FALSE}
# import raw data
data <- readRDS("../data/raw/all_data_09142022.RDS")
```


```{r study_site}
# study site
study_site <- data %>%
  filter(redcap_event_name=="household_survey_arm_1") %>%
  select(rec_id, study_site, aim, isindex) %>%
  filter(!is.na(study_site)) # 

table(study_site$study_site, study_site$aim)
```


## Individual enrolment
```{r enrolled-participants, echo=FALSE}
ind <- data %>% 
  dplyr::filter(redcap_event_name == "individual_enrollm_arm_1") %>% 
  dplyr::select("rec_id","date_enrolled", "sex", "sex_other", "birthdate","age", 
                "read_write", "occupation___0", "occupation___1", "occupation___2", 
                "occupation___3", "occupation___4", "occupation___5", "occupation___6",
                "occupation___7", "occupation___8", "occupation___9", "occupation_other",
                "enrolled_school", "highest_educ", "school_level", "transport_use",
                "hh_resp_exposure", "child_breastfeed", "num_simbling", "inscrio_complete",
                "sensor_id","child", "redcap_repeat_instrument") %>%
  rename(num_sibling = num_simbling) %>%
    dplyr::filter(is.na(redcap_repeat_instrument)) %>%
  left_join(study_site, by="rec_id")
## Individual enrollment records

ind <- ind %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 
ind <- ind %>% 
  dplyr::mutate(aim = case_when(aim == 0 ~ 1,
                                 aim == 1 ~ 2)) 

ind <- ind %>% 
  dplyr::mutate(highest_educ = case_when(highest_educ == 0 ~ "No schooling", 
                                           highest_educ == 1 ~ "Primary School (1-7)", 
                                           highest_educ == 2 ~ "Basic Secondary school (8-10)",
                                           highest_educ == 3 ~ "Middle Secondary (11-12)", 
                                           highest_educ == 4 ~ "1-3 years of college/university", 
                                           highest_educ == 5 ~ "Bachelors",
                                           highest_educ == 6 ~ "More than Bachelors")) 
label(ind$highest_educ) <- "What is the highest level of education that you have attained?"

## age categories
ind$age_weeks <- round(difftime(strptime(as.Date(ind$date_enrolled), format = "%Y-%m-%d"), 
                               strptime(ind$birthdate, format = "%Y-%m-%d"),units="weeks"),2)
ind$months <- interval(ind$birthdate, ind$date_enrolled) %/% months(1) 
df_mths <- subset(ind, ind$months < 12)
df_years <- subset(ind, ind$months >= 12)
df_years$age <- as.numeric(df_years$age)
df_mths <- df_mths %>% 
  dplyr::mutate(group = case_when(months < 6 ~ 1, 
                                  months >= 6  ~ 2))
df_years <- df_years %>% 
  dplyr::mutate(group = case_when(
    age < 5 ~ 3, 
    age >= 5 & age < 10 ~ 4, 
    age >= 10 & age < 15 ~ 5, 
    age >= 15 & age < 20 ~ 6, 
    age >= 20 & age < 30 ~ 7, 
    age >= 30 & age < 40 ~ 8,
    age >= 40 & age < 60 ~ 9, 
    age >= 60 ~ 10))

ind <- rbind(df_mths, df_years)

ind$age_cat <- NA
ind <- ind %>% dplyr::mutate(age_cat = case_when(group == 1 ~ "<6mo", 
                                          group == 2 ~ "6-11mo", 
                                          group == 3 ~ "1-4y", 
                                          group == 4 ~ "5-9y", 
                                          group == 5 ~ "10-14y", 
                                          group == 6 ~ "15-19y", 
                                          group == 7 ~ "20-29y", 
                                          group == 8 ~ "30-39y", 
                                          group == 9 ~ "40-59y", 
                                          group == 10 ~ "60+y"))
ind$age_cat <- factor(ind$age_cat, 
                   levels = c("<6mo", "6-11mo", "1-4y", "5-9y", 
                              "10-14y", "15-19y", "20-29y", "30-39y", 
                              "40-59y", "60+y"))

## sex
ind <- ind %>% 
  dplyr::mutate(sex = case_when(sex == 0 ~ "Female", sex == 1 ~ "Male"))


ind <- ind %>% 
  dplyr::mutate(read_write = case_when(read_write == 0 ~ "No", 
                                         read_write == 1 ~ "Yes"))
label(ind$read_write) <- "Can the participant read and write on their own?"


label(ind$occupation___0) <- "Unemployed"
label(ind$occupation___1) <- "Student"
label(ind$occupation___2) <- "Office worker"
label(ind$occupation___3) <- "Business person"
label(ind$occupation___4) <- "Casual labor"
label(ind$occupation___5) <- "Farmer"
label(ind$occupation___6) <- "Fishing"
label(ind$occupation___7) <- "Retired"
label(ind$occupation___8) <- "Homemaker/ Housewife"
label(ind$occupation___9) <- "Other"

ind$occupation <- "Other"
ind <- ind %>%
  dplyr::mutate(occupation = case_when(occupation___0 == 1 ~ "Unemployed",
                                       occupation___1 == 1 ~ "Student",
                                       occupation___2 == 1 ~ "Office worker",
                                       occupation___3 == 1 ~ "Business person",
                                       occupation___4 == 1 ~ "Casual laboror",
                                       occupation___5 == 1 ~ "Farmer",
                                       occupation___6 == 1 ~ "Fishing",
                                       occupation___7 == 1 ~ "Retired",
                                       occupation___8 == 1 ~ "Homemaker/ Housewife",
                                       occupation___9 == 1 ~ "Other"))
label(ind$occupation) <- "What is your occupation?"

ind <- ind %>% 
  dplyr::mutate(enrolled_school = case_when(enrolled_school == 0 ~ "No", 
                                         enrolled_school == 1 ~ "Yes"))
label(ind$enrolled_school) <- "Are you currently enrolled in school?"

ind <- ind %>% 
  dplyr::mutate(school_level = case_when(school_level == 0 ~ "No schooling", 
                                           school_level == 1 ~ "Primary School (1-7)", 
                                           school_level == 2 ~ "Basic Secondary school (8-10)",
                                           school_level == 3 ~ "Middle Secondary (11-12)", 
                                           school_level == 4 ~ "1-3 years of college/university", 
                                           school_level == 5 ~ "Bachelors",
                                           school_level == 6 ~ "More than Bachelors"))
label(ind$school_level) <- "What school level are you in?"

ind <- ind %>% 
  dplyr::mutate(transport_use = case_when(transport_use == 0 ~ "Never", 
                                            transport_use == 1 ~ "Rarely", 
                                            transport_use == 2 ~ "Daily or almost daily",
                                            transport_use == 3 ~ "1-3 times per week", 
                                            transport_use == 4 ~ "1 time per month"))
label(ind$transport_use) <- "How often did you use mass transport in the past 3 months?"

ind <- ind %>% 
  dplyr::mutate(hh_resp_exposure = case_when(hh_resp_exposure == 0 ~ "No", 
                                               hh_resp_exposure == 1 ~ "Yes",
                                               hh_resp_exposure == 2 ~ "Unnown"))
label(ind$hh_resp_exposure) <- "Were you exposed to persons with respiratory complaints within your household in the past one week?"
 
ind <- ind %>% 
  dplyr::mutate(child_breastfeed = case_when(child_breastfeed == 0 ~ "No", 
                                               child_breastfeed == 1 ~ "Yes",
                                               child_breastfeed == 2 ~ "Not applicable"))
label(ind$child_breastfeed) <- "Are you breastfeeding?"

ind <- ind %>% 
  dplyr::mutate(child = case_when(child == 0 ~ "No", 
                                    child == 1 ~ "Yes",
                                    child == 2 ~ "Not applicable"))
label(ind$child) <- "Do you have an infant ?"

# ind_contact_hh <- contact_hh_all %>%
#   left_join(ind[,-which(names(ind) %in% c("aim","study_site"))], by = "rec_id")
# # 
# ind_contact_nonhh <- contact_nonhh_all %>%
#   left_join(ind[,-which(names(ind) %in% c("aim","study_site"))], by = "rec_id")
```

```{r exit-interiew}
## Exit interview data
exit <- data %>% 
  dplyr::filter(redcap_event_name == "exit_interview_arm_1") %>% 
  dplyr::select("rec_id", "aim", "study_site", "contacts_completedby","all_contacts", 
                "contact_compare","behavior_change", "movement_change", 
                "days_left_home", "activities___1","activities___2",
                "activities___3", "activities___4","activities___5", 
                "activities___6", "activities___7", "activities___8", 
                "activities_work", "activities_school", "activities_other", 
                "yesterday_left_home", "quarantine", "quarantine_behavior", 
                "self_isolation", "self_isolation_location", "self_isolation_home", 
                "self_isolation_away", "isolation_ability", "mask_use",
                "mask_use_location___0", "mask_use_location___1" ,
                "mask_use_location___2", "mask_use_location___3", 
                "mask_use_location___4", "mask_use_location___5", 
                "mask_use_location___6", "mask_use_location___7", 
                "mask_use_location_other", "covid_contact___0", 
                "covid_contact___1", "covid_contact___2", "covid_contact___3", 
                "covid_contact___4", "covid_contact___5", "covid_contact___6", 
                "covid_contact___7", "covid_contact_other", "current_symptoms___0", 
                "current_symptoms___1", "current_symptoms___2", 
                "current_symptoms___3", "current_symptoms___4", 
                "current_symptoms___5", "current_symptoms___6", 
                "current_symptoms___7", "current_symptoms___8", 
                "current_symptoms___9", "current_symptoms___10", 
                "current_symptoms___11", "contact_with_infected", 
                "self_covid_test", "family_covid", "family_covid_symptoms", 
                "family_covid_test", "family_covid_number", "phone_access", 
                "phone_ownership", "phone_function", "phone_comm_mode",
                "phone_provider___0", "phone_provider___1", "phone_provider___2", 
                "phone_provider___3", "phone_provider_other", "phone_signal", 
                "phone_use", "entrevista_de_sada_complete") # "individual_id",

# study site and aim
exit <- exit %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 
exit <- exit %>% 
  dplyr::mutate(aim = case_when(aim == 0 ~ 1,
                                 aim == 1 ~ 2)) 
# Cleaning other variables 
exit <- exit %>% 
  dplyr::mutate(contacts_completedbylb = case_when(contacts_completedby == 0 ~ "Self, # during day 1 and 2",
                                                            contacts_completedby == 1 ~ "By fieldworker)) # at collection day"))
label(exit$contacts_completedbylb) <- "Did the participant complete the contact diaries alone? 
# throughout day 1 and day 2 or were the contact diaries completed with the Field Worker on the day of collection?"

exit <- exit %>% 
  dplyr::mutate(all_contactslb = case_when(all_contacts == 0 ~ "No",
                                           all_contacts == 1 ~ "Yes",
                                           all_contacts == 2 ~ "Unnown"))
label(exit$all_contactslb) <- "Were you able to include every single contact?"

exit <- exit %>% 
  dplyr::mutate(contact_comparelb = case_when(contact_compare == 1 ~ "Much fewer contacts then usual",
                                           contact_compare == 2 ~ "Fewer contacts than usual",
                                           contact_compare == 3 ~ "About the same as usual",
                                           contact_compare == 4 ~ "More contacts than usual",
                                           contact_compare == 5 ~ "Much more contacts than usual"))
label(exit$contact_comparelb) <- "On a scale of 1-5, how did the 2 days on which you reported your contact compare to a typical day?"

exit <- exit %>% 
  dplyr::mutate(behavior_changelb = case_when(behavior_change == 1 ~ "No change", 
                                              #I interact with people the same way that I used to before",
                                              behavior_change == 2 ~ "My interactions have increased",
                                              behavior_change == 3 ~ "My interactions have reduced",
                                              behavior_change == 4 ~ "Unnown"))
label(exit$behavior_changelb) <- "Do you think your social behavior has changed following the start of COVID-19? 
# Social behavior refers to your interactions with other people, such as talking face-to-face, visiting their homes, meeting outside # the home, etc."

exit <- exit %>% 
  dplyr::mutate(movement_changelb = case_when(movement_change == 1 ~ "No change",
                                              #I still move around the same way that I used to before",
                                              movement_change == 2 ~ "My movements have increased",
                                              movement_change == 3 ~ "My movements have have reduced",
                                              movement_change == 4 ~ "Unnown"))
label(exit$movement_changelb) <- "How do you think your movements have changed following the start of COVID-19?"

exit <- exit %>% 
  dplyr::mutate(days_left_homelb = case_when(days_left_home == 0 ~ "0",
                                           days_left_home == 1 ~ "1-3 times",
                                           days_left_home == 2 ~ "4-7 times",
                                           days_left_home == 3 ~ ">7 times",
                                           days_left_home == 4 ~ "Unnown",
                                           days_left_home == 5 ~ "I prefer not to answer"))
label(exit$days_left_homelb) <- "During the past 14 days, how many days did you leave your home?"

label(exit$activities___1) <- "Go to work"
label(exit$activities___2) <- "Go to school"
label(exit$activities___3) <-  "Attend religious service"
label(exit$activities___4) <-  "Seek health care"
label(exit$activities___5) <-  "Go to the market"
label(exit$activities___6) <-  "Visiting family/friends"
label(exit$activities___7) <-  "Did not leave home"
label(exit$activities___8) <-  "Other"

exit <- exit %>% 
  dplyr::mutate(yesterday_left_homelb = case_when(yesterday_left_home == 0 ~ "No",
                                           yesterday_left_home == 1 ~ "Yes"))
label(exit$yesterday_left_homelb) <- "Did you leave your home yesterday?"

exit <- exit %>% 
  dplyr::mutate(quarantinelb = case_when(quarantine == 0 ~ "No",
                                           quarantine == 1 ~ "Yes",
                                           quarantine == 2 ~ "I prefer not to answer"))
label(exit$quarantinelb) <- "Have you been required to go into quarantine due to COVID-19 in the last 14 days?"

exit <- exit %>% 
  dplyr::mutate(quarantine_behaviorlb = case_when(quarantine_behavior == 0 ~ "Continued to mingle with other family members",
                                           quarantine_behavior == 1 ~ "Stayed in separate room away from other family members",
                                           quarantine_behavior == 2 ~ "Went out of the house",
                                           quarantine_behavior == 3 ~ "Prefer not to answer"))
label(exit$quarantine_behaviorlb) <- "How was your social behavior during quarantine?"

exit <- exit %>% 
  dplyr::mutate(self_isolationlb = case_when(self_isolation == 0 ~ "No",
                                           self_isolation == 1 ~ "Yes",
                                           self_isolation == 2 ~ "I prefer not to answer"))
label(exit$self_isolationlb) <- "Have you been required to isolate yourself in the last 14 days?"

exit <- exit %>% 
  dplyr::mutate(self_isolation_locationlb = case_when(self_isolation_location == 0 ~ "At home",
                                                            self_isolation_location == 1 ~ "Away from home"))
label(exit$self_isolation_locationlb) <- "If yes, where did the isolation happen?"

exit <- exit %>% 
  dplyr::mutate(self_isolation_homelb = case_when(self_isolation_home == 0 ~ "Continued to mingle with other family members",
                                           self_isolation_home == 1 ~ "Stayed in separate room away from other family members",
                                           self_isolation_home == 2 ~ "Went out of the house",
                                           self_isolation_home == 3 ~ "Prefer not to answer"))
label(exit$self_isolation_homelb) <- "How was your social behavior during isolation at home?"

exit <- exit %>% 
  dplyr::mutate(self_isolation_awaylb = case_when(self_isolation_away == 0 ~ "Continued to mingle with other individuals",
                                           self_isolation_away == 1 ~ "Stayed in separate room away from other individuals",
                                           self_isolation_away == 2 ~ "Went out of the isolation facility",
                                           self_isolation_away == 3 ~ "Prefer not to answer"))
label(exit$self_isolation_awaylb) <- "How was your social behavior at the isolation facility?"

exit <- exit %>% 
  dplyr::mutate(isolation_abilitylb = case_when(isolation_ability == 0 ~ "No",
                                           isolation_ability == 1 ~ "Yes"))
label(exit$isolation_abilitylb) <- "If you were diagnosed with COVID-19 now, would you be able to isolate yourself from other members of the home?"

exit <- exit %>% 
  dplyr::mutate(mask_uselb = case_when(mask_use == 0 ~ "No",
                                           mask_use == 1 ~ "Yes",
                                           mask_use == 2 ~ "I prefer not to answer"))
label(exit$mask_uselb) <- "Did you wear a face mask in the last 14 days?"

label(exit$mask_use_location___0) <- "At home"
label(exit$mask_use_location___1) <- "Everywhere outside my house"
label(exit$mask_use_location___2) <- "When walking on the street"
label(exit$mask_use_location___3) <- "On public transport"
label(exit$mask_use_location___4) <- "In supermarkets/shops"
label(exit$mask_use_location___5) <- "In cinema/bar/restaurant"
label(exit$mask_use_location___6) <- "At work/school/college/university"
label(exit$mask_use_location___7) <- "Other"
  
label(exit$covid_contact___0) <- "None that I know of"
label(exit$covid_contact___1) <- "Member of my household"
label(exit$covid_contact___2) <- "Close friend"
label(exit$covid_contact___3) <- "Coworker"
label(exit$covid_contact___4) <- "Patient (in case of a health care worker)"
label(exit$covid_contact___5) <- "Client/Customer"
label(exit$covid_contact___6) <- "Other"
label(exit$covid_contact___7) <- "Rather not respond"  
 
label(exit$current_symptoms___0) <- "Difficulty in breathing"
label(exit$current_symptoms___1) <- "Chest discomfort"
label(exit$current_symptoms___2) <- "Chills"
label(exit$current_symptoms___3) <- "Cough"
label(exit$current_symptoms___4) <- "Fever"
label(exit$current_symptoms___5) <- "Sore throat"
label(exit$current_symptoms___6) <- "Loss of taste or smell"
label(exit$current_symptoms___7) <- "Muscle or joint pains"
label(exit$current_symptoms___8) <- "Tiredness or exhaustion"
label(exit$current_symptoms___9) <- "Nausea or vomiting"
label(exit$current_symptoms___10) <- "Diarrhea"
label(exit$current_symptoms___11) <- "None of these"

exit <- exit %>% 
  dplyr::mutate(contact_with_infectedlb = case_when(contact_with_infected == 0 ~ "No",
                                           contact_with_infected == 1 ~ "Yes",
                                           contact_with_infected == 2 ~ "I prefer not to answer"))
label(exit$contact_with_infectedlb) <- "Did you visit a health care facility for any of these symptoms?"
  
exit <- exit %>% 
  dplyr::mutate(self_covid_testlb = case_when(self_covid_test == 0 ~ "No, I don't think I need it",
                                           self_covid_test == 1 ~ "No, I didn't have the opportunity",
                                           self_covid_test == 2 ~ "Yes, I tested positive",
                                           self_covid_test == 3 ~ "Yes, I tested negative",
                                           self_covid_test == 4 ~ "Yes, waiting for results",
                                           self_covid_test == 5 ~ "I prefer not to answer"))
label(exit$self_covid_testlb) <- "Have you been tested for COVID-19?"  
  
exit <- exit %>% 
  dplyr::mutate(family_covid_symptomslb = case_when(family_covid_symptoms == 0 ~ "No",
                                           family_covid_symptoms == 1 ~ "Yes",
                                           family_covid_symptoms == 2 ~ "I prefer not to answer"))
label(exit$family_covid_symptomslb) <- "Has anyone else in your household exhibited COVID-19 symptoms in the last 14 days?"

exit <- exit %>% 
  dplyr::mutate(family_covid_testlb = case_when(family_covid_test == 0 ~ "No",
                                           family_covid_test == 1 ~ "Yes",
                                           family_covid_test == 2 ~ "I prefer not to answer"))
label(exit$family_covid_testlb) <- "Has anyone else in your household been tested for COVID-19?"

exit <- exit %>% 
  dplyr::mutate(phone_accesslb = case_when(phone_access == 0 ~ "No",
                                           phone_access == 1 ~ "Yes"))
label(exit$phone_accesslb) <- "Do you have access to a mobile phone?"

exit <- exit %>% 
  dplyr::mutate(phone_ownershiplb = case_when(phone_ownership == 0 ~ "No",
                                           phone_ownership == 1 ~ "Yes"))
label(exit$phone_ownershiplb) <- "If yes, do you own it?"

exit <- exit %>% 
  dplyr::mutate(phone_functionlb = case_when(phone_function == 1 ~ "Basic features",
                                             #phone (no internet)",
                                             phone_function == 2 ~ "Smart phone")) 
                                             #(internet enabled)"))
label(exit$phone_functionlb) <- "If you use (own or borrow) a mobile phone, what is the functionality? "

exit <- exit %>% 
  dplyr::mutate(phone_comm_modelb = case_when(phone_comm_mode == 1 ~ "Normal call and text",
                                           phone_comm_mode == 2 ~ "Internet calls and text"))
                                           #e.g. via Whatsapp"))
label(exit$phone_comm_modelb) <- "If smartphone, what is your preferred mode of communication?" 

label(exit$phone_provider___0) <- "Movitel"
label(exit$phone_provider___1) <- "Vodacom"
label(exit$phone_provider___2) <- "TMcel"
label(exit$phone_provider___3) <- "Other"

exit <- exit %>% 
  dplyr::mutate(phone_signallb = case_when(phone_signal == 0 ~ "Poor",
                                           phone_signal == 1 ~ "Normal",
                                           phone_signal == 2 ~ "Good"))
label(exit$phone_signallb) <- "If you use a mobile phone, rate the signal in most locations that you visit during the day. "

exit <- exit %>% 
  dplyr::mutate(phone_uselb = case_when(phone_use == 0 ~ "Never",
                                           phone_use == 1 ~ "1-5 times",
                                           phone_use == 2 ~ "6-10 times",
                                           phone_use == 3 ~ "More than 10 times"))
label(exit$phone_uselb) <- "In the last day/ 24 hours, how often did you call/ text using your mobile phone?"

```


```{r completed-participants, echo=FALSE}
library(readxl)

# drop all rec_ids in list given by Nilzio.these are 53 individuals in PC who did not complete the study.
todelete1 <- read_excel("../data/sensor_metadata/records_to_remove_09062022.xlsx", sheet=1)

length(unique(study_site$rec_id)) # 2186
length(unique(ind$rec_id)) # 2119
length(unique(exit$rec_id)) # 2016

study_site <- study_site %>% # 2133
  filter(!rec_id %in% unlist(todelete1$rec_id))

# generate list of rec_ids for individuals who completed survey
participant_ids <- intersect(unique(study_site$rec_id),
                           unique(exit$rec_id))

participant_ids <- intersect(unique(ind$rec_id),
                           participant_ids)

length(participant_ids) # 1960

# keep only participants who enrolled and completed the diary (with exit interview).
study_site <- study_site %>%
  filter(rec_id %in% participant_ids) 

ind <- ind %>% 
  filter(rec_id %in% participant_ids)

exit <- exit %>% 
  filter(rec_id %in% participant_ids)

data <- data %>% 
  filter(rec_id %in% participant_ids)

# now, the total number of total records is 1960.
length(unique(study_site$rec_id))
length(unique(ind$rec_id))
length(unique(exit$rec_id))
length(unique(data$rec_id))
```

# Summary of participant details by site
```{r participant-summary, echo=FALSE}
aim1_summary <- ind %>%
  select("aim", "sex", "age_cat", "read_write", "study_site", 
         "enrolled_school", "highest_educ", "school_level", "occupation") %>%
  filter(aim==1) %>%
  tbl_summary(by=study_site,
              percent="column",
              digits = all_categorical() ~ 0) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Aim 1 Particiant Individual Information in Mozambique**")
# "occupation___0", "occupation___1", "occupation___2", "occupation___3", "occupation___4","occupation___5", "occupation___6", "occupation___7", "occupation___8", "occupation___9", "occupation_other",

aim1_summary
# this excludes aim 2 index participants, so the numbers are lower.
```

```{r participant-summary, echo=FALSE}
aim2_summary <- ind %>%
  select("aim", "sex","age_cat", "read_write", "study_site", 
         "enrolled_school", "highest_educ", "school_level", "occupation") %>%
  filter(aim==2) %>%
  tbl_summary(by = study_site,
              percent="column",
              digits = all_categorical() ~ 0) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Aim 2 Particiant Individual Information in Mozambique**")
# "occupation___0", "occupation___1", "occupation___2", "occupation___3", "occupation___4","occupation___5", "occupation___6", "occupation___7", "occupation___8", "occupation___9", "occupation_other",

aim2_summary
```

```{r contact_id}
contact_name <- data %>%
  filter(redcap_repeat_instrument == "informaes_sobre_os_membros_da_famlia") %>%
  # filter(rec_id %in% participant_ids) %>%
  group_by(rec_id) %>%
  select(rec_id, hh_member_name)

# generate unique number for each contact
contact_name$hh_member_id <- NA
 
for (i in unique(contact_name$rec_id)) {
  contact_name$hh_member_id[which(contact_name$rec_id==i)] <- 1:nrow(contact_name[which(contact_name$rec_id==i),])
}

rec_id <- sort(rep(unique(contact_name$rec_id), 30))
hh_member_id <- rep(1:30, length(unique(contact_name$rec_id))) # hh members could enter up to 30 records
contact_name_full <- data.frame(rec_id, hh_member_id)

contact_name_full <- contact_name_full %>%
  left_join(contact_name, by=c("rec_id", "hh_member_id")) %>%
  mutate(hh_member_id2 = paste(rec_id, hh_member_id, sep="-")) %>%
  select(rec_id, hh_member_id, hh_member_id2, hh_member_name)
```


```{r hh_contacts_d1}
# generate day 1 contacts

for (i in 1:30) {
  nam <- paste("c", i, sep = ".")
  assign(nam, data %>%
           dplyr::filter(redcap_event_name == "day_1_diary_arm_1") %>%
           dplyr::select("rec_id", "redcap_event_name",
                         "redcap_repeat_instrument","redcap_repeat_instance", 
                         ends_with(paste0("_d1_hh_",i)), 
                         starts_with(paste0("location_contact_d1_hh_", i, "___")), paste0("location_contact_other_d1_", i)) %>%
           dplyr::filter(is.na(redcap_repeat_instrument)) %>%
           left_join(contact_name_full[which(contact_name_full$hh_member_id==i),], by="rec_id")) # "individual_id",
}

names(c.1) <- str_remove(names(c.1), "_1") 
names(c.2) <- str_remove(names(c.2), "_2") 
names(c.3) <- str_remove(names(c.3), "_3") 
names(c.4) <- str_remove(names(c.4), "_4") 
names(c.5) <- str_remove(names(c.5), "_5") 
names(c.6) <- str_remove(names(c.6), "_6") 
names(c.7) <- str_remove(names(c.7), "_7") 
names(c.8) <- str_remove(names(c.8), "_8") 
names(c.9) <- str_remove(names(c.9), "_9") 
names(c.10) <- str_remove(names(c.10), "_10") 
names(c.11) <- str_remove(names(c.11), "_11") 
names(c.12) <- str_remove(names(c.12), "_12") 
names(c.13) <- str_remove(names(c.13), "_13") 
names(c.14) <- str_remove(names(c.14), "_14") 
names(c.15) <- str_remove(names(c.15), "_15") 
names(c.16) <- str_remove(names(c.16), "_16") 
names(c.17) <- str_remove(names(c.17), "_17") 
names(c.18) <- str_remove(names(c.18), "_18") 
names(c.19) <- str_remove(names(c.19), "_19") 
names(c.20) <- str_remove(names(c.20), "_20") 
names(c.21) <- str_remove(names(c.21), "_21") 
names(c.22) <- str_remove(names(c.22), "_22") 
names(c.23) <- str_remove(names(c.23), "_23") 
names(c.24) <- str_remove(names(c.24), "_24") 
names(c.25) <- str_remove(names(c.25), "_25")
names(c.26) <- str_remove(names(c.26), "_26") 
names(c.27) <- str_remove(names(c.27), "_27") 
names(c.28) <- str_remove(names(c.28), "_28") 
names(c.29) <- str_remove(names(c.29), "_29") 
names(c.30) <- str_remove(names(c.30), "_30") 

cont_d1_hh <- rbind(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20,c.21,c.22,c.23,c.24,c.25,c.26,
   c.27,c.28,c.29,c.30)
cont_d1_hh <- cont_d1_hh[which(!is.na(cont_d1_hh$contact_id_d1_hh)),]

rm(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20,c.21,c.22,c.23,c.24,c.25,c.26,
   c.27,c.28,c.29,c.30)

cont_d1_hh <- cont_d1_hh %>%
  # filter(redcap_repeat_instrument == "informaes_sobre_os_membros_da_famlia") %>%
  # filter(rec_id %in% participant_ids) %>%
  group_by(rec_id) %>%
  mutate(hh_member_id = cur_group_id()) %>%
  ungroup() %>%
  group_by(rec_id) %>%
  mutate(n=1:n()) %>%
  mutate(contact_id = paste(hh_member_id, n, sep="-")) %>%
  select("rec_id", "redcap_event_name", "redcap_repeat_instrument",
         "redcap_repeat_instance", "contact_id_d1_hh", "touch_contact_d1_hh",
         "where_contact_d1_hh", "contact_mask_d1_hh", "duration_contact_d1_hh",
         "frequency_contact_d1_hh", "known_contact_d1_hh", "location_contact_d1_hh___0",
         "location_contact_d1_hh___1", "location_contact_d1_hh___2", 
         "location_contact_d1_hh___3", "location_contact_d1_hh___4", 
         "location_contact_d1_hh___5", "location_contact_d1_hh___6",
         "location_contact_d1_hh___7", "location_contact_d1_hh___8", 
         "location_contact_d1_hh___9", "location_contact_d1_hh___10", 
         "location_contact_d1_hh___11", "location_contact_other_d1",
         "contact_id", "hh_member_id","hh_member_id2", "hh_member_name") # drop hh_member_name
# "individual_id",
```


```{r hh_contacts_d2}
# generate day 2 contacts
for (i in 1:30) {
  nam <- paste("c", i, sep = ".")
  assign(nam, data %>%
           dplyr::filter(redcap_event_name == "day_2_diary_arm_1") %>%
           dplyr::select("rec_id", "redcap_event_name",
                         "redcap_repeat_instrument","redcap_repeat_instance", 
                         ends_with(paste0("_d2_hh_",i)), 
                         starts_with(paste0("location_contact_d2_hh_",i, "___")), paste0("location_contact_other_d2_", i)) %>%
    dplyr::filter(is.na(redcap_repeat_instrument)) %>%
    left_join(contact_name_full[which(contact_name_full$hh_member_id==i),], by="rec_id"))
}


names(c.1) <- str_remove(names(c.1), "_1") 
names(c.2) <- str_remove(names(c.2), "_2") 
names(c.3) <- str_remove(names(c.3), "_3") 
names(c.4) <- str_remove(names(c.4), "_4") 
names(c.5) <- str_remove(names(c.5), "_5") 
names(c.6) <- str_remove(names(c.6), "_6") 
names(c.7) <- str_remove(names(c.7), "_7") 
names(c.8) <- str_remove(names(c.8), "_8") 
names(c.9) <- str_remove(names(c.9), "_9") 
names(c.10) <- str_remove(names(c.10), "_10") 
names(c.11) <- str_remove(names(c.11), "_11") 
names(c.12) <- str_remove(names(c.12), "_12") 
names(c.13) <- str_remove(names(c.13), "_13") 
names(c.14) <- str_remove(names(c.14), "_14") 
names(c.15) <- str_remove(names(c.15), "_15") 
names(c.16) <- str_remove(names(c.16), "_16") 
names(c.17) <- str_remove(names(c.17), "_17") 
names(c.18) <- str_remove(names(c.18), "_18") 
names(c.19) <- str_remove(names(c.19), "_19") 
names(c.20) <- str_remove(names(c.20), "_20") 
names(c.21) <- str_remove(names(c.21), "_21") 
names(c.22) <- str_remove(names(c.22), "_22") 
names(c.23) <- str_remove(names(c.23), "_23") 
names(c.24) <- str_remove(names(c.24), "_24") 
names(c.25) <- str_remove(names(c.25), "_25")
names(c.26) <- str_remove(names(c.26), "_26") 
names(c.27) <- str_remove(names(c.27), "_27") 
names(c.28) <- str_remove(names(c.28), "_28") 
names(c.29) <- str_remove(names(c.29), "_29") 
names(c.30) <- str_remove(names(c.30), "_30") 

cont_d2_hh<- rbind(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20,c.21,c.22,c.23,c.24,c.25,c.26,
   c.27,c.28,c.29,c.30)
cont_d2_hh <- cont_d2_hh[which(!is.na(cont_d2_hh$contact_id_d2_hh)),]

rm(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20,c.21,c.22,c.23,c.24,c.25,c.26,
   c.27,c.28,c.29,c.30)

cont_d2_hh <- cont_d2_hh %>%
  # filter(redcap_repeat_instrument == "informaes_sobre_os_membros_da_famlia") %>%
  # filter(rec_id %in% participant_ids) %>%
  group_by(rec_id) %>%
  mutate(hh_member_id = cur_group_id()) %>% # should be hh group ID?
  ungroup() %>%
  group_by(rec_id) %>%
  mutate(n = 1:n()) %>%
  mutate(contact_id = paste(hh_member_id, n, sep="-")) %>%
  select("rec_id", "redcap_event_name", "redcap_repeat_instrument",
         "redcap_repeat_instance", "contact_id_d2_hh", "touch_contact_d2_hh",
         "where_contact_d2_hh", "contact_mask_d2_hh", "duration_contact_d2_hh",
         "frequency_contact_d2_hh", "known_contact_d2_hh", "location_contact_d2_hh___0",
         "location_contact_d2_hh___1", "location_contact_d2_hh___2", 
         "location_contact_d2_hh___3", "location_contact_d2_hh___4", 
         "location_contact_d2_hh___5", "location_contact_d2_hh___6",
         "location_contact_d2_hh___7", "location_contact_d2_hh___8", 
         "location_contact_d2_hh___9", "location_contact_d2_hh___10", 
         "location_contact_d2_hh___11", "location_contact_other_d2",
         "contact_id", "hh_member_id", "hh_member_id2", "hh_member_name") # drop hh_member_name
# "individual_id",
```

/
/

```{r hh_contacts, echo=FALSE}
# # here, if contact_id_d1_hh == 1 it means that participant had contact with this household member. if we
# use this filter only, we do not report on if participant did not have a contact with this hh member i.e. contact_id_d1_hh == 0. so, MCK changes this to contact_id_d1_hh == 0 | contact_id_d1_hh == 1. so, we filter out contact_id_d1_hh != 2, where 2==not applicable. What does NA mean here?
# SOMETHING TO THINK ABOUT

# table(cont_d1_hh$contact_id_d1_hh, useNA = "always")
# table(cont_d2_hh$contact_id_d2_hh, useNA = "always")


# merge d1 and d2 household contact data
cont_d1_hh <- cont_d1_hh[which(cont_d1_hh$contact_id_d1_hh != 2),] # cont_d1_hh$contact_id_d1_hh !=2
cont_d2_hh <- cont_d2_hh[which(cont_d2_hh$contact_id_d2_hh != 2),]

# rename contact_id_d1_hh to indicate if participant had a contact with this person
cont_d1_hh <- cont_d1_hh %>%
  rename(had_contact = contact_id_d1_hh)
cont_d2_hh <- cont_d2_hh %>%
  rename(had_contact = contact_id_d2_hh)

# delete the _d1_hh tag from each var name
names(cont_d1_hh)[grep("_d1_hh", names(cont_d1_hh))] <- gsub("_d1_hh", "", 
                                                             names(cont_d1_hh)[grep("_d1_hh", names(cont_d1_hh))])
names(cont_d1_hh)[25] <- "location_contact_other"


names(cont_d2_hh)[grep("_d2_hh", names(cont_d2_hh))] <- gsub("_d2_hh", "", 
                                                             names(cont_d2_hh)[grep("_d2_hh", names(cont_d2_hh))])
names(cont_d2_hh)[25] <- "location_contact_other"

# names(cont_d1_hh); names(cont_d2_hh)
# names(cont_d1_hh) == names(cont_d2_hh)

# specify contact day and merge d1 and d2 data
cont_d1_hh$Day1or2 <- 1
cont_d2_hh$Day1or2 <- 2

contact_hh_all <- rbind(cont_d1_hh, cont_d2_hh) # 15445
contact_hh_all <- contact_hh_all[-which(is.na(contact_hh_all$hh_member_name)),]
# 253 records deleted without names

contact_hh_all$hh_membership <- "Member"

# delete duplicated contact records
contact_hh_all <- contact_hh_all %>%
  distinct(rec_id, hh_member_id2, Day1or2, .keep_all = TRUE) # n=15445, hh_member_id, 
  # distinct(rec_id, Day1or2, .keep_all = TRUE) # initially, this was the code, but only retains one hh member.


# merge hh contact data with household member data
hh_member <- data %>%
  dplyr::filter(redcap_repeat_instrument == "informaes_sobre_os_membros_da_famlia") %>%
  dplyr::select("rec_id", hh_member_hoh,
                hh_member_name, hh_member_id, hh_member_sensor, hh_member_sex,
                hh_member_age, hh_member_relationship,
                hh_member_relationship_other, share_room, share_bed, cook_food,
                #hh_member_hhform, hh_member_instance,
                informaes_de_agregado_familiar_e_casa_complete) %>%
  # hh_member_sex_outro, 
  distinct(rec_id, hh_member_name, .keep_all = TRUE) # 7768 household members recorded

contact_hh_all <- contact_hh_all %>% 
  left_join(hh_member, by=c("rec_id", "hh_member_name")) # n=2641, ok

# generate variable that shows if a repeat contact on d2 (2) vs contact on 1 day only (1)
contact_hh_repeat <- contact_hh_all %>%
  group_by(rec_id, hh_member_name, hh_member_id.y) %>%
  summarise(contact_count=n())


contact_hh_all <- contact_hh_all %>%
  left_join(contact_hh_repeat, by=c("rec_id","hh_member_name","hh_member_id.y")) %>%
  # label repeat and unique contacts
  mutate(repeat_contact_d2 = ifelse(contact_count == 2 & Day1or2 == 2, "repeat", 
                                       ifelse(contact_count == 1 & Day1or2 == 2, "unique", "unique"))) %>%
  left_join(study_site, by="rec_id") %>%
  mutate(fromdayone = ifelse(((contact_count == 2 & Day1or2 == 2) | 
                                (Day1or2 == 1 & contact_count == 2)), "Both Days",
                             ifelse(contact_count == 1 & Day1or2 == 2, "Day2 Only",
                                    ifelse(contact_count == 1 & Day1or2 == 1, "Day1 Only", NA)))) %>%
  # keep select variables
  select("rec_id","study_site", "hh_membership", "hh_member_hoh", "hh_member_id2",
         "hh_member_sex", "hh_member_age", "hh_member_relationship", "hh_member_relationship_other",
         "had_contact", "Day1or2", "known_contact", "touch_contact", "where_contact", 
         "contact_mask", "duration_contact", "frequency_contact", "share_room", 
         "share_bed", "cook_food", "contact_count", "repeat_contact_d2",    
         "study_site", "aim", "isindex", "fromdayone", "location_contact___0", 
         "location_contact___1", "location_contact___2", "location_contact___3", 
         "location_contact___4", "location_contact___5", "location_contact___6", 
         "location_contact___7", "location_contact___8", "location_contact___9", 
         "location_contact___10", "location_contact___11", "location_contact_other",
         "redcap_event_name") #  "contact_id",

```

\
\

```{r nonhh_contacts, echo=False}
# Non-household contacts
cont_d1_nonhh <- data %>% 
  dplyr::filter(redcap_repeat_instrument == "dirio_de_contato_dia_1") %>%
  dplyr::select("rec_id","redcap_event_name","redcap_repeat_instance",
                "redcap_repeat_instrument","contact_id_d1","contact_age_yn_d1","age_contact_d1",
                "age_group_contact_d1","sex_contact_d1","touch_contact_d1","where_contact_d1",
                "location_contact_d1___0","location_contact_d1___1","location_contact_d1___2",
                "location_contact_d1___3","location_contact_d1___4","location_contact_d1___5",
                "location_contact_d1___6","location_contact_d1___7","location_contact_d1___8",
                "location_contact_d1___9","location_contact_d1___10","location_contact_d1___11",
                "location_contact_other_d1","contact_mask_d1","duration_contact_d1",
                "frequency_contact_d1","known_contact_d1","dirio_de_contato_dia_1_complete")
# "individual_id",


# day 1 of keeping diary
cont_d1_diarydate <- data %>%
  dplyr::filter(redcap_event_name == "day_1_diary_arm_1") %>%
  dplyr::select("rec_id", "survey_date_d1") %>%
  rename(survey_date = survey_date_d1) %>%
  na.omit()
# 1920 vs 1960 records. keep only those with complete day of keeping diary reported?

cont_d1_nonhh <- cont_d1_nonhh %>%
  full_join(cont_d1_diarydate, by="rec_id") # include date of survey in data
names(cont_d1_nonhh)[grep("_d1", names(cont_d1_nonhh))] <-  gsub("_d1", "", 
                                                     names(cont_d1_nonhh)[grep("_d1", names(cont_d1_nonhh))])
# names(cont_d1)[names(cont_d1)=="survey_date"] <- "survey_date_d1"


cont_d2_nonhh = data %>% 
  dplyr::filter(redcap_repeat_instrument == "dirio_de_contato_dia_2") %>% 
  dplyr::select("rec_id","redcap_event_name", "redcap_repeat_instance",
                "redcap_repeat_instrument","contact_id_d2", "contact_age_yn_d2","age_contact_d2",
                "age_group_contact_d2","sex_contact_d2", "touch_contact_d2","where_contact_d2",
                "location_contact_d2___0", "location_contact_d2___1","location_contact_d2___2",
                "location_contact_d2___3", "location_contact_d2___4","location_contact_d2___5",
                "location_contact_d2___6", "location_contact_d2___7","location_contact_d2___8",
                "location_contact_d2___9", "location_contact_d2___10","location_contact_d2___11",
                "location_contact_other_d2", "contact_mask_d2","duration_contact_d2","frequency_contact_d2",
                "known_contact_d2", "dirio_de_contato_dia_1_complete")
# "individual_id",
# 
# day 2 of keeping diary
cont_d2_diarydate <- data %>%
  dplyr::filter(redcap_event_name == "day_2_diary_arm_1") %>%
  dplyr::select("rec_id","survey_date_d2") %>%
  rename(survey_date = survey_date_d2) %>%
  na.omit()

cont_d2_nonhh <- cont_d2_nonhh %>%
  full_join(cont_d2_diarydate, by="rec_id") # include date of survey in data
names(cont_d2_nonhh)[grep("_d2", names(cont_d2_nonhh))] <-  gsub("_d2", "", 
                                                                 names(cont_d2_nonhh)[grep("_d2", names(cont_d2_nonhh))])
# names(cont_d2)[names(cont_d2)=="survey_date"] <- "survey_date_d2"


# names(cont_d1) == names(cont_d2)
cont_d1_nonhh$Day1or2 <- 1
cont_d2_nonhh$Day1or2 <- 2
cont_d2_nonhh$repeat_contact_d2 <- "unique"
cont_d1_nonhh$repeat_contact_d2 <- NA

# merge d1 and d2 nonhh contacts
cont_d1d2_norep <- rbind(cont_d1_nonhh, cont_d2_nonhh)

cont_d1d2_norep <- cont_d1d2_norep %>%
  select("rec_id","survey_date",
         "redcap_event_name","redcap_repeat_instrument", "redcap_repeat_instance",
         "contact_id","touch_contact","where_contact", "contact_mask",
         "duration_contact","frequency_contact","known_contact",
         "location_contact___0","location_contact___1","location_contact___2",
         "location_contact___3","location_contact___4","location_contact___5",
         "location_contact___6","location_contact___7","location_contact___8",
         "location_contact___9","location_contact___10","location_contact___11",
         "location_contact_other","Day1or2","repeat_contact_d2","contact_age_yn",
         "age_contact","age_group_contact","sex_contact") # "individual_id",

```

\
\

```{r}
contact_name_d1 <- data %>% 
  filter(redcap_repeat_instrument == "dirio_de_contato_dia_1") %>%
  group_by(rec_id) %>%
  select(rec_id, contact_id_d1, "contact_age_yn_d1", "age_contact_d1",
         "age_group_contact_d1", "sex_contact_d1")

contact_name_d1$contact_sequence_id <- NA
for (i in unique(contact_name_d1$rec_id)) {
  contact_name_d1$contact_sequence_id[which(contact_name_d1$rec_id==i)] <- 1:nrow(contact_name_d1[which(contact_name_d1$rec_id==i),]) 
  }

rec_id <- sort(rep(unique(contact_name_d1$rec_id), 20))
contact_sequence_id <- rep(1:20, length(unique(contact_name_d1$rec_id)))
contact_name_d1_full <- data.frame(rec_id, contact_sequence_id)

contact_name_d1_full <- contact_name_d1_full %>%
  left_join(contact_name_d1, by=c("rec_id", "contact_sequence_id"))

for (i in 1:20) {
  nam <- paste("c", i, sep = ".")
  assign(nam, data %>%
           dplyr::filter(redcap_event_name == "day_2_diary_arm_1") %>% 
           dplyr::select("rec_id","individual_id","redcap_event_name", "redcap_repeat_instrument",
                         "redcap_repeat_instance", ends_with(paste0("_d2_rep_",i)), starts_with(paste0("location_contact_d2_rep_",i)) )%>%
    dplyr::filter(is.na(redcap_repeat_instrument)) %>%
    left_join(contact_name_d1_full[which(contact_name_d1_full$contact_sequence_id==i),], by="rec_id"))
}

c.1 <- c.1[,c(1:25,146:151)]
c.2 <- c.2[,c(1:25,38:43)]


names(c.1) <- str_remove(names(c.1), "_1") 
names(c.2) <- str_remove(names(c.2), "_2") 
names(c.3) <- str_remove(names(c.3), "_3") 
names(c.4) <- str_remove(names(c.4), "_4") 
names(c.5) <- str_remove(names(c.5), "_5") 
names(c.6) <- str_remove(names(c.6), "_6") 
names(c.7) <- str_remove(names(c.7), "_7") 
names(c.8) <- str_remove(names(c.8), "_8") 
names(c.9) <- str_remove(names(c.9), "_9") 
names(c.10) <- str_remove(names(c.10), "_10") 
names(c.11) <- str_remove(names(c.11), "_11") 
names(c.12) <- str_remove(names(c.12), "_12") 
names(c.13) <- str_remove(names(c.13), "_13") 
names(c.14) <- str_remove(names(c.14), "_14") 
names(c.15) <- str_remove(names(c.15), "_15") 
names(c.16) <- str_remove(names(c.16), "_16") 
names(c.17) <- str_remove(names(c.17), "_17") 
names(c.18) <- str_remove(names(c.18), "_18") 
names(c.19) <- str_remove(names(c.19), "_19") 
names(c.20) <- str_remove(names(c.20), "_20") 


cont_d2_rep <- rbind(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20)
cont_d2_rep <- cont_d2_rep[which(cont_d2_rep$repeat_contact_d2_rep == 1),]

rm(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20)

cont_d2_rep$Day1or2 <- 2
cont_d2_rep$repeat_contact_d2 <- "repeat"

names(cont_d2_rep)[grep("_d2_rep", names(cont_d2_rep))] <-  gsub("_d2_rep", "",
                                                                 names(cont_d2_rep)[grep("_d2_rep",
                                                                                         names(cont_d2_rep))])
names(cont_d2_rep)[grep("_d1", names(cont_d2_rep))] <-  gsub("_d1", "", 
                                                             names(cont_d2_rep)[grep("_d1",
                                                                                     names(cont_d2_rep))])


cont_d2_rep <- cont_d2_rep %>%
  select("rec_id","redcap_event_name","redcap_repeat_instrument", "redcap_repeat_instance","contact_id","touch_contact","where_contact", "contact_mask","duration_contact","frequency_contact","known_contact", "location_contact___0","location_contact___1","location_contact___2", "location_contact___3","location_contact___4","location_contact___5", "location_contact___6","location_contact___7","location_contact___8", "location_contact___9","location_contact___10","location_contact___11", "location_contact_other","Day1or2","repeat_contact_d2","contact_age_yn", "age_contact","age_group_contact","sex_contact")

cont_d2_rep <- cont_d2_rep %>%
  left_join(cont_d2_diarydate, by="rec_id")

#names(cont_d2_rep)==names(cont_d1d2_norep)
contact_nonhh_all <- rbind(cont_d1d2_norep, cont_d2_rep)
contact_nonhh_all$hh_membership <- "Non-member"
# names(cont_d2_rep)
# names(cont_d1d2_norep)

cont_nonhh_repeat <- contact_nonhh_all %>%
  group_by(rec_id, contact_id) %>%
  summarise(contact_count=n())


contact_nonhh_all <- contact_nonhh_all %>%
  left_join(study_site, by="rec_id") %>% 
  left_join(cont_nonhh_repeat, by=c("rec_id","contact_id")) %>%
  mutate(fromdayone = ifelse(((contact_count == 2 & Day1or2 == 2) | 
                                (Day1or2 == 1 & contact_count == 2)), "Both Days",
                             ifelse(((contact_count == 1 & Day1or2 == 2)), "Day2 Only", 
                                    ifelse((Day1or2 == 1 & contact_count == 1), "Day1 Only", NA))))

contact_nonhh_all$fromdayone[which(contact_nonhh_all$contact_count > 2 & 
                                  contact_nonhh_all$repeat_contact_d2=="unique" & 
                                  contact_nonhh_all$Day1or2==2)] <- "Day2 Only"

contact_nonhh_all$fromdayone[which(contact_nonhh_all$contact_count > 2 & 
                            contact_nonhh_all$repeat_contact_d2=="repeat" & 
                            contact_nonhh_all$Day1or2==2)] <- "Both Days"


cont_repeat_dup <- contact_nonhh_all %>%
  filter(contact_count > 2) %>%
  group_by(rec_id, Day1or2, contact_id, fromdayone) %>%
  summarise(contact_count=n())

```


```{r}
# here, check ages 10-19 and convert to 10-14 and 15-19
# 




contact_hh_all <- contact_hh_all %>%
  full_join(cont_d2_diarydate, by="rec_id")

# table(contact_hh_all$hh_member_age, useNA = "always")
contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(age_group_contact = case_when(hh_member_age == 0 ~ "<6mo",
                                              hh_member_age == 1 ~ "6-11mo",
                                              hh_member_age == 2 ~ "1-4y",
                                              hh_member_age == 3 ~ "5-9y",
                                              hh_member_age == 4 ~ "10-14y",
                                              hh_member_age == 5 ~ "15-19y",
                                              hh_member_age == 5 ~ "20-29y",
                                              hh_member_age == 6 ~ "30-39y",
                                              hh_member_age == 7 ~ "40-59y", # 40-59
                                              hh_member_age == 8 ~ "40-59y", # 40-59
                                              hh_member_age == 9 ~ "60+y",
                                              hh_member_age == 10 ~ "Missing",
                                              hh_member_age == 0 ~ "6-11mo",
                                              hh_member_age %in% 1:4 ~ "1-4y",
                                              hh_member_age %in% 5:9 ~ "5-9y",
                                              hh_member_age %in% 10:14 ~ "10-14y",
                                              hh_member_age %in% 15:19 ~ "15-19y",
                                              hh_member_age %in% 20:29 ~ "20-29y",
                                               hh_member_age %in% 30:39 ~ "30-39y",
                                               hh_member_age %in% 40:49 ~ "40-59y", # 40-59
                                               hh_member_age %in% 50:59 ~ "40-59y", # 40-59
                                               hh_member_age >=60 ~ "60+y"))

# table(contact_hh_all$age_group_contact, useNA = "always")
#  drop "I don't know" and NA
contact_hh_all <- contact_hh_all %>% #15840
  subset(age_group_contact != "Missing")  # n=397 unknown ages

contact_hh_all$age_group_contact = factor(contact_hh_all$age_group_contact, 
                   levels = c("<6mo", "6-11mo", "1-4y", "5-9y", 
                              "10-14y","15-19y", "20-29y", "30-39y", 
                              "40-59y", "60+y")) #, "Missing")) <- dropped and NA
label(contact_hh_all$age_group_contact) <- "Age group"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(contact_id = case_when(had_contact == 0 ~ "No",
                                         had_contact == 1 ~ "Yes",
                                         had_contact == 2 ~ "Not applicable")) 
# the data dict only says 0, No | 1, Yes, but actually there are 3 levels in this variable 
label(contact_hh_all$had_contact) <- "Did you have contact with this household member?"

contact_hh_all <- contact_hh_all %>% 
  dplyr::mutate(touch_contact = case_when(touch_contact == 0 ~ "No",
                                         touch_contact == 1 ~ "Yes",
                                         touch_contact == 2 ~ "I don't remember"))
contact_hh_all$touch_contact = factor(contact_hh_all$touch_contact, 
                   levels = c("Yes", "No", "I don't remember"))
label(contact_hh_all$touch_contact) <- "Did you touch?"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(where_contact = case_when(where_contact == 0 ~ "Indoors",
                                         where_contact == 1 ~ "Outdoors",
                                         where_contact == 2 ~ "Both"))
contact_hh_all$where_contact <- factor(contact_hh_all$where_contact,
                                       levels = c("Indoors", "Outdoors", "Both"))
label(contact_hh_all$where_contact) <- "Did the contact occur indoors or outdoors?"

label(contact_hh_all$location_contact___0) <- "My home"
label(contact_hh_all$location_contact___1) <- "Other home"
label(contact_hh_all$location_contact___2) <- "School"
label(contact_hh_all$location_contact___3) <- "Work"
label(contact_hh_all$location_contact___4) <- "Transport/Hub"
label(contact_hh_all$location_contact___5) <- "Market/Shop"
label(contact_hh_all$location_contact___6) <- "Street"
label(contact_hh_all$location_contact___7) <- "Well"
label(contact_hh_all$location_contact___8) <- "Agricultural Field"
label(contact_hh_all$location_contact___9) <- "Playground"
label(contact_hh_all$location_contact___10) <- "Place of worship"
label(contact_hh_all$location_contact___11) <- "Other"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(contact_mask = case_when(contact_mask == 0 ~ "No mask was worn during the encounter",
                                        contact_mask == 1 ~ "Yes, for the entire encounter",
                                        contact_mask == 2 ~ "Yes, during parts of encounter",
                                        contact_mask == 3 ~ "I don't remember"))
contact_hh_all$contact_mask <- factor(contact_hh_all$contact_mask,
                                      levels = c("No mask was worn during the encounter",
                                                 "Yes, for the entire encounter",
                                                 "Yes, during parts of encounter",
                                                 "I don't remember"))
label(contact_hh_all$contact_mask) <- "Was this individual wearing a mask when you had contact?"

contact_hh_all = contact_hh_all %>%
  dplyr::mutate(duration_contact = case_when(duration_contact == 0 ~ "<5 mins",
                                               duration_contact == 1 ~ "5-15 mins",
                                               duration_contact == 2 ~ "16-30 mins",
                                               duration_contact == 3 ~ "31 mins-1 hr",
                                               duration_contact == 4 ~ "1-4 hrs",
                                               duration_contact == 5 ~ ">4 hrs"))
contact_hh_all$duration_contact <- factor(contact_hh_all$duration_contact,
                                          levels = c("<5 mins", "5-15 mins", 
                                                     "16-30 mins", "31 mins-1 hr",
                                                     "1-4 hrs", ">4 hrs"))
label(contact_hh_all$duration_contact) <- "What was the total time spent with the contact on this day?"

contact_hh_all = contact_hh_all %>%
  dplyr::mutate(frequency_contact = case_when(frequency_contact == 0 ~ "Never met before",
                                               frequency_contact == 1 ~ "Rarely",
                                               frequency_contact == 2 ~ "Daily or almost daily",
                                               frequency_contact == 3 ~ "1-3 times per week",
                                               frequency_contact == 4 ~ "Once every 2 weeks",
                                               frequency_contact == 5 ~ "Once per month",
                                               frequency_contact == 6 ~ "Once every 3 months"))
contact_hh_all$frequency_contact <- factor(contact_hh_all$frequency_contact,
                                           levels = c("Never met before", "Rarely",
                                                      "Daily or almost daily","1-3 times per week",
                                                      "Once every 2 weeks", "Once per month",
                                                      "Once every 3 months"))
label(contact_hh_all$frequency_contact) <- "In the past 6 months, how often have you had contact with this person?"

contact_hh_all = contact_hh_all %>%
  dplyr::mutate(known_contact = case_when(known_contact == 0 ~ "Never met before",
                                               known_contact == 1 ~ "<1 yr",
                                               known_contact == 2 ~ "1-2 yrs",
                                               known_contact == 3 ~ "3-5 yrs",
                                               known_contact == 4 ~ "6-10 yrs",
                                               known_contact == 5 ~ ">10 yrs"))
contact_hh_all$known_contact <- factor(contact_hh_all$known_contact,
                                       levels = c("Never met before", "<1 yr",
                                                  "1-2 yrs", "3-5 yrs", "6-10 yrs",
                                                  ">10 yrs"))
label(contact_hh_all$known_contact) <- "How long have you known this person?"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(contact_sex = case_when(hh_member_sex == 0 ~ "Female",
                                        hh_member_sex == 1 ~ "Male",
                                        TRUE ~ "Other"))
                                        # hh_member_sex == 2 ~ "Transsexual Female",
                                        # hh_member_sex == 3 ~ "Transsexual Male",
                                        # hh_member_sex == 4 ~ "Other"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(hh_member_relationship = case_when(hh_member_relationship == 0 ~ "Spouse",
                                        hh_member_relationship == 1 ~ "Sibiling",
                                        hh_member_relationship == 2 ~ "Child",
                                        hh_member_relationship == 3 ~ "Parent",
                                        hh_member_relationship == 4 ~ "Grandparent",
                                        hh_member_relationship == 5 ~ "Uncle/Aunt",
                                        hh_member_relationship == 6 ~ "Grandchild",
                                        hh_member_relationship == 7 ~ "Nephew",
                                        hh_member_relationship == 8 ~ "Other relative",
                                        hh_member_relationship == 9 ~ "Not relative",
                                        hh_member_relationship == 10 ~ "Self (HoH)"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(share_room = case_when(share_room == 0 ~ "No",
                                         share_room == 1 ~ "Yes"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(share_bed = case_when(share_bed == 0 ~ "No",
                                        share_bed == 1 ~ "Yes"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(cook_food = case_when(cook_food == 0 ~ "No",
                                        cook_food == 1 ~ "Yes"))
```



```{r}

contact_nonhh_all <- contact_nonhh_all %>% 
  dplyr::mutate(touch_contact = case_when(touch_contact == 0 ~ "No",
                                         touch_contact == 1 ~ "Yes",
                                         touch_contact == 2 ~ "I don't remember"))
contact_nonhh_all$touch_contact = factor(contact_nonhh_all$touch_contact, 
                   levels = c("Yes", "No", "I don't remember"))
label(contact_nonhh_all$touch_contact) <- "Did you touch?"

contact_nonhh_all = contact_nonhh_all %>% 
  dplyr::mutate(where_contact = case_when(where_contact == 0 ~ "Indoors",
                                          where_contact == 1 ~ "Outdoors",
                                          where_contact == 2 ~ "Both"))
contact_nonhh_all$where_contact <- factor(contact_nonhh_all$where_contact,
                                       levels = c("Indoors", "Outdoors", "Both"))
label(contact_nonhh_all$where_contact) <- "Did the contact occur indoors or outdoors?"

label(contact_nonhh_all$location_contact___0) <- "My home"
label(contact_nonhh_all$location_contact___1) <- "Other home"
label(contact_nonhh_all$location_contact___2) <- "School"
label(contact_nonhh_all$location_contact___3) <- "Work"
label(contact_nonhh_all$location_contact___4) <- "Transport/Hub"
label(contact_nonhh_all$location_contact___5) <- "Market/Shop"
label(contact_nonhh_all$location_contact___6) <- "Street"
label(contact_nonhh_all$location_contact___7) <- "Well"
label(contact_nonhh_all$location_contact___8) <- "Agricultural Field"
label(contact_nonhh_all$location_contact___9) <- "Playground"
label(contact_nonhh_all$location_contact___10) <- "Place of worship"
label(contact_nonhh_all$location_contact___11) <- "Other"


contact_hh_all$contact_mask <- factor(contact_hh_all$contact_mask,
                                      levels = c("No mask was worn during the encounter",
                                                 "Yes, for the entire encounter",
                                                 "Yes, during parts of encounter",
                                                 "I don't remember"))

contact_nonhh_all = contact_nonhh_all %>% 
  dplyr::mutate(contact_mask = case_when(contact_mask == 0 ~ "No mask was worn during the encounter",
                                        contact_mask == 1 ~ "Yes, for the entire encounter",
                                        contact_mask == 2 ~ "Yes, during parts of encounter",
                                        contact_mask == 3 ~ "I don't remember"))
contact_nonhh_all$contact_mask <- factor(contact_nonhh_all$contact_mask,
                                   levels = c("No mask was worn during the encounter",
                                              "Yes, for the entire encounter",
                                              "Yes, during parts of encounter",
                                              "I don't remember"))
label(contact_nonhh_all$contact_mask) <- "Was this individual wearing a mask when you had contact?"

contact_nonhh_all = contact_nonhh_all %>%
  dplyr::mutate(duration_contact = case_when(duration_contact == 0 ~ "<5 mins",
                                               duration_contact == 1 ~ "5-15 mins",
                                               duration_contact == 2 ~ "16-30 mins",
                                               duration_contact == 3 ~ "31 mins-1 hr",
                                               duration_contact == 4 ~ "1-4 hrs",
                                               duration_contact == 5 ~ ">4 hrs"))
contact_nonhh_all$duration_contact <- factor(contact_nonhh_all$duration_contact,
                                       levels = c("<5 mins", "5-15 mins", 
                                                  "16-30 mins", "31 mins-1 hr",
                                                  "1-4 hrs", ">4 hrs"))
label(contact_nonhh_all$duration_contact) <- "What was the total time spent with the contact on this day?"

contact_nonhh_all = contact_nonhh_all %>%
  dplyr::mutate(frequency_contact = case_when(frequency_contact == 0 ~ "Never met before",
                                               frequency_contact == 1 ~ "Rarely",
                                               frequency_contact == 2 ~ "Daily or almost daily",
                                               frequency_contact == 3 ~ "1-3 times per week",
                                               frequency_contact == 4 ~ "Once every 2 weeks",
                                               frequency_contact == 5 ~ "Once per month",
                                               frequency_contact == 6 ~ "Once every 3 months"))
contact_nonhh_all$frequency_contact <- factor(contact_nonhh_all$frequency_contact,
                                        levels = c("Never met before", "Rarely",
                                                   "Daily or almost daily","1-3 times per week",
                                                   "Once every 2 weeks", "Once per month",
                                                   "Once every 3 months"))
label(contact_nonhh_all$frequency_contact) <- "In the past 6 months, how often have you had contact with this person?"

contact_nonhh_all = contact_nonhh_all %>%
  dplyr::mutate(known_contact = case_when(known_contact == 0 ~ "Never met before",
                                               known_contact == 1 ~ "<1 year",
                                               known_contact == 2 ~ "1-2 years",
                                               known_contact == 3 ~ "3-5 years",
                                               known_contact == 4 ~ "6-10 years",
                                               known_contact == 5 ~ ">10 years"))
contact_nonhh_all$known_contact <- factor(contact_nonhh_all$known_contact,
                                          levels = c("Never met before", "<1 yr",
                                                     "1-2 yrs", "3-5 yrs", "6-10 yrs",
                                                     ">10 yrs"))

label(contact_nonhh_all$known_contact) <- "How long have you known this person?"

contact_nonhh_all = contact_nonhh_all %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                       study_site == 2 ~ "Polana Caniço")) 

contact_nonhh_all = contact_nonhh_all %>% 
  dplyr::mutate(contact_age_yn = case_when(contact_age_yn == 0 ~ "No",
                                           contact_age_yn == 1 ~ "Yes")) 
label(contact_nonhh_all$contact_age_yn) <- "Do you know the contact age?"

contact_nonhh_all = contact_nonhh_all %>% 
  dplyr::mutate(age_group_contact = case_when(age_group_contact == 0 ~ "<6mo",
                                              age_group_contact == 1 ~ "6-11mo",
                                              age_group_contact == 2 ~ "1-4y",
                                              age_group_contact == 3 ~ "5-9y",
                                              age_group_contact == 4 ~ "10-14y",
                                              age_group_contact == 5 ~ "15-19y",
                                              age_group_contact == 5 ~ "20-29y",
                                              age_group_contact == 6 ~ "30-39y",
                                              age_group_contact == 7 ~ "40-59y", # 40-59
                                              age_group_contact == 8 ~ "40-59y", # 40-59
                                              age_group_contact == 9 ~ "60+y",
                                              age_group_contact == 10 ~ "Missing",
                                              age_contact == 0 ~ "6-11mo",
                                              age_contact %in% 1:4 ~ "1-4y",
                                              age_contact %in% 5:9 ~ "5-9y",
                                              age_contact %in% 10:19 ~ "10-14y",
                                              age_contact %in% 10:19 ~ "15-19y",
                                              age_contact %in% 20:29 ~ "20-29y",
                                              age_contact %in% 30:39 ~ "30-39y",
                                              age_contact %in% 40:49 ~ "40-59y", # 40-59
                                              age_contact %in% 50:59 ~ "40-59y", # 40-59
                                              age_contact >=60 ~ "60+y"))
contact_nonhh_all <- contact_nonhh_all %>% 
  subset(age_group_contact != "Missing")

contact_nonhh_all$age_group_contact = factor(contact_nonhh_all$age_group_contact, 
                   levels = c("<6mo", "6-11mo", "1-4y", "5-9y", 
                              "10-14y", "15-19y", "20-29y", "30-39y", 
                              "40-59y", "60+y"))

contact_nonhh_all = contact_nonhh_all %>% 
  dplyr::mutate(contact_sex = case_when(sex_contact == 0 ~ "Female",
                                        sex_contact == 1 ~ "Male",
                                        TRUE ~ "Other"))
                                        # sex_contact == 2 ~ "Transsexual Female",
                                        # sex_contact == 3 ~ "Transsexual Male",
                                        # sex_contact == 4 ~ "Other"))
```


```{r}
# Merge household and hon-household contacts
# contact_hh_rural <- contact_hh_all[which(contact_hh_all$study_site=="Manhiça"),]
# contact_nonhh_rural <- contact_nonhh_all[which(contact_nonhh_all$study_site=="Manhiça"),]

# contact_nonhh_rural$hh_membership <- "Non-member"
# contact_nonhh_rural$relationship <- NA # relationship data was not collected for non-household members

# contact_hh_rural$hh_membership <- "Member"
# contact_hh_rural <- contact_hh_rural %>%
#   rename(relationship = hh_member_relationship)


contact_vars <- c("rec_id", "study_site", "survey_date", "age_group_contact", 
               "contact_sex","touch_contact", "fromdayone",
               "where_contact","contact_mask", "duration_contact", "frequency_contact",
               "known_contact", "hh_membership", "relationship",
               "location_contact___0","location_contact___1","location_contact___2",
               "location_contact___3", "location_contact___4", "location_contact___5",
               "location_contact___6", "location_contact___7","location_contact___8",
               "location_contact___9", "location_contact___10", "location_contact___11")

ind_contact_hh <- contact_hh_all %>%
  left_join(ind, by = "rec_id")

ind_contact_nonhh <- contact_nonhh_all %>%
  left_join(ind, by = "rec_id")


contact_hh_all <- contact_hh_all %>%
  select(any_of(contact_vars))

contact_nonhh_all <- contact_nonhh_all %>%
  select(any_of(contact_vars))

# keep only ids that are common in both data sets. this should move up in cleaning, 
# to keep only ids that are in participant file. 
# intersect_ids <- intersect(unique(contact_hh_all$rec_id),
#                            unique(contact_nonhh_all$rec_id))
# length(intersect_ids)
# 
# nrow(contact_hh_all) # n=1950
# nrow(contact_nonhh_all) # n=24460
# 
# contact_hh_all <- contact_hh_all[contact_hh_all$rec_id %in% intersect_ids,]
# contact_nonhh_all <- contact_nonhh_all[contact_nonhh_all$rec_id %in% intersect_ids,]
# nrow(contact_hh_all) # n=
# nrow(contact_nonhh_all) # n=12013
# # how do we have 12447 unlinked records?

contact_all <- rbind(contact_hh_all, contact_nonhh_all) %>%
  left_join(study_site, by="rec_id") %>%
  subset(select = -c(study_site.y)) %>%
  rename(study_site = study_site.x) %>%
  drop_na(study_site)
contact_all$study_site <-  factor(contact_all$study_site,
  levels = c("Manhiça", "Polana Caniço")) 
  

# keep only ids that are common in both contact and participant sets.
contact_all <- contact_all %>%
  filter(rec_id %in% participant_ids)
```


```{r contact_summary}

# library(gtsummary)
contact_summary <- contact_all %>%
  filter(aim==1) %>%
  select("study_site","contact_sex","age_group_contact","fromdayone",
         "touch_contact","where_contact","contact_mask","duration_contact",
         "frequency_contact","known_contact","location_contact___0",
         "location_contact___1","location_contact___2","location_contact___3",
         "location_contact___4","location_contact___5","location_contact___6",
         "location_contact___7","location_contact___8","location_contact___9",
         "location_contact___10","location_contact___11") %>%
  # fct_explicit_na(na_level = "Missing") %>%
  tbl_summary(by=study_site,
              percent="column",
              digits = all_categorical() ~ 1) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Baseline contact information for aim 1 **")

contact_summary
```


```{r aim1_data}
# Extract aim 1 data only

# 1. add index participants from aim 2 to aim 1 data for analysis
# participant variables
participant_vars <- c("rec_id", "aim", "study_site", "date_enrolled", "sex", 
                      "age", "age_cat", "read_write", "occupation", "enrolled_school", 
                      "highest_educ", "school_level", "transport_use", 
                      "hh_resp_exposure", "child_breastfeed", "num_sibling")

participants_aim1 <- ind %>% 
  filter(aim == 1) %>%
  select(any_of(participant_vars))
  
participants_aim2_index <- ind %>% 
  filter(aim==2, age_cat %in% c("<6mo","6-11mo", "1-4y")) %>%
  select(any_of(participant_vars))

participants_aim1 <- rbind(participants_aim1, participants_aim2_index) %>%
  rename(participant_sex = sex,
         participant_age = age_cat,
         highest_education = highest_educ,
         number_subling = num_sibling) %>%
  mutate(aim = case_when(aim == 2 ~ 1,
                         TRUE ~ 1))

participants_aim2 <- ind %>% 
  filter(aim==2)


# add index contacts from aim 2 to aim 1 data for analysis
contacts_aim1 <- contact_all %>% 
  filter(aim==0) %>%
  rename(contact_age = age_group_contact)

contacts_aim2_index <- contact_all %>% 
  filter(aim==1, age_group_contact %in% c("<6mo","6-11mo", "1-4y")) %>%
  rename(contact_age = age_group_contact)

contacts_aim1 <- rbind(contacts_aim1, contacts_aim2_index)

# save participant and contact data
saveRDS(participants_aim1, "../data/clean/participant_data_aim1.RDS")
saveRDS(contacts_aim1, "../data/clean/contact_data_aim1.RDS")


# extract all aim 2 participants and contacts
participants_aim2 <- ind %>% 
  filter(aim==2)

contacts_aim2 <- contact_all %>% 
  filter(aim==1) %>%
  rename(contact_age = age_group_contact)

saveRDS(participants_aim2, "../data/clean/participant_data_aim2.RDS")
saveRDS(contacts_aim2, "../data/clean/contact_data_aim2.RDS")
```



```{r}
participant_summary_aim1 <- participants_aim1 %>%
  select("aim", "study_site", "participant_sex", "participant_age", "read_write", 
         "enrolled_school", "highest_education", "school_level", "occupation") %>%
  # filter(aim==1) %>%
  tbl_summary(by = study_site,
              percent="column",
              digits = all_categorical() ~ 0) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Aim 1 Particiant Individual Information in Mozambique**")

participant_summary_aim1
# this includes aim 2 index participants
```


```{r}
contact_summary_aim1 <- contacts_aim1 %>%
  # select("aim", "study_site", "participant_sex", "participant_age", "read_write", 
  #        "enrolled_school", "highest_education", "school_level", "occupation") %>%
  # filter(aim==0) %>%
  tbl_summary(by = study_site,
              percent="column",
              digits = all_categorical() ~ 0) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Summary of Aim 1 contacts in Mozambique**")

contact_summary_aim1
# this includes aim 2 index participants
```


```{r hh_survey}
# create the date for household information survey 
hh_survey <- data %>% 
  dplyr::filter(redcap_event_name == "household_survey_arm_1",
                is.na(redcap_repeat_instrument)) %>%
  filter(rec_id %in% participant_ids) %>%
  select(names(data)[1:126]) %>%
  select(-c("redcap_event_name", "informaes_de_agregado_familiar_e_casa_complete", 
            "redcap_repeat_instrument", "redcap_repeat_instance", "individual_id",
            "interview_date", "enumerator_id100", "isindex", "site_do_estudo_complete",
            "date_hohconsent", "hh"))

hh_survey <- hh_survey %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço"),
                aim = case_when(aim == 0 ~ 1,
                                aim == 1 ~ 2),
                hh_head_gender = case_when(hh_head_gender == 0 ~ 'Female',
                                           hh_head_gender == 1 ~ 'Male',
                                           TRUE ~ "Other"),
                                          # hh_head_gender == 2 ~ 'Transsexual Female'),
                hh_roof_material = case_when(hh_roof_material == 0 ~ "Natural", 
                                             #'Natural cover (Ex. Straw, palm leaf or grass)',
                                             hh_roof_material == 1 ~ "Rudimentary",
                                             #'Rudimentary covering (eg rustic rug, rustic wooden boards or cardboard)',
                                             hh_roof_material == 2 ~ "Modern", 
                                             #'Modern roofing (eg zinc sheet, concrete, ceramic, tiles)',
                                             hh_roof_material == 3 ~ 'Other'),
                
                hh_wall_material = case_when(hh_wall_material == 0 ~ "Natural",
                                             # 'Natural walls (Ex. No wall, reeds, palm leaves, stakes)',
                                             hh_wall_material == 1 ~ "Rudimentary",
                                             #'Rudimentary walls (eg Bamboo, pressed wood, adobe, adobe-matted stone, recycled wood, adobe-matted pegs, unburned bricks, tin, cardboard)',
                                             hh_wall_material == 2 ~ "Modern",
                                             #'Modern walls (eg Cement, limestone/cement, bricks, cement blocks, cement-covered adobe, wooden planks/laths, burnt bricks, zinc sheet walls)',
                                             hh_wall_material == 3 ~ 'Other'),
                hh_ac = case_when(hh_ac == 0 ~ 'No',
                                  hh_ac == 1 ~ 'Yes',
                                  hh_ac == 2 ~ "Unknown"),
                
                hh_fan = case_when(hh_fan == 0 ~ 'No',
                                  hh_fan == 1 ~ 'Yes',
                                  hh_fan == 2 ~ "Unknown")) 

label(hh_survey$hh_amenities___0) <- "Electricity"
label(hh_survey$hh_amenities___1) <- "Refrigerator/Freezer"
label(hh_survey$hh_amenities___2) <- "Radio"
label(hh_survey$hh_amenities___3) <- "Television"
label(hh_survey$hh_amenities___4) <- "None of the above"

label(hh_survey$hh_transport___0) <- "Bicycle"
label(hh_survey$hh_transport___1) <- "Motorcycle"
label(hh_survey$hh_transport___2) <- "Car"
label(hh_survey$hh_transport___3) <- "Tractor"
label(hh_survey$hh_transport___4) <- "None"

label(hh_survey$animal_touch___0) <- "Contact with chicken, ducks, geese"
label(hh_survey$animal_touch___1) <- "Contact with cows, rabbit, pigs, goats, sheep"
label(hh_survey$animal_touch___2) <- "Contact with cats and dogs"
label(hh_survey$animal_touch___3) <- "Contact with rodents"
label(hh_survey$animal_touch___4) <- "Contact with primates"
label(hh_survey$animal_touch___5) <- "Contact with bats"
label(hh_survey$animal_touch___6) <- "Contact with antelope"
label(hh_survey$animal_touch___7) <- "Contact with other animals"
label(hh_survey$animal_touch___8) <- "No contact with animals"

label(hh_survey$animal_injury___0) <- "Injury from chicken, ducks, geese"
label(hh_survey$animal_injury___1) <- "Injury from cows, rabbit, pigs, goats, sheep"
label(hh_survey$animal_injury___2) <- "Injury from cats and dogs"
label(hh_survey$animal_injury___3) <- "Injury from rodents"
label(hh_survey$animal_injury___4) <- "Injury from primates"
label(hh_survey$animal_injury___5) <- "Injury from bats"
label(hh_survey$animal_injury___6) <- "Injury from antelope"
label(hh_survey$animal_injury___7) <- "Injury from other animals"
label(hh_survey$animal_injury___8) <- "No injury from animals"

label(hh_survey$animal_cook___0) <- "Cooked chicken, ducks, geese"
label(hh_survey$animal_cook___1) <- "Cooked cows, rabbit, pigs, goats, sheep"
label(hh_survey$animal_cook___2) <- "Cooked cats and dogs"
label(hh_survey$animal_cook___3) <- "Cooked rodents"
label(hh_survey$animal_cook___4) <- "Cooked primates"
label(hh_survey$animal_cook___5) <- "Cooked bats"
label(hh_survey$animal_cook___6) <- "Cooked antelope"
label(hh_survey$animal_cook___7) <- "Cooked other animals"
label(hh_survey$animal_cook___8) <- "Did not cook animals"

label(hh_survey$water_source___0) <- "Piped water (indoors, outside, in the yard, at neighbor's house)"
label(hh_survey$water_source___1) <- "Public fountain water"
label(hh_survey$water_source___2) <- "Protected dug well/hole water (with or without hand pump)"
label(hh_survey$water_source___3) <- "Unprotected dug well"
label(hh_survey$water_source___4) <- "Water from protected spring"
label(hh_survey$water_source___5) <- "Water from unprotected spring"
label(hh_survey$water_source___6) <- "Rainwater"
label(hh_survey$water_source___7) <- "Lorry tank water/Water Tanker"
label(hh_survey$water_source___8) <- "Water loaded in drums/barrels"
label(hh_survey$water_source___9) <- "Surface water (River/Lake/Water Pan)"
label(hh_survey$water_source___10) <- "Bottled or Packed Water/Mineral Water"
label(hh_survey$water_source___11) <- "Other"

label(hh_survey$water_drink___0) <- "Piped water (indoors, outside, in the yard, at neighbor's house)"
label(hh_survey$water_drink___1) <- "Public fountain water"
label(hh_survey$water_drink___2) <- "Protected dug well/hole water (with or without hand pump)"
label(hh_survey$water_drink___3) <- "Unprotected dug well"
label(hh_survey$water_drink___4) <- "Water from protected spring"
label(hh_survey$water_drink___5) <- "Water from unprotected spring"
label(hh_survey$water_drink___6) <- "Rainwater"
label(hh_survey$water_drink___7) <- "Lorry tank water/Water Tanker"
label(hh_survey$water_drink___8) <- "Water loaded in drums/barrels"
label(hh_survey$water_drink___9) <- "Surface water (River/Lake/Water Pan)"
label(hh_survey$water_drink___10) <- "Bottled or Packed Water/Mineral Water"
label(hh_survey$water_drink___11) <- "Other"

label(hh_survey$water_purify_method___1) <- "Boil"
label(hh_survey$water_purify_method___2) <- "Add bleach/chlorine"
label(hh_survey$water_purify_method___3) <- "Strain through cloth"
label(hh_survey$water_purify_method___4) <- "Use water filter"
label(hh_survey$water_purify_method___5) <- "Solar disinfection"
label(hh_survey$water_purify_method___6) <- "Let it stand and settle"
label(hh_survey$water_purify_method___7) <- "Other"
label(hh_survey$water_purify_method___8) <- "Unnown"

hh_survey <- hh_survey %>% 
  # Do you wash your hands after helping a child defecate?
  dplyr::mutate(wash_hands_defecatelb = case_when(wash_hands_defecate == 0 ~ "Never",
                                         wash_hands_defecate == 1 ~ "Rarely",
                                         wash_hands_defecate == 2 ~ "Sometimes",
                                         wash_hands_defecate == 3 ~ "Always",
                                         wash_hands_defecate == 4 ~ "Not applicable), 
                                         # (does not help a child defecate)"),
                
  # Do members of your household wash their hands before touching food (Ex. cooking, preparing, before eating)?
                wash_hands_foodlb = case_when(wash_hands_food == 0 ~ "Never",
                                         wash_hands_food == 1 ~ "Rarely",
                                         wash_hands_food == 2 ~ "Sometimes",
                                         wash_hands_food == 3 ~ "Always"),
                
                # Do members of your household wash their hands after using the toilet?
                wash_hands_toiletlb = case_when(wash_hands_toilet == 0 ~ "Never",
                                         wash_hands_toilet == 1 ~ "Rarely",
                                         wash_hands_toilet == 2 ~ "Sometimes",
                                         wash_hands_toilet == 3 ~ "Always"))

label(hh_survey$wash_hands_defecatelb) <- "Do you wash your hands after helping a child defecate?"
label(hh_survey$wash_hands_foodlb) <- "Do members of your household wash their hands before touching food?" 
# (Ex. cooking, preparing, before eating)?"
label(hh_survey$wash_hands_toiletlb) <- "Do members of your household wash their hands after using the toilet?"

hh_survey = hh_survey %>% 
  # Does anyone in your household (including yourself) smoke tobacco products?
  dplyr::mutate(hh_smokinglb = case_when(hh_smoking == 0 ~ "No",
                                         hh_smoking == 1 ~ "Yes",
                                         hh_smoking == 2 ~ "Unknown"),
                
                #Do you cook food inside or outside the house?
                hh_cooklb = case_when(hh_cook == 0 ~ "Inside",
                                         hh_cook == 1 ~ "Outside",
                                         hh_cook == 2 ~ "Both"))

label(hh_survey$hh_smokinglb) <- "Does anyone in your household smoke tobacco products?"
label(hh_survey$hh_cooklb) <- "Do you cook food inside/ outside the house?"

# What do you use to cook food? 
label(hh_survey$hh_fuel___0) <- "Biomass" # (Wood, Coal, Manure)"
label(hh_survey$hh_fuel___1) <- "Gas"
label(hh_survey$hh_fuel___2) <- "Electricity"
label(hh_survey$hh_fuel___3) <- "Other"

hh_survey <- hh_survey %>% 
  #Does anyone in your household have asthma?
  dplyr::mutate(hh_asthmalb = case_when(hh_asthma == 0 ~ "No",
                                         hh_asthma == 1 ~ "Yes",
                                         hh_asthma == 2 ~ "Unknown"),
                
                #Has anyone in your household been diagnosed with Tuberculosis (TB) in the past year?
                hh_tblb = case_when(hh_tb == 0 ~ "No",
                                         hh_tb == 1 ~ "Yes",
                                         hh_tb == 2 ~ "Unnown"))

label(hh_survey$hh_asthmalb) -> "Does anyone in your household have asthma?"
label(hh_survey$hh_tblb) -> "Has anyone in your household been diagnosed with Tuberculosis (TB) in the past year?"

# keep aim 1 data only
hh_survey_aim1 <- hh_survey %>%
  filter(rec_id %in% participants_aim1$rec_id) %>%
  select(-c(hh_id, hoh_id))

saveRDS(hh_survey_aim1, "../data/clean/household_survey_aim1.RDS")

# keep aim 2 data only
hh_survey_aim2 <- hh_survey %>%
  filter(rec_id %in% participants_aim2$rec_id) %>%
  select(-c(hh_id, hoh_id))

saveRDS(hh_survey_aim2, "../data/clean/household_survey_aim2.RDS")

# rm(hh_survey, hh_survey_aim1, hh_survey_aim2)
```


```{r}
# create the data for participants' location visit information in 2 days 
loc_visit_d1 <- data %>%
  # filter(rec_id %in% participant_ids) %>%
  dplyr::filter(redcap_repeat_instrument == "dirio_de_locais_visitados_dia_1") %>%
  select("rec_id", "place_visited_d1", "place_visited_d1_other",
         "num_pax_place_d1", "time_visited_d1", "visited_frequency_d1")
# "redcap_event_name","redcap_repeat_instrument", "redcap_repeat_instance",
# "dirio_de_locais_visitados_dia_1_complete")

loc_visit_d1 <- loc_visit_d1 %>%
  mutate(place_visited_d1 = case_when(place_visited_d1 == 0 ~ "My home",
  place_visited_d1 == 1~ "Other home",
  place_visited_d1 == 2~ "School",
  place_visited_d1 == 3~ "Work",
  place_visited_d1 == 4~ "Transport/Hub",
  place_visited_d1 == 5~ "Market/Shop",
  place_visited_d1 == 6~ "Street",
  place_visited_d1 == 7~ "Well",
  place_visited_d1 == 8~ "Agricultural Field",
  place_visited_d1 == 9~ "Playground",
  place_visited_d1 == 10~ "Place of worship",
  place_visited_d1 == 11~ "Other"))

loc_visit_d1 = loc_visit_d1 %>%
  dplyr::mutate(time_visited_d1 = case_when(time_visited_d1 == 0 ~ "<5 mins",
                                               time_visited_d1 == 1 ~ "5-15 mins",
                                               time_visited_d1 == 2 ~ "16-30 mins",
                                               time_visited_d1 == 3 ~ "31 mins-1 hr",
                                               time_visited_d1 == 4 ~ "1-4 hrs",
                                               time_visited_d1 == 5 ~ ">4 hrs"))
label(loc_visit_d1$time_visited_d1) <- "How much time did you spend in this place?"

loc_visit_d1 = loc_visit_d1 %>%
  dplyr::mutate(visited_frequency_d1 = case_when(visited_frequency_d1 == 0 ~ "Never met before",
                                               visited_frequency_d1 == 1 ~ "Rarely",
                                               visited_frequency_d1 == 2 ~ "Daily or almost daily",
                                               visited_frequency_d1 == 3 ~ "1-3 times per week",
                                               visited_frequency_d1 == 4 ~ "Once every 2 weeks",
                                               visited_frequency_d1 == 5 ~ "Once per month",
                                               visited_frequency_d1 == 6 ~ "Once every 3 months"))
label(loc_visit_d1$visited_frequency_d1) <- "Besides this visit, how many times have you visited this place in the last 6 months?"

# loc_visit_d1 = loc_visit_d1 %>%
#   dplyr::mutate(dirio_de_locais_visitados_dia_1_complete = case_when(dirio_de_locais_visitados_dia_1_complete == 0 ~ "Incomplete",
#                                                dirio_de_locais_visitados_dia_1_complete == 1 ~ "Unverified",
#                                                dirio_de_locais_visitados_dia_1_complete == 2 ~ "Complete"))
# label(loc_visit_d1$dirio_de_locais_visitados_dia_1_complete) <- "Complete the location visit day 1 survey?"

loc_visit_d1$Day1or2 <- 1
```


```{r}
loc_visit_d2 <- data %>%
  # filter(rec_id %in% participant_ids) %>%
  dplyr::filter(redcap_repeat_instrument == "dirio_de_locais_visitados_dia_2") %>%
  select("rec_id","place_visited_d2","place_visited_d2_other",
         "num_pax_place_d2","time_visited_d2","visited_frequency_d2")
# "redcap_event_name","redcap_repeat_instrument", "redcap_repeat_instance",
# "dirio_de_locais_visitados_dia_2_complete")

loc_visit_d2 <- loc_visit_d2 %>%
  mutate(place_visited_d2 = case_when(place_visited_d2 == 0 ~ "My home",
  place_visited_d2 == 1~ "Other home",
  place_visited_d2 == 2~ "School",
  place_visited_d2 == 3~ "Work",
  place_visited_d2 == 4~ "Transport/Hub",
  place_visited_d2 == 5~ "Market/Shop",
  place_visited_d2 == 6~ "Street",
  place_visited_d2 == 7~ "Well",
  place_visited_d2 == 8~ "Agricultural Field",
  place_visited_d2 == 9~ "Playground",
  place_visited_d2 == 10~ "Place of worship",
  place_visited_d2 == 11~ "Other"))

loc_visit_d2 <- loc_visit_d2 %>%
  dplyr::mutate(time_visited_d2 = case_when(time_visited_d2 == 0 ~ "<5 mins",
                                               time_visited_d2 == 1 ~ "5-15 mins",
                                               time_visited_d2 == 2 ~ "16-30 mins",
                                               time_visited_d2 == 3 ~ "31 mins-1 hr",
                                               time_visited_d2 == 4 ~ "1-4 hrs",
                                               time_visited_d2 == 5 ~ ">4 hrs"))
label(loc_visit_d2$time_visited_d2) <- "How long did you spend in this place?"

loc_visit_d2 <- loc_visit_d2 %>%
  dplyr::mutate(visited_frequency_d2 = case_when(visited_frequency_d2 == 0 ~ "Never met before",
                                               visited_frequency_d2 == 1 ~ "Rarely",
                                               visited_frequency_d2 == 2 ~ "Daily or almost daily",
                                               visited_frequency_d2 == 3 ~ "1-3 times per week",
                                               visited_frequency_d2 == 4 ~ "Once every 2 weeks",
                                               visited_frequency_d2 == 5 ~ "Once per month",
                                               visited_frequency_d2 == 6 ~ "Once every 3 months"))
label(loc_visit_d2$visited_frequency_d2) <- "Besides this visit, how many times have you visited this place in the last 6 months?"

# loc_visit_d2 <- loc_visit_d2 %>%
#   dplyr::mutate(dirio_de_locais_visitados_dia_2_complete = case_when(dirio_de_locais_visitados_dia_2_complete == 0 ~ "Incomplete",
#                                                dirio_de_locais_visitados_dia_2_complete == 1 ~ "Unverified",
#                                                dirio_de_locais_visitados_dia_2_complete == 2 ~ "Complete"))
# label(loc_visit_d2$dirio_de_locais_visitados_dia_2_complete) <- "Complete the location visit day 2 survey?"

loc_visit_d2$Day1or2 <- 2
```


```{r}
# combine data for location visit day 1 and day 2 together
names(loc_visit_d1)[grep("_d1", names(loc_visit_d1))] <-  gsub("_d1", "", 
                                                               names(loc_visit_d1)[grep("_d1", names(loc_visit_d1))])
# names(loc_visit_d1)[11] <- "survey_complete"

names(loc_visit_d2)[grep("_d2", names(loc_visit_d2))] <-  gsub("_d2", "", 
                                                               names(loc_visit_d2)[grep("_d2", names(loc_visit_d2))])
# names(loc_visit_d2)[11] <- "survey_complete"

loc_visit <- rbind(loc_visit_d1, loc_visit_d2)

# keep only those in participants_id list
loc_visit <- loc_visit %>%
  left_join(ind, by='rec_id') %>%
  filter(rec_id %in% participant_ids)

# keep aim 1 data only
loc_visit_aim1 <- loc_visit %>%
  filter(rec_id %in% participants_aim1$rec_id)
saveRDS(loc_visit_aim1, "../data/clean/locations_visited_aim1.RDS")

# keep aim 2 data only
loc_visit_aim2 <- loc_visit %>%
  filter(rec_id %in% participants_aim2$rec_id)
saveRDS(loc_visit_aim2, "../data/clean/locations_visited_aim2.RDS")

rm(loc_visit_d1, loc_visit_d2)
```


```{r exit-interview, echo=FALSE}

# keep aim 1 data only
exit_interview_aim1 <- exit %>%
  filter(rec_id %in% participants_aim1$rec_id)
saveRDS(exit_interview_aim1, "../data/clean/exit_interview_aim1.RDS")

# keep aim 2 data only
exit_interview_aim2 <- exit %>%
  filter(rec_id %in% participants_aim2$rec_id)
saveRDS(exit_interview_aim2, "../data/clean/exit_interview_aim2.RDS")

rm(exit_interview_aim1, exit_interview_aim2)

```
