---
title: "Global Mix Mozambique cleaning"
author: corssinojaime@gmail.com
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
        
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = F}
rm(list=ls())
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```


```{r imports, echo=FALSE, message = FALSE}
# Load packages
source("../scripts/00_load_libraries.R")

# define theme
theme_asart = ggthemes::theme_hc
options(knitr.table.format = "html") 

data = rio::import("../raw/data_2021-06-15.csv")

```

## Household survey for aim 1
```{r, echo=FALSE, message = FALSE}

hh = data %>% 
  dplyr::filter(redcap_event_name == "household_survey_arm_1") %>% dplyr::select("rec_id","redcap_repeat_instrument","redcap_repeat_instance","redcap_survey_identifier","site_do_estudo_timestamp", "individual_id","interview_date","enumerator_id100","study_site","aim","hh","site_do_estudo_complete", "informaes_de_agregado_familiar_e_casa_timestamp","hh_id","hoh_id","date_hohconsent","hh_head_gender","hh_head_gender_other", "hh_occupants","hh_slept","hh_room_num","hh_bedroom_num","hh_roof_material","hh_roof_material_other","hh_wall_material", "hh_wall_material_other","hh_ac","hh_fan","hh_amenities___0","hh_amenities___1","hh_amenities___2","hh_amenities___3", "hh_amenities___4","hh_transport___0","hh_transport___1","hh_transport___2","hh_transport___3","hh_transport___4","hh_grazing", "hh_poultry","hh_pig","hh_improvements","animal_touch___0","animal_touch___1","animal_touch___2","animal_touch___3", "animal_touch___4","animal_touch___5","animal_touch___6","animal_touch___7","animal_touch___8","animal_touch_other", "animal_injury___0","animal_injury___1","animal_injury___2","animal_injury___3","animal_injury___4","animal_injury___5", "animal_injury___6","animal_injury___7","animal_injury___8","animal_injury_other","animal_cook___0","animal_cook___1", "animal_cook___2","animal_cook___3","animal_cook___4","animal_cook___5","animal_cook___6","animal_cook___7","animal_cook___8", "animal_cook_other","water_source___0","water_source___1","water_source___2","water_source___3","water_source___4", "water_source___5","water_source___6","water_source___7","water_source___8","water_source___9","water_source___10", "water_source___11","water_source_other","water_drink___0","water_drink___1","water_drink___2","water_drink___3", "water_drink___4","water_drink___5","water_drink___6","water_drink___7","water_drink___8","water_drink___9","water_drink___10", "water_drink___11","water_drink_other","water_purify","water_purify_method___1","water_purify_method___2","water_purify_method___3", "water_purify_method___4","water_purify_method___5","water_purify_method___6","water_purify_method___7","water_purify_method___8", "water_purify_method_other","wash_hands_defecate","wash_hands_food","wash_hands_toilet","hh_toilet","hh_toilet_other", "hh_toilet_location","hh_toilet_location_other","child_stool_disposal","child_stool_disposal_other","hh_smoking","hh_cook", "hh_fuel___0","hh_fuel___1","hh_fuel___2","hh_fuel___3","hh_fuel_other","hh_asthma","hh_tb", "informaes_de_agregado_familiar_e_casa_complete", "informaes_sobre_os_membros_da_famlia_timestamp") %>% dplyr::filter(redcap_repeat_instrument == "")

# site
hh = hh %>% 
  dplyr::mutate(study_sitelb = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 
# hh head sex
hh <- hh %>% 
  dplyr::mutate(genderlb = case_when(hh_head_gender == 0 ~ "Female",
                                                   hh_head_gender == 1 ~ "Male"))


```

## check the distribution of number of occupants, people slept in the house overnight, number of rooms, and number of bedrooms.
```{r, echo=FALSE, message = FALSE}
# hh
temp1 <- c("hh_occupants","hh_slept","hh_room_num","hh_bedroom_num")
boxplot(hh[,vars1])

# for each house, hh_bedroom_num < hh_room_num
```
```{r, echo=FALSE, message=FALSE}
# there is a household in which >40 people slept in. check amd correct.
hh %>%
  select(study_site, enumerator_id100, hh_id, hh_slept, hh_room_num, hh_bedroom_num) %>%
  filter(hh_slept > 20)
# Polana Canico,
```


## Amenities
```{r, echo=FALSE}
temp2 <- c("hh_amenities___0","hh_amenities___1","hh_amenities___2","hh_amenities___3", "hh_amenities___4")

```

```{r, echo=FALSE}
temp3 <- c("hh_transport___1","hh_transport___2","hh_transport___3","hh_transport___4")
```
## Animal ownership
```{r, echo=FALSE}
temp4 <- c("hh_grazing", "hh_poultry","hh_pig")
```
## Animal touch, injury, cook
```{r, echo=FALSE}
temp5 <- c("animal_touch___0","animal_touch___1","animal_touch___2","animal_touch___3",
           "animal_touch___4","animal_touch___5","animal_touch___6","animal_touch___7",
           "animal_touch___8","animal_touch_other")

temp6 <- c("animal_injury___0","animal_injury___1","animal_injury___2","animal_injury___3",
           "animal_injury___4","animal_injury___5","animal_injury___6","animal_injury___7",
           "animal_injury___8","animal_injury_other")

temp7 <- c("animal_cook___0","animal_cook___1","animal_cook___2","animal_cook___3",
           "animal_cook___4","animal_cook___5","animal_cook___6","animal_cook___7",
           "animal_cook___8", "animal_cook_other")

```

## Water
```{r, echo=FALSE}
temp8 <- c("water_source___0","water_source___1","water_source___2","water_source___3",
           "water_source___4", "water_source___5","water_source___6","water_source___7",
           "water_source___8","water_source___9","water_source___10", "water_source___11",
           "water_source_other")

temp9 <- c("water_drink___0","water_drink___1","water_drink___2","water_drink___3",
           "water_drink___4","water_drink___5","water_drink___6","water_drink___7",
           "water_drink___8","water_drink___9","water_drink___10", "water_drink___11",
           "water_drink_other")

temp10 <- c("water_purify","water_purify_method___1","water_purify_method___2","water_purify_method___3",
           "water_purify_method___4","water_purify_method___5","water_purify_method___6","water_purify_method___7",
           "water_purify_method___8", "water_purify_method_other")
```

```{r, echo=FALSE}
temp11 <- c("wash_hands_defecate","wash_hands_food","wash_hands_toilet")
```

```{r, echo=FALSE}
temp12 <- c("hh_toilet","hh_toilet_other","hh_toilet_location","hh_toilet_location_other",
            "child_stool_disposal","child_stool_disposal_other")
```

```{r, echo=FALSE}
temp13 <- c("hh_smoking","hh_cook", "hh_fuel___0","hh_fuel___1",
            "hh_fuel___2","hh_fuel___3","hh_fuel_other",)
```

```{r, echo=FALSE}
temp14 <- c("hh_asthma","hh_tb")
```

## Individual enrollment
```{r, echo=FALSE}
## Individual enrollment records
ind_rep = data %>% 
  dplyr::filter(redcap_repeat_instrument == "informaes_sobre_os_membros_da_famlia") %>% 
  dplyr::select("rec_id", "redcap_repeat_instrument", "redcap_repeat_instance","hh_member_hoh","hh_member_name", 
                "hh_member_id","hh_member_sensor","hh_member_sex","hh_member_sex_outro","hh_member_age",
                "hh_member_relationship","hh_member_relationship_other","share_room","share_bed","cook_food",
                "hh_member_hhform","hh_member_instance","informaes_sobre_os_membros_da_famlia_complete","inscrio_timestamp")

ind = data %>% 
  dplyr::filter(redcap_event_name == "individual_enrollm_arm_1") %>% 
  dplyr::select("rec_id", "redcap_event_name", "date_enrolled", "name", "sensor_id", "sex", "sex_other","birthdate", "age", "read_write", "address", "telephone", "telephone_1", "occupation___0", "occupation___1", "occupation___2", "occupation___3", "occupation___4", "occupation___5", "occupation___6", "occupation___7", "occupation___8", "occupation___9", "occupation_other", "enrolled_school", "highest_educ", "school_level", "transport_use", "hh_resp_exposure", "child", "child_breastfeed", "child_breastfeed2", "child_breastfeed3___1", "child_breastfeed3___2", "child_breastfeed3___3", "child_breastfeed3___4", "child_breastfeed3___5", "child_breastfeed3___6", "child_breastfeed3___7", "child_breastfeed3___8", "child_breastfeed3___9", "child_breastfeed3___10", "child_breastfeed3___11", "child_breastfeed3_other", "num_simbling", "inscrio_complete")


ind  = ind %>% 
  dplyr::mutate(highest_educlb = case_when(highest_educ == 0 ~ "No schooling", 
                                           highest_educ == 1 ~ "Primary School (1-7)", 
                                           highest_educ == 2 ~ "Basic Secondary school (8-10)",
                                           highest_educ == 3 ~ "Middle Secondary (11-12)", 
                                           highest_educ == 4 ~ "1-3 years of college/university", 
                                           highest_educ == 5 ~ "Bacherols",
                                           highest_educ == 6 ~ "More than Bachelors")) ## check spelling, initially "Bacherols"

#indnull = ind[is.na(ind$birthdate),]
#indnull$birthdate = x$date_enrolled %m-%years(x$age)
#ind = ind[!is.na(ind$birthdate),]
#ind = rbind(indnull, ind)

#ind$age_weeks = round(difftime(strptime(as.Date(ind$date_enrolled), format = "%Y-%m-%d"),strptime(ind$birthdate, format = "%Y-%m-%d"),units="weeks"),2)
#ind$months = interval(ind$birthdate,ind$date_enrolled) %/% months(1) 

#df_mths = subset(ind, ind$months < 12)
#df_years = subset(ind, ind$months >= 12)
#df_mths = df_mths %>% dplyr::mutate(group = case_when(months < 6 ~ 1, months >= 6  ~ 2))
#df_years = df_years %>% dplyr::mutate(group = case_when( age < 5 ~ 3, age >= 5 & age < 10 ~ 4, age >= 10 & age < 15 ~ 5, age >= 15 & age < 20 ~ 6, age >= 20 & age < 30 ~ 7, age >= 30 & age < 40 ~ 8,
#                                                         age >= 40 & age < 60 ~ 9, age >= 60 ~ 10))
#ind = rbind(df_mths, df_years)

#ind = ind %>% dplyr::mutate(agelb = case_when(group == 1 ~ "< 6months", group == 2 ~ "6 - 11months", group == 3 ~ "1 - 4y", group == 4 ~ "5 - 9y", group == 5 ~ "10 - 14y", group == 6 ~ "15 - 19y", 
#                                              group == 7 ~ "20 - 29y", group == 8 ~ "30 - 39y", group == 9 ~ "40 - 59y", group == 10 ~ "60y+"))

ind = ind %>% 
  dplyr::mutate(agelb = case_when(age < 1 ~ "<1", 
                                  age >=1 & age <= 4 ~ "1 - 4y", 
                                  age >=5 & age <=9 ~ "5 - 9y", 
                                  age >=10 & age <=14 ~ "10 - 14y", 
                                  age >=15 & age <=19 ~ "15 - 19y", 
                                  age >=20 & age <=29 ~ "20 - 29y", 
                                  age >=30 & age <=39 ~ "30 - 39y", 
                                  age >=40 & age <=59 ~ "40 - 59y", 
                                  age >=60 ~ "60y+"))

ind = ind %>% 
  dplyr::mutate(sexlb = case_when(sex == 0 ~ "Female", sex == 1 ~ "Male"))

ind$agelb = factor(ind$agelb, 
                   levels = c("<1", "1 - 4y", "5 - 9y", "10 - 14y", "15 - 19y", "20 - 29y", "30 - 39y", "40 - 59y", "60y+"))


#ind$agelb = factor(ind$agelb, levels = c("< 6months","6 - 11months", "1 - 4y", "5 - 9y", "10 - 14y", "15 - 19y", "20 - 29y", "30 - 39y", "40 - 59y", "60y+"))
```
