---
title: "Mozambique: cleaning individual participant data"
author: mkiti@emory.edu
output: html_document
# date:
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = F}
rm(list=ls())
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```


```{r imports, echo=FALSE, message = FALSE}
# Load packages
source("../scripts/00_load_libraries.R")

# load data
data = rio::import("../raw/all_data_09242021.csv")

# filter
ind <- data %>% 
  dplyr::filter(redcap_event_name == "individual_enrollm_arm_1") %>% 
  dplyr::select("rec_id", "individual_id","redcap_event_name", "date_enrolled", "sex", "sex_other", "birthdate","age", "read_write", "occupation___0", "occupation___1", "occupation___2", "occupation___3", "occupation___4", "occupation___5", "occupation___6", "occupation___7", "occupation___8", "occupation___9", "occupation_other", "enrolled_school", "highest_educ", "school_level", "transport_use", "hh_resp_exposure", "child_breastfeed", "num_simbling", "inscrio_complete", "sensor_id","child", "redcap_repeat_instrument") %>%
    dplyr::filter(redcap_repeat_instrument == "")

```

## Individual enrolment
```{r individual_enrolment, echo=FALSE}
## Individual enrollment records
ind  = ind %>% 
  dplyr::mutate(highest_educlb = case_when(highest_educ == 0 ~ "No schooling", 
                                           highest_educ == 1 ~ "Primary School (1-7)", 
                                           highest_educ == 2 ~ "Basic Secondary school (8-10)",
                                           highest_educ == 3 ~ "Middle Secondary (11-12)", 
                                           highest_educ == 4 ~ "1-3 years of college/university", 
                                           highest_educ == 5 ~ "Bacherols",
                                           highest_educ == 6 ~ "More than Bachelors")) ## check spelling, initially "Bacherols"
label(ind$highest_educlb) <- "What is the highest level of education that you have attained?"

ind = ind %>% 
  dplyr::mutate(agelb = case_when(age < 1 ~ "<1", 
                                  age >=1 & age <= 4 ~ "1 - 4y", 
                                  age >=5 & age <=9 ~ "5 - 9y", 
                                  age >=10 & age <=14 ~ "10 - 14y", 
                                  age >=15 & age <=19 ~ "15 - 19y", 
                                  age >=20 & age <=29 ~ "20 - 29y", 
                                  age >=30 & age <=39 ~ "30 - 39y", 
                                  age >=40 & age <=59 ~ "40 - 59y", 
                                  age >=60 ~ "60y+"))

ind = ind %>% 
  dplyr::mutate(sexlb = case_when(sex == 0 ~ "Female", sex == 1 ~ "Male"))

ind$agelb = factor(ind$agelb, 
                   levels = c("<1", "1 - 4y", "5 - 9y", "10 - 14y", "15 - 19y", "20 - 29y", "30 - 39y", "40 - 59y", "60y+"))


ind  = ind %>% 
  dplyr::mutate(read_writelb = case_when(read_write == 0 ~ "No", 
                                         read_write == 1 ~ "Yes"))
label(ind$read_writelb) <- "Can the participant read and write on their own?"


label(ind$occupation___0) <- "Unemployed"
label(ind$occupation___1) <- "Student"
label(ind$occupation___2) <- "Office worker"
label(ind$occupation___3) <- "Business person"
label(ind$occupation___4) <- "Casual labor"
label(ind$occupation___5) <- "Farmer"
label(ind$occupation___6) <- "Fishing"
label(ind$occupation___7) <- "Retired"
label(ind$occupation___8) <- "Homemaker/ Housewife"
label(ind$occupation___9) <- "Other"

ind  = ind %>% 
  dplyr::mutate(enrolled_schoollb = case_when(enrolled_school == 0 ~ "No", 
                                         enrolled_school == 1 ~ "Yes"))
label(ind$enrolled_schoollb) <- "Are you currently enrolled in school?"

ind  = ind %>% 
  dplyr::mutate(school_levellb = case_when(school_level == 0 ~ "No schooling", 
                                           school_level == 1 ~ "Primary School (1-7)", 
                                           school_level == 2 ~ "Basic Secondary school (8-10)",
                                           school_level == 3 ~ "Middle Secondary (11-12)", 
                                           school_level == 4 ~ "1-3 years of college/university", 
                                           school_level == 5 ~ "Bacherols",
                                           school_level == 6 ~ "More than Bachelors"))
label(ind$school_levellb) <- "What school level are you in?"

ind  = ind %>% 
  dplyr::mutate(transport_uselb = case_when(transport_use == 0 ~ "Never", 
                                            transport_use == 1 ~ "Rarely", 
                                            transport_use == 2 ~ "Daily or almost daily",
                                            transport_use == 3 ~ "1-3 times per week", 
                                            transport_use == 4 ~ "1 time per month"))
label(ind$transport_uselb) <- "How often did you use mass transport in the past 3 months?"

ind  = ind %>% 
  dplyr::mutate(hh_resp_exposurelb = case_when(hh_resp_exposure == 0 ~ "No", 
                                               hh_resp_exposure == 1 ~ "Yes",
                                               hh_resp_exposure == 2 ~ "I don't know"))
label(ind$hh_resp_exposurelb) <- "Were you exposed to persons with respiratory complaints within your household in the past one week?"
 
ind  = ind %>% 
  dplyr::mutate(child_breastfeedlb = case_when(child_breastfeed == 0 ~ "No", 
                                               child_breastfeed == 1 ~ "Yes",
                                               child_breastfeed == 2 ~ "Not applicable"))
label(ind$child_breastfeedlb) <- "Are you breastfeeding?"

ind  = ind %>% 
  dplyr::mutate(childlb = case_when(child == 0 ~ "No", 
                                    child == 1 ~ "Yes",
                                    child == 2 ~ "Not applicable"))
label(ind$childlb) <- "Do you have a infant ?"
```


```{r}
# individual enrollment has sensor_id, household_enrol has aim 2. merge these two, then filter.
sensor1 <- data %>% 
  dplyr::filter(redcap_event_name == "individual_enrollm_arm_1") %>%
  dplyr::select("rec_id", "sensor_id", "age", "sex")


sensor2 <- data %>% 
  dplyr::filter(redcap_event_name == "household_survey_arm_1") %>%
  dplyr::select("redcap_repeat_instrument","redcap_event_name","aim","individual_id","rec_id","study_site","hh","hh_id","hoh_id", 
                "hh_head_gender","hh_occupants") %>%
  dplyr::filter(aim == 1) %>% #only aim2
  dplyr::filter(redcap_repeat_instrument == "")

sensor <- dplyr::inner_join(sensor1, sensor2, by="rec_id")

# for now, after visually eyeballing, drop sensors with incorrect ID
drop_sensors <- c("1109", "1110","1111","1121","249","1026","1140","478","942",
                  "867","737","738","739","595","596","597","598","1004")
sensor <- sensor[!sensor$rec_id %in% drop_sensors, ]

# Some summary stats
##1. How many people with sensors? By site and age and sex?
n <- dim(sensor[1])

sensor <- sensor %>% 
  dplyr::mutate(agegp = case_when(age < 1 ~ "<1", 
                                  age >=1 & age <= 4 ~ "1-4y", 
                                  age >=5 & age <=9 ~ "5-9y", 
                                  age >=10 & age <=14 ~ "10-14y", 
                                  age >=15 & age <=19 ~ "15-19y", 
                                  age >=20 & age <=29 ~ "20-29y", 
                                  age >=30 & age <=39 ~ "30-39y", 
                                  age >=40 & age <=59 ~ "40-59y", 
                                  age >=60 ~ "60y+"))
sensor$agegp = factor(sensor$agegp, 
                   levels = c("<1", "1-4y", "5-9y", "10-14y", "15-19y", "20-29y", "30-39y", "40-59y", "60y+"))


# graph of agegp by site
p <- sensor %>% 
  ggplot(aes(x=agegp, color=study_site, fill=study_site)) +
  geom_histogram(stat = 'count') +
  facet_wrap(~study_site)
p

##2. How many households and participants by site?

##3. Average household size by site


```