---
title: "CL_contact matrix"
output: html_document
date: "2022-08-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libs, include=FALSE, warnings=FALSE}
library(dplyr)
library(tidyr)
library(socialmixr)
library(ggplot2)
library(table1)
library(gtsummary)
```

## Read in data
```{r read_data, include=FALSE, warnings=FALSE}
# files have been renamed
ind <- readRDS("../data/clean/participant_data_aim1.RDS")
ind_exit <- readRDS("../data/clean/exit_interview_aim1.RDS")
contact <- readRDS("../data/clean/contact_data_aim1.RDS")
# contact_nonhh <- readRDS("../data/clean/ind_contact_nonhh.RDS")
hh_survey <- readRDS("../data/clean/household_survey_aim1.RDS")

```

Subset to aim 1 only
```{r subset_aim1, include=FALSE, warnings=FALSE}
## Subset individual_info to those included in aim1 only and only those who compelted exit interview
ind <- ind %>% 
  filter(aim ==1) %>% ## retain 1328 from aim 1
  filter(rec_id %in% unlist(ind_exit$rec_id)) ## retain 1270, only those with exit survey ie completed survey

## Subset household contact to the IDs from aim 1 only
contact <- contact%>%
              filter(rec_id %in% unlist(ind$rec_id))

# ## Subset non HH contact to the IDs from aim 1 only
# contact_nonhh <- contact_nonhh %>%
#               filter(rec_id %in% unlist(ind$rec_id))
```

Check to see if there are any IDs with no contacts reported
```{r no_contacts, include=FALSE, warnings=FALSE}
sum(!ind$rec_id %in% contact$rec_id) # 78
# sum(!ind$rec_id %in% contact_nonhh$rec_id) # 28

## Figure out which ones
# missing_hh_nonhh <- ind %>%
#   filter(!rec_id %in% unlist(contact_hh$rec_id)) %>%
#   filter(!rec_id %in% unlist(contact_nonhh$rec_id)) %>%
#   arrange(rec_id)

no_contacts <- ind %>% 
  filter(!rec_id %in% unlist(contact$rec_id)) %>% 
  arrange(rec_id)

# missing_nonhh <- ind %>% 
#   filter(!rec_id %in% unlist(contact_nonhh$rec_id)) %>% 
#   arrange(rec_id)
# 
# missing_both <- missing_hh$rec_id[!missing_hh$rec_id %in% missing_nonhh$rec_id]
# length((missing_both)) # 56 missing in both
```


Remove those with exit interviews but without contact diaries
```{r, , include=FALSE, warnings=FALSE}
ind <- ind %>%
    filter(!rec_id %in% unlist(no_contacts$rec_id)) 
## Dropped 78 without any diaries (but had exit interviews, 28 rural 50 urban)
```


Check if those without household contact but have other contacts live alone
```{r, , include=FALSE, warnings=FALSE}

live_alone <- hh_survey %>% 
  filter(rec_id %in% unlist(ind$rec_id)) %>%
  filter(hh_occupants==1) 

## no person who lived alone reported contacts
no_contacts <- no_contacts %>% filter(rec_id %in% unlist(live_alone$rec_id))

# ## 15 people had household members but no reported household contacts
# ## Retain these for now
# missing_hh %>% 
#   filter(!rec_id %in% unlist(missing_hh_nonhh$rec_id)) %>%
#   filter(!rec_id %in% live_alone$rec_id)

```

```{r, include=FALSE, warnings=FALSE}
## Note that self refers to HoH not the participant, it looks like the entry for the participant has already been removed from the HH contacts
# contact_hh %>% select(rec_id, individual_id, contact_id:study_site)
# 
# ##Combine HH and nonhh contact and figure out the day/dates
# 
# 
# contact_all <- plyr::rbind.fill(contact_nonhh %>% 
#                                   select(rec_id,survey_date, study_site, study_day, 
#                                          contact_age_yn, age_contact,age_group_contact, 
#                                          touch_contact, where_contact, contact_mask, duration_contact,
#                                          location_contact___0:location_contact___11) %>%
#                                   arrange(rec_id, study_day),
#                                 
#                                 contact_hh %>% 
#                                   select(rec_id, survey_date,study_site, study_day, hh_member_age, 
#                                          age_group_contact, touch_contact, where_contact, contact_mask,
#                                          duration_contact, location_contact___0:location_contact___11,
#                                          hh_member_relationship) %>%
#                                   rename(age_contact = hh_member_age))

## Get age of the participant
contact_all <- contact %>%
                left_join(ind %>% 
                            select(rec_id, participant_age), by = c("rec_id"="rec_id")) 
# %>% rename(participant_age = age)

## Recategorize location
contact_all <- contact_all %>%
              mutate(cnt_home = ifelse(location_contact___0==1, 1,0),
                     cnt_school = ifelse(location_contact___2==1, 1,0),
                     cnt_work = ifelse(location_contact___3==1, 1,0),
                     cnt_otherplace = ifelse(location_contact___1==1 | 
                                               location_contact___4==1 | 
                                               location_contact___5==1 | 
                                               location_contact___6==1 | 
                                               location_contact___7==1 |
                                               location_contact___8==1 | 
                                               location_contact___9==1 |
                                               location_contact___10==1 | 
                                               location_contact___11==1,1,0))

# ## recat relationship
# contact_all <- contact_all %>%
#                 mutate(rel = case_when(is.na(hh_member_relationship) ~"non_hh",
#                     #hh_member_relationship %in% c("Nephew", "Not relative","Other relative","Uncle/Aunt") ~ "ext_hh",
#                     TRUE ~ "hh"))

```

```{r}
diariest1 <- ind %>%
  # mutate(read_write = case_when(
  #                   read_write == "Yes"~"Y",
  #                   read_write == "No"~"N",
  #                   TRUE ~ NA_character_),
  #        
  #        enrolled_school = case_when(
  #                  age <= 4 ~"Not applicable",
  #                  enrolled_school == "Yes"~"Y",
  #                   enrolled_school == "No"~"N",
  #                   TRUE ~ NA_character_)) %>%
  
  select(participant_sex, participant_age, read_write, enrolled_school, 
         school_level, highest_education, study_site, occupation, transport_use) %>% # day_of_week, year,
  tbl_summary(by=study_site, 
              percent="column",
              digits = all_categorical() ~ 0) %>%
              #missing="no") %>%
  add_overall() %>%
  bold_labels() %>%
  modify_header(label = "") %>%
  # modify_spanning_header(c("stat_1", "stat_2", "stat_3") ~ "**Survey round**") %>%
  modify_caption("**Table 1: Baseline characteristics of Aim 1 participants across sites**")

diariest1

# table(ind$read_write)
```

```{r, include=FALSE, warnings=FALSE}
## summarize diary date
## Are there differences in contact over time?
## Not readily detectable

## Looks like some issues with this where surveydate not matching exactly with Day 1 or2
first_survey_date <- contact_all %>%
                    select(rec_id, survey_date)%>%
                    arrange(rec_id, survey_date) %>%
                    group_by(rec_id) %>%
                    slice(n=1)%>%
                    rename(dt_diaryd1 = survey_date) %>%
  mutate(pand_period = case_when(dt_diaryd1 <= as.Date("2021-6-1") ~ "lull1",
                                 dt_diaryd1 <= as.Date("2021-7-31") ~ "inc_delta",
                                 dt_diaryd1 <= as.Date("2021-9-28") ~ "dec_delta",
                                 dt_diaryd1 <= as.Date("2021-12-8") ~ "lull2",
                                 dt_diaryd1 <= as.Date("2022-1-6") ~ "inc_omi",
                                 dt_diaryd1 <= as.Date("2022-2-6") ~ "dec_omi",
                                 dt_diaryd1 <= as.Date("2022-6-1") ~ "lull3",
                                 TRUE ~ NA_character_),
         pand_period_simp = case_when(dt_diaryd1 <= as.Date("2021-6-1") ~ "lull",
                                      dt_diaryd1 <= as.Date("2021-7-31") ~ "wave",
                                      dt_diaryd1 <= as.Date("2021-9-28") ~ "wave",
                                      dt_diaryd1 <= as.Date("2021-12-8") ~ "lull",
                                      dt_diaryd1 <= as.Date("2022-1-6") ~ "wave",
                                      dt_diaryd1 <= as.Date("2022-2-6") ~ "wave",
                                      dt_diaryd1 <= as.Date("2022-6-1") ~ "lull",
                                      TRUE ~ NA_character_), 
                
                 pand_period_simp1 = case_when(
                  dt_diaryd1 <= as.Date("2021-6-1") ~ "lull",
                  dt_diaryd1 <= as.Date("2021-7-31") ~ "inc",
                  dt_diaryd1 <= as.Date("2021-9-28") ~ "dec",
                  dt_diaryd1 <= as.Date("2021-12-8") ~ "lull",
                  dt_diaryd1 <= as.Date("2022-1-6") ~ "inc",
                  dt_diaryd1 <= as.Date("2022-2-6") ~ "dec",
                  dt_diaryd1 <= as.Date("2022-6-1") ~ "lull",
                  TRUE ~ NA_character_
                
                ))
                    

```




```{r}
contact_behav <- contact_all %>% select(study_site, participant_age, touch_contact, where_contact, contact_mask, duration_contact)%>%
              mutate(where_contact = as.character(where_contact),
                     touch_contact = as.character(touch_contact),
                     contact_mask = as.character(contact_mask),
                     duration_contact = as.character(duration_contact))%>%
              pivot_longer(cols = touch_contact:duration_contact, names_to="var", values_to="value") %>%
              group_by(study_site, participant_age, var, value) %>%
              summarise(n=n()) %>% 
              left_join(contact_all %>% 
                          group_by(participant_age, study_site) %>%
                          summarise(tot_contacts=n()), by = c("participant_age"="participant_age", "study_site" = "study_site")) %>%
              mutate(prop = n/tot_contacts)

contact_behav %>% filter(var=="contact_mask") %>% 
  ggplot(x=participant_age, y =prop, fill = value) +
  geom_col(aes(x=participant_age, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)+
  theme_bw()+theme(axis.text.x = element_text(angle = 45, hjust=1))+
  ylab("Prop contacts")
       
contact_behav %>% filter(var=="duration_contact") %>% 
  ggplot(x=participant_age, y =prop, fill = value) +
  geom_col(aes(x=participant_age, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)+
  theme_bw()+theme(axis.text.x = element_text(angle = 45, hjust=1))+
  ylab("Prop contacts")

contact_behav %>% filter(var=="touch_contact") %>% 
  ggplot(x=participant_age, y =prop, fill = value) +
  geom_col(aes(x=participant_age, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)+
  theme_bw()+theme(axis.text.x = element_text(angle = 45, hjust=1))+
  ylab("Prop contacts")

contact_behav %>% filter(var=="where_contact") %>% 
  ggplot(x=participant_age, y =prop, fill = value) +
  geom_col(aes(x=participant_age, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)+
  theme_bw()+theme(axis.text.x = element_text(angle = 45, hjust=1))+
  ylab("Prop contacts")
```

```{r}
## work with Day 1 contacts only
contact_all <- contact_all %>% 
              left_join(first_survey_date)%>%
              filter(study_day ==1) 
  
contact_all_summary <- contact_all %>%
                        filter(study_day ==1) %>%
                        group_by(rec_id,study_site,participant_age, pand_period, pand_period_simp, pand_period_simp1)%>%
                        summarise(num_contact = n()) %>%
                        mutate(pand_period = factor(pand_period, 
                                                    levels = c("lull1","inc_delta","dec_delta","lull2","inc_omi","dec_omi","lull3")))
                        

ggplot(contact_all_summary, aes(x =pand_period, y = num_contact, fill = study_site)) +

  geom_boxplot(width = .50, position = position_dodge(0.6), outlier.size = 0.5) + #outlier.shape = NA,
  theme_bw() +
  #geom_hline(yintercept = all_median_rural, linetype = "dashed", color = "red") +
  scale_y_continuous(limits = c(0, 40)) +
  labs(fill="", # Round
       x = "Pandemic period",
       y = "Number of contacts" ) +
  theme(legend.title = element_text(size=15),
        legend.text = element_text(size = 12),
        legend.position = c(0.15,0.85)) +
  theme(plot.title = element_text(size = 20), 
        axis.title.x = element_text(size=18, face="bold"),
        axis.title.y = element_text(size=18, face="bold"),
        axis.text.x = element_text(size = 12, angle=0), # changed from txt_size (MK)
        axis.text.y = element_text(size= 16))

ggplot(contact_all_summary, aes(x =pand_period_simp, y = num_contact, fill = study_site)) +

  geom_boxplot(width = .50, position = position_dodge(0.6), outlier.size = 0.5) + #outlier.shape = NA,
  theme_bw() +
  #geom_hline(yintercept = all_median_rural, linetype = "dashed", color = "red") +
  scale_y_continuous(limits = c(0, 40)) +
  labs(fill="", # Round
       x = "Pandemic period",
       y = "Number of contacts" ) +
  theme(legend.title = element_text(size=15),
        legend.text = element_text(size = 12),
        legend.position = c(0.15,0.85)) +
  theme(plot.title = element_text(size = 20), 
        axis.title.x = element_text(size=18, face="bold"),
        axis.title.y = element_text(size=18, face="bold"),
        axis.text.x = element_text(size = 12, angle=0), # changed from txt_size (MK)
        axis.text.y = element_text(size= 16))

ggplot(contact_all_summary, aes(x =pand_period_simp1, y = num_contact, fill = study_site))+

  geom_boxplot(width = .50, position = position_dodge(0.6), outlier.size = 0.5) + #outlier.shape = NA,
  theme_bw() +
  #geom_hline(yintercept = all_median_rural, linetype = "dashed", color = "red") +
  scale_y_continuous(limits = c(0, 40)) +
  labs(fill="", # Round
       x = "Pandemic period",
       y = "Number of contacts" ) +
  theme(legend.title = element_text(size=15),
        legend.text = element_text(size = 12),
        legend.position = c(0.15,0.85)) +
  theme(plot.title = element_text(size = 20), 
        axis.title.x = element_text(size=18, face="bold"),
        axis.title.y = element_text(size=18, face="bold"),
        axis.text.x = element_text(size = 12, angle=0), # changed from txt_size (MK)
        axis.text.y = element_text(size= 16))
```

Not much difference in behavior over time either.. 
```{r}
contact_behav <- contact_all %>% select(study_site, pand_period, touch_contact, 
                                        where_contact, contact_mask, duration_contact) %>%
  mutate(pand_period = factor(pand_period,
                              levels = c("lull1","inc_delta","dec_delta","lull2","inc_omi","dec_omi","lull3"))) %>%
              mutate(where_contact = as.character(where_contact),
                     touch_contact = as.character(touch_contact),
                     contact_mask = as.character(contact_mask),
                     duration_contact = as.character(duration_contact))%>%
              pivot_longer(cols = touch_contact:duration_contact, names_to="var", values_to="value") %>%
              group_by(study_site, pand_period, var, value) %>%
              summarise(n=n()) %>% 
              left_join(contact_all %>% 
                          group_by(pand_period, study_site) %>%
                          summarise(tot_contacts=n()), by = c("pand_period"="pand_period", 
                                                              "study_site" = "study_site")) %>%
              mutate(prop = n/tot_contacts)

contact_behav %>% filter(var=="contact_mask") %>% 
  mutate(pand_period = factor(pand_period, levels = c("lull1","inc_delta","dec_delta","lull2","inc_omi","dec_omi","lull3"))) %>%
  ggplot(x=pand_period, y =prop, fill = value) +
  geom_col(aes(x=pand_period, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)
       
contact_behav %>% filter(var=="duration_contact") %>% 
  mutate(pand_period = factor(pand_period, 
                              levels = c("lull1","inc_delta","dec_delta","lull2","inc_omi","dec_omi","lull3"))) %>%
  ggplot(x=pand_period, y =prop, fill = value) +
  geom_col(aes(x=pand_period, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)

contact_behav %>% filter(var=="touch_contact") %>% 
  mutate(pand_period = factor(pand_period, 
                              levels = c("lull1","inc_delta","dec_delta","lull2","inc_omi","dec_omi","lull3"))) %>%
  ggplot(x=pand_period, y =prop, fill = value) +
  geom_col(aes(x=pand_period, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)

contact_behav %>% filter(var=="where_contact") %>% 
  mutate(pand_period = factor(pand_period, 
                              levels = c("lull1","inc_delta","dec_delta","lull2","inc_omi","dec_omi","lull3"))) %>%
  ggplot(x=pand_period, y =prop, fill = value) +
  geom_col(aes(x=pand_period, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)

```

```{r}
contact_behav <- contact_all %>% select(study_site, pand_period_simp, touch_contact, where_contact, contact_mask, duration_contact)%>%
              mutate(where_contact = as.character(where_contact),
                     touch_contact = as.character(touch_contact),
                     contact_mask = as.character(contact_mask),
                     duration_contact = as.character(duration_contact))%>%
              pivot_longer(cols = touch_contact:duration_contact, names_to="var", values_to="value") %>%
              group_by(study_site, pand_period_simp, var, value) %>%
              summarise(n=n()) %>% 
              left_join(contact_all %>% 
                          group_by(pand_period_simp, study_site) %>%
                          summarise(tot_contacts=n()), by = c("pand_period_simp"="pand_period_simp", "study_site" = "study_site")) %>%
              mutate(prop = n/tot_contacts)

contact_behav %>% filter(var=="contact_mask") %>% 
  ggplot(x=pand_period_simp, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)
       
contact_behav %>% filter(var=="duration_contact") %>% 
  ggplot(x=pand_period_simp, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)

contact_behav %>% filter(var=="touch_contact") %>% 
  ggplot(x=pand_period_simp, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)

contact_behav %>% filter(var=="where_contact") %>% 
  ggplot(x=pand_period_simp, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)
```

```{r}
contact_behav <- contact_all %>% select(study_site, pand_period_simp1, touch_contact, where_contact, contact_mask, duration_contact)%>%
              mutate(where_contact = as.character(where_contact),
                     touch_contact = as.character(touch_contact),
                     contact_mask = as.character(contact_mask),
                     duration_contact = as.character(duration_contact))%>%
              pivot_longer(cols = touch_contact:duration_contact, names_to="var", values_to="value") %>%
              group_by(study_site, pand_period_simp1, var, value) %>%
              summarise(n=n()) %>% 
              left_join(contact_all %>% 
                          group_by(pand_period_simp1, study_site) %>%
                          summarise(tot_contacts=n()), by = c("pand_period_simp1"="pand_period_simp1", "study_site" = "study_site")) %>%
              mutate(prop = n/tot_contacts)

contact_behav %>% filter(var=="contact_mask") %>% 
  ggplot(x=pand_period_simp1, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp1, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)
       
contact_behav %>% filter(var=="duration_contact") %>% 
  ggplot(x=pand_period_simp1, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp1, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)

contact_behav %>% filter(var=="touch_contact") %>% 
  ggplot(x=pand_period_simp1, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp1, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)

contact_behav %>% filter(var=="where_contact") %>% 
  ggplot(x=pand_period_simp1, y =prop, fill = value) +
  geom_col(aes(x=pand_period_simp1, y =prop, fill = value), position = "fill") + facet_wrap(~study_site)
```

##Matrix
One urban and one rural
```{r, include=FALSE, warnings=FALSE}
contact_all <- contact_all %>%
                rename(part_id = rec_id)%>%
                rename(part_age = participant_age)

contact_all <- contact_all %>%
  mutate(contact_age = as.character(contact_age),
        weight_cat = case_when(
          contact_age =="<6mo" ~ "0",
          contact_age == "6-11mo"~"0",
          TRUE ~ contact_age
  ))

pop_dist <- read.csv("../data/pop_dist_ines_2021.csv") %>%
            pivot_longer(cols=urban:rural, names_to = "urb_rur", values_to = "tot_pop") %>%
            mutate(study_site = case_when(
                        urb_rur =="urban" ~"Polana Caniço",
                        urb_rur == "rural"~"Manhiça"
            ))
pop_weight <- contact_all %>%
                select(part_id, study_site, weight_cat) %>% unique() %>%
                group_by(study_site, weight_cat) %>%
                summarise(n=n())

pop_weight <- pop_weight %>% 
  left_join(pop_dist, by = c("weight_cat"="age_cat","study_site"="study_site")) %>%
  mutate(part_weight = 1/(n/tot_pop))

##join weights into participant data
contact_all <- contact_all %>%
  left_join(pop_weight %>% select(study_site, weight_cat, part_weight,tot_pop),
                by = c("study_site"="study_site", "weight_cat"="weight_cat")) %>% 
  rename(population.count = tot_pop)

         
```

```{r, include=FALSE, warnings=FALSE}
contact_all <- contact_all %>% 
  mutate(part_age = as.numeric(part_age),
         contact_age = as.numeric(contact_age),
         age_group_contact = as.character(age_group_contact),
         
         cnt_age_est_min = age_contact,
         cnt_age_est_max = age_contact,
         
         cnt_age_est_min = case_when(
           !is.na(cnt_age_est_min) ~ cnt_age_est_min,
           age_group_contact == "<6mo" ~0,
           age_group_contact == "6-11mo"~0,
           age_group_contact == "1-4y" ~1,
           age_group_contact == "5-9y" ~ 5,
           age_group_contact == "10-19y"~10,
           age_group_contact == "20-29y"~20,
           age_group_contact == "30-39y"~30,
           age_group_contact == "40-49y"~40,
           age_group_contact == "50-59y"~50,
           age_group_contact == "60+y"~60,
           age_group_contact== "I don't know" ~ NA_real_,
           is.na(age_group_contact) ~ NA_real_
         ),
         
         cnt_age_est_max= case_when(
           !is.na(cnt_age_est_max) ~ cnt_age_est_max,
           age_group_contact == "<6mo" ~0,
           age_group_contact == "6-11mo"~1,
           age_group_contact == "1-4y" ~4,
           age_group_contact == "5-9y" ~ 9,
           age_group_contact == "10-19y"~19,
           age_group_contact == "20-29y"~29,
           age_group_contact == "30-39y"~39,
           age_group_contact == "40-49y"~49,
           age_group_contact == "50-59y"~59,
           age_group_contact == "60+y"~99,
           age_group_contact== "I don't know" ~ NA_real_,
           is.na(age_group_contact) ~ NA_real_
         )
  ) 


cnt_u <- contact_all %>% filter(
                  study_site == "Polana Caniço"
)

cnt_r <- contact_all %>% filter(
                  study_site == "Manhiça"
)

df_u <- survey(
        participants = cnt_u %>% 
                        select(part_id, part_age,part_weight,population.count) %>% unique()%>%
                        rename(weights = part_weight),
        
        contacts = cnt_u %>%
                        select(part_id,cnt_age_est_min, cnt_age_est_max, cnt_home:cnt_otherplace)
                
)

df_r <- survey(
        participants = cnt_r %>% 
                        select(part_id, part_age,part_weight,population.count) %>% unique()%>%
                        rename(weights = part_weight),
        
        contacts = cnt_r %>%
                        select(part_id,cnt_age_est_min, cnt_age_est_max, cnt_home:cnt_otherplace)
                
)
```

###Matrices
```{r}
## urban
m_u <- contact_matrix(df_u, age.limits = c(0,18,50,99), symmetric=T, 
                      missing.contact.age="sample", estimated.contact.age = "sample",
                     weights= df_u$participants$weights, n=1000)


mr_u <- Reduce("+", lapply(m_u$matrices, function(x) {x$matrix})) / length(m_u$matrices)
mat_u <- reshape2::melt(mr_u, varnames = c("age1", "age_cont"), value.name = "contacts") %>%
       left_join(data.frame(age1 = c(1,2,3),
                            age_part = c("[0,17)","[18,50)","50+")),
                            by="age1")



m_r <- contact_matrix(df_r, age.limits = c(0,18,50,99),symmetric=T, 
                      missing.contact.age="sample",estimated.contact.age = "sample",
                      weights= df_r$participants$weights,n=1000)


mr_r <- Reduce("+", lapply(m_r$matrices, function(x) {x$matrix})) / length(m_r$matrices)
mat_r <- reshape2::melt(mr_r, varnames = c("age1", "age_cont"), value.name = "contacts") %>%
       left_join(data.frame(age1 = c(1,2,3),
                            age_part = c("[0,17)","[18,50)","50+")),
                            by="age1")

m_r1 <- contact_matrix(df_r, age.limits = c(0,18,50,99),symmetric=T, 
                       missing.contact.age="sample",estimated.contact.age = "sample",
                       n=1000)


mr_r1 <- Reduce("+", lapply(m_r1$matrices, function(x) {x$matrix})) / length(m_r1$matrices)
mat_r1 <- reshape2::melt(mr_r1, varnames = c("age1", "age_cont"), value.name = "contacts") %>%
       left_join(data.frame(age1 = c(1,2,3),
                            age_part = c("[0,17)","[18,50)","50+")),
                            by="age1")


ggplot(mat_u, aes(x = age_part, y = age_cont, fill = contacts)) + theme(legend.position = "bottom") + 
    scale_fill_gradient2(low = "white", high = "#273871", mid = "#7FABD3", midpoint = 3.4, limit = c(0,7))+
    xlab("Age of participant")+ylab("Age of contact")+
    geom_tile()+ theme()

ggplot(mat_r, aes(x = age_part, y = age_cont, fill = contacts)) + theme(legend.position = "bottom") + 
    scale_fill_gradient2(low = "white", high = "#273871", mid = "#7FABD3", midpoint = 3.4, limit = c(0,7))+
    xlab("Age of participant")+ylab("Age of contact")+
    geom_tile()+ theme()



```

```{r}
m_r1 <- contact_matrix(df_r, age.limits = c(0,10,20,30,40,50,60),symmetric=T, missing.contact.age="sample",estimated.contact.age = "sample",
                     n=1000)


mr_r1 <- Reduce("+", lapply(m_r1$matrices, function(x) {x$matrix})) / length(m_r1$matrices)
mat_r1 <- reshape2::melt(mr_r1, varnames = c("age1", "age_cont"), value.name = "contacts") %>%
       left_join(data.frame(age1 = c(1,2,3,4,5,6,7),
                            age_part = c("[0,10)","[10,20)","[20,30)","[30-40)","[40-50)","[50-60)","60+")),
                            by="age1")

ggplot(mat_r1, aes(x = age_part, y = age_cont, fill = contacts)) + theme(legend.position = "bottom") + 
    scale_fill_gradient2(low = "white", high = "#273871", mid = "#7FABD3", midpoint = 3.4, limit = c(0,7))+
    xlab("Age of participant")+ylab("Age of contact")+
    geom_tile()+
    geom_text(aes(label=round(contacts, digits=2)), colour = "black", check_overlap = TRUE) + theme()
```

```{r}
#contact_all1 %>% group_by(rec_id, study_site, pand_period) %>%
#            summarise(pp_cont = n(),
#                      age = mean(as.numeric(age_part))) %>%
#            group_by(study_site, pand_period)%>%
#            summarise(total_cont = sum(pp_cont),
#                      part = n(),
#                      med_cont = median(pp_cont),
#                      med_age = median(age)) %>%
#            mutate(mean_cont = total_cont/part)

#contact_all1  %>% group_by(rec_id, study_site, pand_period_simp) %>%
#            summarise(pp_cont = n(),
#                      age = mean(as.numeric(age_part))) %>%
#            group_by(study_site, pand_period_simp)%>%
#            summarise(total_cont = sum(pp_cont),
#                      part = n(),
#                      med_cont = median(pp_cont),
#                      med_age = median(age)) %>%
#            mutate(mean_cont = total_cont/part)

#contact_all1  %>% group_by(rec_id, study_site, pand_period_simp1) %>%
#            summarise(pp_cont = n(),
#                      age = mean(as.numeric(age_part))) %>%
#            group_by(study_site, pand_period_simp1)%>%
#            summarise(total_cont = sum(pp_cont),
#                      part = n(),
#                      med_cont = median(pp_cont),
#                      med_age = median(age)) %>%
#            mutate(mean_cont = total_cont/part)


#contact_all %>% group_by(rec_id, study_site, age_cat) %>%
#                  summarise(pp_cont=n()) %>%
#            group_by(study_site, age_cat) %>%
#            summarise(total_cont = sum(pp_cont),
#                      part = n(),
#                      med_cont = median(pp_cont)) %>%
#            mutate(mean_cont = total_cont/part)


                

```


