---
title: "Global Mix Mozambique cleaning"
author: "Holin Chen"
date: "9/29/2021"
output: html_document
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = F}
rm(list=ls())
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```

```{r imports, echo=FALSE, message = FALSE}
# Load packages
source("../scripts/00_load_libraries.R")

# load data
data = rio::import("../raw/all_data_09242021.csv")

diary_1 = data %>% dplyr::filter(redcap_event_name == "day_1_diary_arm_1") %>% dplyr::select("rec_id","individual_id","redcap_event_name","redcap_repeat_instance","redcap_repeat_instrument","study_site","aim","shadow_d1","shadow_name_d1","shadow_gender_d1","shadow_age_d1","shadow_gender_other_d1","shadow_relationship_d1","shadow_relationship_other_d1","interview_date_d1","survey_date_d1","survey_day_d1","aim_day1","hh_day1","num_contact_aim1_d1","num_contact_nonhh_aim1_d1","num_contact_aim2_d1","num_contact_nonhh_aim2_d1","dirio_de_contato_dia_1_metadata_complete","contact_id_d1_hh_1","touch_contact_d1_hh_1","where_contact_d1_hh_1") %>% dplyr::filter(redcap_repeat_instrument == "")

locs_d1 = data %>% dplyr::filter(redcap_repeat_instrument == "dirio_de_locais_visitados_dia_1") %>% dplyr::select("rec_id","individual_id","redcap_repeat_instance","redcap_repeat_instrument","place_name_d1","place_visited_d1","place_visited_d1_other","num_pax_place_d1","time_visited_d1","visited_frequency_d1","dirio_de_locais_visitados_dia_1_complete")

cont_d1 = data %>% dplyr::filter(redcap_repeat_instrument == "dirio_de_contato_dia_1") %>% dplyr::select("rec_id","individual_id","redcap_repeat_instance","redcap_repeat_instrument","contact_id_d1","contact_hhmember_d1","contact_hhmember_id_d1","contact_age_yn_d1","age_contact_d1","age_group_contact_d1","sex_contact_d1","touch_contact_d1","where_contact_d1","location_contact_d1___0","location_contact_d1___1","location_contact_d1___2","location_contact_d1___3","location_contact_d1___4","location_contact_d1___5","location_contact_d1___6","location_contact_d1___7","location_contact_d1___8","location_contact_d1___9","location_contact_d1___10","location_contact_d1___11","location_contact_other_d1","contact_mask_d1","duration_contact_d1","frequency_contact_d1","known_contact_d1","dirio_de_contato_dia_1_complete")
```

```{r}
#site
diary_1 = diary_1 %>% 
  dplyr::mutate(study_sitelb = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 

# aim
diary_1 = diary_1 %>% 
  dplyr::mutate(aim_day1lb = case_when(aim_day1 == 0 ~ "1",
                                         aim_day1 == 1 ~ "2"))

diary_1 = diary_1 %>% 
  dplyr::mutate(aimlb = case_when(aim == 0 ~ "1",
                                         aim == 1 ~ "2"))
diary_1 = diary_1 %>% 
  dplyr::mutate(hh_day1lb = case_when(hh_day1 == 0 ~ "No",
                                         hh_day1 == 1 ~ "Yes"))
label(diary_1$hh_day1lb) <- "Are you the head of the household?"

diary_1 = diary_1 %>% 
  dplyr::mutate(shadow_d1lb = case_when(shadow_d1 == 0 ~ "Participant",
                                        shadow_d1 == 1 ~ "Shadow (person who will help)"))
label(diary_1$shadow_d1lb) <- "Who recorded the contact details in the paper dairy?"


diary_1 = diary_1 %>% 
  dplyr::mutate(shadow_gender_d1lb = case_when(shadow_gender_d1 == 0 ~ "Female",
                                        shadow_gender_d1 == 1 ~ "Male"))
label(diary_1$shadow_gender_d1lb) <- "If the participant requires a shadow, what is the sex of the shadow?"

diary_1 = diary_1 %>% 
  dplyr::mutate(shadow_relationship_d1lb = case_when(shadow_relationship_d1 == 0 ~ "Spouse",
                                        shadow_relationship_d1 == 1 ~ "Sibling",
                                        shadow_relationship_d1 == 2 ~ "Child",
                                        shadow_relationship_d1 == 3 ~ "Parent",
                                        shadow_relationship_d1 == 4 ~ "Grandparent",
                                        shadow_relationship_d1 == 5 ~ "Uncle/Aunt",
                                        shadow_relationship_d1 == 6 ~ "Grandchild",
                                        shadow_relationship_d1 == 7 ~ "Niece/Nephew",
                                        shadow_relationship_d1 == 8 ~ "Other")) #there are 0 to 8 in shadow_relationship_d1lb this variable??? 
label(diary_1$shadow_relationship_d1lb) <- "If the participant requires a shadow, what is the relationship between participant and shadow?"

wkdays = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

diary_1 = diary_1 %>% dplyr::mutate(sd1 = case_when(survey_day_d1 == 0 ~ wkdays[1], survey_day_d1 == 1 ~ wkdays[2], survey_day_d1 == 2 ~ wkdays[3], survey_day_d1 == 3 ~ wkdays[4],
                                                    survey_day_d1 == 4 ~ wkdays[5], survey_day_d1 == 5 ~ wkdays[6], survey_day_d1 == 6 ~ wkdays[7]))

diary_1$sd1 = factor(diary_1$sd1, levels = c(wkdays[1:7]))

diary_1 = diary_1 %>% 
  dplyr::mutate(touch_contact_d1_hh_1lb = case_when(touch_contact_d1_hh_1 == 0 ~ "No",
                                         touch_contact_d1_hh_1 == 1 ~ "Yes",
                                         touch_contact_d1_hh_1 == 2 ~ "Do not remember"))
label(diary_1$touch_contact_d1_hh_1lb) <- "Did you touch?"

diary_1 = diary_1 %>% 
  dplyr::mutate(where_contact_d1_hh_1lb = case_when(where_contact_d1_hh_1 == 0 ~ "Indoors",
                                         where_contact_d1_hh_1 == 1 ~ "Outdoors",
                                         where_contact_d1_hh_1 == 2 ~ "Both"))
label(diary_1$where_contact_d1_hh_1lb) <- "Did the contact occur indoors or outdoors?"


```

```{r}
locs_d1 = locs_d1 %>%
  dplyr::mutate(place_visited_d1lb = case_when(place_visited_d1 == 0 ~ "My home",
                                               place_visited_d1 == 1 ~ "Other home",
                                               place_visited_d1 == 2 ~ "School",
                                               place_visited_d1 == 3 ~ "Work",
                                               place_visited_d1 == 4 ~ "Transport/Hub",
                                               place_visited_d1 == 5 ~ "Market/Shop",
                                               place_visited_d1 == 6 ~ "Street",
                                               place_visited_d1 == 7 ~ "Well",
                                               place_visited_d1 == 8 ~ "Agricultural Field",
                                               place_visited_d1 == 9 ~ "Playground",
                                               place_visited_d1 == 10 ~ "Place of worship",
                                               place_visited_d1 == 11 ~ "Other"))
label(locs_d1$place_visited_d1lb) <- "Select the type of location that you visited."

locs_d1 = locs_d1 %>%
  dplyr::mutate(time_visited_d1lb = case_when(time_visited_d1 == 0 ~ "< 5 mins",
                                               time_visited_d1 == 1 ~ "5-15 mins",
                                               time_visited_d1 == 2 ~ "16-30 mins",
                                               time_visited_d1 == 3 ~ "31 mins - 1 hr",
                                               time_visited_d1 == 4 ~ "1-4 hrs",
                                               time_visited_d1 == 5 ~ ">4 hrs"))
label(locs_d1$time_visited_d1) <- "How much time did you spend at this location over the entire day?"

locs_d1 = locs_d1 %>%
  dplyr::mutate(visited_frequency_d1lb = case_when(visited_frequency_d1 == 0 ~ "Never met before",
                                               visited_frequency_d1 == 1 ~ "Rarely",
                                               visited_frequency_d1 == 2 ~ "Daily or almost daily",
                                               visited_frequency_d1 == 3 ~ "1-3 times per week",
                                               visited_frequency_d1 == 4 ~ "Once every 2 weeks",
                                               visited_frequency_d1 == 5 ~ "Once per month",
                                               visited_frequency_d1 == 6 ~ "Once every 3 months"))
label(locs_d1$visited_frequency_d1lb) <- "Other than this visit, in the last 6 months, how often do you visit this place?"
                                               
```

```{r}
cont_d1 = cont_d1 %>% 
  dplyr::mutate(contact_hhmember_d1lb = case_when(contact_hhmember_d1 == 0 ~ "No",
                                         contact_hhmember_d1 == 1 ~ "Yes"))
label(cont_d1$contact_hhmember_d1lb) <- "Is this contact a member of the household?"

cont_d1 = cont_d1 %>% 
  dplyr::mutate(contact_age_yn_d1lb = case_when(contact_age_yn_d1 == 0 ~ "No",
                                         contact_age_yn_d1 == 1 ~ "Yes"))
label(cont_d1$contact_age_yn_d1lb) <- "Do you know the age of the contact?"

cont_d1 = cont_d1 %>%
  dplyr::mutate(age_group_contact_d1lb = case_when(age_group_contact_d1 == 0 ~ " < 6 months",
                                               age_group_contact_d1 == 1 ~ "6-11 months",
                                               age_group_contact_d1 == 2 ~ "1-4 yrs",
                                               age_group_contact_d1 == 3 ~ "5-9 yrs",
                                               age_group_contact_d1 == 4 ~ "10-19 yrs",
                                               age_group_contact_d1 == 5 ~ "20-29 yrs",
                                               age_group_contact_d1 == 6 ~ "30-39 yrs",
                                               age_group_contact_d1 == 7 ~ "40-49 yrs",
                                               age_group_contact_d1 == 8 ~ "50-59 yrs",
                                               age_group_contact_d1 == 9 ~ "60+ yrs",
                                               age_group_contact_d1 == 10 ~ "I don't know"))
label(cont_d1$age_group_contact_d1lb) <- "If you do not know the exact age, please estimate the age group of the contact."

cont_d1 = cont_d1 %>% 
  dplyr::mutate(sex_contact_d1lb = case_when(sex_contact_d1 == 0 ~ "Female",
                                        sex_contact_d1 == 1 ~ "Male",
                                        sex_contact_d1 == 2 ~ "Transsexual Female",
                                        sex_contact_d1 == 3 ~ "Transsexual Male",
                                        sex_contact_d1 == 4 ~ "Other"))
label(cont_d1$sex_contact_d1lb) <- "What is the sex of the contact?"

cont_d1 = cont_d1 %>% 
  dplyr::mutate(touch_contact_d1lb = case_when(touch_contact_d1 == 0 ~ "No",
                                         touch_contact_d1 == 1 ~ "Yes",
                                         touch_contact_d1 == 2 ~ "Do not remember"))
label(cont_d1$touch_contact_d1lb) <- "Did you touch?"

cont_d1 = cont_d1 %>% 
  dplyr::mutate(where_contact_d1lb = case_when(where_contact_d1 == 0 ~ "Indoors",
                                         where_contact_d1 == 1 ~ "Outdoors",
                                         where_contact_d1 == 2 ~ "Both"))
label(cont_d1$where_contact_d1lb) <- "Did the contact occur indoors or outdoors?"

label(cont_d1$location_contact_d1___0) <- "My home"
label(cont_d1$location_contact_d1___1) <- "Other home"
label(cont_d1$location_contact_d1___2) <- "School"
label(cont_d1$location_contact_d1___3) <- "Work"
label(cont_d1$location_contact_d1___4) <- "Transport/Hub"
label(cont_d1$location_contact_d1___5) <- "Market/Shop"
label(cont_d1$location_contact_d1___6) <- "Street"
label(cont_d1$location_contact_d1___7) <- "Well"
label(cont_d1$location_contact_d1___8) <- "Agricultural Field"
label(cont_d1$location_contact_d1___9) <- "Playground"
label(cont_d1$location_contact_d1___10) <- "Place of worship"
label(cont_d1$location_contact_d1___11) <- "Other"
  
cont_d1 = cont_d1 %>% 
  dplyr::mutate(contact_mask_d1lb = case_when(contact_mask_d1 == 0 ~ "No, no mask was worn during the encounter",
                                        contact_mask_d1 == 1 ~ "Yes, for the entire encounter",
                                        contact_mask_d1 == 2 ~ "Yes, during parts of encounter",
                                        contact_mask_d1 == 3 ~ "I don't remember"))  
label(cont_d1$contact_mask_d1lb) <- "Was this individual wearing a mask when you had contact?"

cont_d1 = cont_d1 %>%
  dplyr::mutate(duration_contact_d1lb = case_when(duration_contact_d1 == 0 ~ "< 5 mins",
                                               duration_contact_d1 == 1 ~ "5-15 mins",
                                               duration_contact_d1 == 2 ~ "16-30 mins",
                                               duration_contact_d1 == 3 ~ "31 mins - 1 hr",
                                               duration_contact_d1 == 4 ~ "1-4 hrs",
                                               duration_contact_d1 == 5 ~ ">4 hrs"))
label(cont_d1$duration_contact_d1lb) <- "What was the total time spent with the contact on this day?"

cont_d1 = cont_d1 %>%
  dplyr::mutate(frequency_contact_d1lb = case_when(frequency_contact_d1 == 0 ~ "Never met before",
                                               frequency_contact_d1 == 1 ~ "Rarely",
                                               frequency_contact_d1 == 2 ~ "Daily or almost daily",
                                               frequency_contact_d1 == 3 ~ "1-3 times per week",
                                               frequency_contact_d1 == 4 ~ "Once every 2 weeks",
                                               frequency_contact_d1 == 5 ~ "Once per month",
                                               frequency_contact_d1 == 6 ~ "Once every 3 months"))
label(cont_d1$frequency_contact_d1lb) <- "In the past 6 months, how often have you had contact with this person?"

cont_d1 = cont_d1 %>%
  dplyr::mutate(known_contact_d1lb = case_when(known_contact_d1 == 0 ~ "Never met before",
                                               known_contact_d1 == 1 ~ "Less than a year",
                                               known_contact_d1 == 2 ~ "1-2 years",
                                               known_contact_d1 == 3 ~ "3-5 years",
                                               known_contact_d1 == 4 ~ "6-10 years",
                                               known_contact_d1 == 5 ~ "More than 10 years"))
label(cont_d1$known_contact_d1lb) <- "How long have you known this person?"

```

```{r}
diary_2 = data %>% dplyr::filter(redcap_event_name == "day_2_diary_arm_1") %>% dplyr::select("rec_id","individual_id","redcap_event_name","redcap_repeat_instance","redcap_repeat_instrument","study_site","aim","shadow_d2","shadow_name_d2","shadow_gender_d2","shadow_age_d2","shadow_gender_other_d2","shadow_relationship_d2","shadow_relationship_other_d2","survey_date_d2","survey_day_d2","aim_day2","hh_day2","num_contact_aim1_d2","num_contact_nonhh_aim1_d2","num_contact_aim2_d2","num_contact_nonhh_aim2_d2","dirio_de_contato_dia_1_metadata_complete","contact_id_d2_hh_1","touch_contact_d2_hh_1","where_contact_d2_hh_1") %>% dplyr::filter(redcap_repeat_instrument == "")

locs_d2 = data %>% dplyr::filter(redcap_repeat_instrument == "dirio_de_locais_visitados_dia_1") %>% dplyr::select("rec_id","individual_id","redcap_repeat_instance","redcap_repeat_instrument","place_name_d2","place_visited_d2","place_visited_d2_other","num_pax_place_d2","time_visited_d2","visited_frequency_d2","dirio_de_locais_visitados_dia_1_complete")

cont_d2 = data %>% dplyr::filter(redcap_repeat_instrument == "dirio_de_contato_dia_1") %>% dplyr::select("rec_id","individual_id","redcap_repeat_instance","redcap_repeat_instrument","contact_id_d2","contact_age_yn_d2","age_contact_d2","age_group_contact_d2","sex_contact_d2","touch_contact_d2","where_contact_d2","location_contact_d2___0","location_contact_d2___1","location_contact_d2___2","location_contact_d2___3","location_contact_d2___4","location_contact_d2___5","location_contact_d2___6","location_contact_d2___7","location_contact_d2___8","location_contact_d2___9","location_contact_d2___10","location_contact_d2___11","location_contact_other_d2","contact_mask_d2","duration_contact_d2","frequency_contact_d2","known_contact_d2","dirio_de_contato_dia_1_complete")

```

```{r}
#site
diary_2 = diary_2 %>% 
  dplyr::mutate(study_sitelb = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 

# aim
diary_2 = diary_2 %>% 
  dplyr::mutate(aim_day2lb = case_when(aim_day2 == 0 ~ "1",
                                         aim_day2 == 1 ~ "2"))

diary_2 = diary_2 %>% 
  dplyr::mutate(aimlb = case_when(aim == 0 ~ "1",
                                         aim == 1 ~ "2"))
diary_2 = diary_2 %>% 
  dplyr::mutate(hh_day2lb = case_when(hh_day2 == 0 ~ "No",
                                         hh_day2 == 1 ~ "Yes"))
label(diary_2$hh_day2lb) <- "Are you the head of the household?"

diary_2 = diary_2 %>% 
  dplyr::mutate(shadow_d2lb = case_when(shadow_d2 == 0 ~ "Participant",
                                        shadow_d2 == 1 ~ "Shadow (person who will help)"))
label(diary_2$shadow_d2lb) <- "Who recorded the contact details in the paper dairy?"


diary_2 = diary_2 %>% 
  dplyr::mutate(shadow_gender_d2lb = case_when(shadow_gender_d2 == 0 ~ "Female",
                                        shadow_gender_d2 == 1 ~ "Male"))
label(diary_2$shadow_gender_d2lb) <- "If the participant requires a shadow, what is the sex of the shadow?"

diary_2 = diary_2 %>% 
  dplyr::mutate(shadow_relationship_d2lb = case_when(shadow_relationship_d2 == 0 ~ "Spouse",
                                        shadow_relationship_d2 == 1 ~ "Sibling",
                                        shadow_relationship_d2 == 2 ~ "Child",
                                        shadow_relationship_d2 == 3 ~ "Parent",
                                        shadow_relationship_d2 == 4 ~ "Grandparent",
                                        shadow_relationship_d2 == 5 ~ "Uncle/Aunt",
                                        shadow_relationship_d2 == 6 ~ "Grandchild",
                                        shadow_relationship_d2 == 7 ~ "Niece/Nephew",
                                        shadow_relationship_d2 == 8 ~ "Other")) ##there are 0 to 8 in shadow_relationship_d2 this variable??? 
label(diary_2$shadow_relationship_d2lb) <- "If the participant requires a shadow, what is the relationship between participant and shadow?"

wkdays = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

diary_2 = diary_2 %>% dplyr::mutate(sd1 = case_when(survey_day_d2 == 0 ~ wkdays[1], survey_day_d2 == 1 ~ wkdays[2], survey_day_d2 == 2 ~ wkdays[3], survey_day_d2 == 3 ~ wkdays[4],
                                                    survey_day_d2 == 4 ~ wkdays[5], survey_day_d2 == 5 ~ wkdays[6], survey_day_d2 == 6 ~ wkdays[7]))

diary_2$sd1 = factor(diary_2$sd1, levels = c(wkdays[1:7]))

diary_2 = diary_2 %>% 
  dplyr::mutate(touch_contact_d2_hh_1lb = case_when(touch_contact_d2_hh_1 == 0 ~ "No",
                                         touch_contact_d2_hh_1 == 1 ~ "Yes",
                                         touch_contact_d2_hh_1 == 2 ~ "Do not remember"))
label(diary_2$touch_contact_d2_hh_1lb) <- "Did you touch?"

diary_2 = diary_2 %>% 
  dplyr::mutate(where_contact_d2_hh_1lb = case_when(where_contact_d2_hh_1 == 0 ~ "Indoors",
                                         where_contact_d2_hh_1 == 1 ~ "Outdoors",
                                         where_contact_d2_hh_1 == 2 ~ "Both"))
label(diary_2$where_contact_d2_hh_1lb) <- "Did the contact occur indoors or outdoors?"


```

```{r}
locs_d2 = locs_d2 %>%
  dplyr::mutate(place_visited_d2lb = case_when(place_visited_d2 == 0 ~ "My home",
                                               place_visited_d2 == 1 ~ "Other home",
                                               place_visited_d2 == 2 ~ "School",
                                               place_visited_d2 == 3 ~ "Work",
                                               place_visited_d2 == 4 ~ "Transport/Hub",
                                               place_visited_d2 == 5 ~ "Market/Shop",
                                               place_visited_d2 == 6 ~ "Street",
                                               place_visited_d2 == 7 ~ "Well",
                                               place_visited_d2 == 8 ~ "Agricultural Field",
                                               place_visited_d2 == 9 ~ "Playground",
                                               place_visited_d2 == 10 ~ "Place of worship",
                                               place_visited_d2 == 11 ~ "Other"))
label(locs_d2$place_visited_d2lb) <- "Select the type of location that you visited."

locs_d2 = locs_d2 %>%
  dplyr::mutate(time_visited_d2lb = case_when(time_visited_d2 == 0 ~ "< 5 mins",
                                               time_visited_d2 == 1 ~ "5-15 mins",
                                               time_visited_d2 == 2 ~ "16-30 mins",
                                               time_visited_d2 == 3 ~ "31 mins - 1 hr",
                                               time_visited_d2 == 4 ~ "1-4 hrs",
                                               time_visited_d2 == 5 ~ ">4 hrs"))
label(locs_d2$time_visited_d2) <- "How much time did you spend at this location over the entire day?"

locs_d2 = locs_d2 %>%
  dplyr::mutate(visited_frequency_d2lb = case_when(visited_frequency_d2 == 0 ~ "Never met before",
                                               visited_frequency_d2 == 1 ~ "Rarely",
                                               visited_frequency_d2 == 2 ~ "Daily or almost daily",
                                               visited_frequency_d2 == 3 ~ "1-3 times per week",
                                               visited_frequency_d2 == 4 ~ "Once every 2 weeks",
                                               visited_frequency_d2 == 5 ~ "Once per month",
                                               visited_frequency_d2 == 6 ~ "Once every 3 months"))
label(locs_d2$visited_frequency_d2lb) <- "Other than this visit, in the last 6 months, how often do you visit this place?"
                                               
```

```{r}
# cont_d2 = cont_d2 %>% 
#   dplyr::mutate(contact_hhmember_d2lb = case_when(contact_hhmember_d2 == 0 ~ "No",
#                                          contact_hhmember_d2 == 1 ~ "Yes"))
# label(cont_d2$contact_hhmember_d2lb) <- "Is this contact a member of the household?" #Do we have contact_hhmember_d2 this variable???

cont_d2 = cont_d2 %>% 
  dplyr::mutate(contact_age_yn_d2lb = case_when(contact_age_yn_d2 == 0 ~ "No",
                                         contact_age_yn_d2 == 1 ~ "Yes"))
label(cont_d2$contact_age_yn_d2lb) <- "Do you know the age of the contact?"

cont_d2 = cont_d2 %>%
  dplyr::mutate(age_group_contact_d2lb = case_when(age_group_contact_d2 == 0 ~ " < 6 months",
                                               age_group_contact_d2 == 1 ~ "6-11 months",
                                               age_group_contact_d2 == 2 ~ "1-4 yrs",
                                               age_group_contact_d2 == 3 ~ "5-9 yrs",
                                               age_group_contact_d2 == 4 ~ "10-19 yrs",
                                               age_group_contact_d2 == 5 ~ "20-29 yrs",
                                               age_group_contact_d2 == 6 ~ "30-39 yrs",
                                               age_group_contact_d2 == 7 ~ "40-49 yrs",
                                               age_group_contact_d2 == 8 ~ "50-59 yrs",
                                               age_group_contact_d2 == 9 ~ "60+ yrs",
                                               age_group_contact_d2 == 10 ~ "I don't know"))
label(cont_d2$age_group_contact_d2lb) <- "If you do not know the exact age, please estimate the age group of the contact."

cont_d2 = cont_d2 %>% 
  dplyr::mutate(sex_contact_d2lb = case_when(sex_contact_d2 == 0 ~ "Female",
                                        sex_contact_d2 == 1 ~ "Male",
                                        sex_contact_d2 == 2 ~ "Transsexual Female",
                                        sex_contact_d2 == 3 ~ "Transsexual Male",
                                        sex_contact_d2 == 4 ~ "Other"))
label(cont_d2$sex_contact_d2lb) <- "What is the sex of the contact?"

cont_d2 = cont_d2 %>% 
  dplyr::mutate(touch_contact_d2lb = case_when(touch_contact_d2 == 0 ~ "No",
                                         touch_contact_d2 == 1 ~ "Yes",
                                         touch_contact_d2 == 2 ~ "Do not remember"))
label(cont_d2$touch_contact_d2lb) <- "Did you touch?"

cont_d2 = cont_d2 %>% 
  dplyr::mutate(where_contact_d2lb = case_when(where_contact_d2 == 0 ~ "Indoors",
                                         where_contact_d2 == 1 ~ "Outdoors",
                                         where_contact_d2 == 2 ~ "Both"))
label(cont_d2$where_contact_d2lb) <- "Did the contact occur indoors or outdoors?"

label(cont_d2$location_contact_d2___0) <- "My home"
label(cont_d2$location_contact_d2___1) <- "Other home"
label(cont_d2$location_contact_d2___2) <- "School"
label(cont_d2$location_contact_d2___3) <- "Work"
label(cont_d2$location_contact_d2___4) <- "Transport/Hub"
label(cont_d2$location_contact_d2___5) <- "Market/Shop"
label(cont_d2$location_contact_d2___6) <- "Street"
label(cont_d2$location_contact_d2___7) <- "Well"
label(cont_d2$location_contact_d2___8) <- "Agricultural Field"
label(cont_d2$location_contact_d2___9) <- "Playground"
label(cont_d2$location_contact_d2___10) <- "Place of worship"
label(cont_d2$location_contact_d2___11) <- "Other"
  
cont_d2 = cont_d2 %>% 
  dplyr::mutate(contact_mask_d2lb = case_when(contact_mask_d2 == 0 ~ "No, no mask was worn during the encounter",
                                        contact_mask_d2 == 1 ~ "Yes, for the entire encounter",
                                        contact_mask_d2 == 2 ~ "Yes, during parts of encounter",
                                        contact_mask_d2 == 3 ~ "I don't remember"))  
label(cont_d2$contact_mask_d2lb) <- "Was this individual wearing a mask when you had contact?"

cont_d2 = cont_d2 %>%
  dplyr::mutate(duration_contact_d2lb = case_when(duration_contact_d2 == 0 ~ "< 5 mins",
                                               duration_contact_d2 == 1 ~ "5-15 mins",
                                               duration_contact_d2 == 2 ~ "16-30 mins",
                                               duration_contact_d2 == 3 ~ "31 mins - 1 hr",
                                               duration_contact_d2 == 4 ~ "1-4 hrs",
                                               duration_contact_d2 == 5 ~ ">4 hrs"))
label(cont_d2$duration_contact_d2lb) <- "What was the total time spent with the contact on this day?"

cont_d2 = cont_d2 %>%
  dplyr::mutate(frequency_contact_d2lb = case_when(frequency_contact_d2 == 0 ~ "Never met before",
                                               frequency_contact_d2 == 1 ~ "Rarely",
                                               frequency_contact_d2 == 2 ~ "Daily or almost daily",
                                               frequency_contact_d2 == 3 ~ "1-3 times per week",
                                               frequency_contact_d2 == 4 ~ "Once every 2 weeks",
                                               frequency_contact_d2 == 5 ~ "Once per month",
                                               frequency_contact_d2 == 6 ~ "Once every 3 months"))
label(cont_d2$frequency_contact_d2lb) <- "In the past 6 months, how often have you had contact with this person?"

cont_d2 = cont_d2 %>%
  dplyr::mutate(known_contact_d2lb = case_when(known_contact_d2 == 0 ~ "Never met before",
                                               known_contact_d2 == 1 ~ "Less than a year",
                                               known_contact_d2 == 2 ~ "1-2 years",
                                               known_contact_d2 == 3 ~ "3-5 years",
                                               known_contact_d2 == 4 ~ "6-10 years",
                                               known_contact_d2 == 5 ~ "More than 10 years"))
label(cont_d2$known_contact_d2lb) <- "How long have you known this person?"

```