---
title: "Global Mix Mozambique cleaning"
author: "Holin Chen"
date: "9/30/2021"
output: html_document
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = F}
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```


```{r imports, echo=FALSE, message = FALSE}
# Load packages
source("../scripts/00_load_libraries.R")
library(stringr)
library(Hmisc)
# load data
data = rio::import("../raw/all_data_03022022.csv")
```

```{r}
contact_name <- data %>% filter(redcap_repeat_instrument == "informaes_sobre_os_membros_da_famlia") %>%
             group_by(rec_id) %>%
             select(rec_id, hh_member_name)

contact_name$hh_member_id <- NA
for (i in unique(contact_name$rec_id)) {
  contact_name$hh_member_id[which(contact_name$rec_id==i)] <- 1:nrow(contact_name[which(contact_name$rec_id==i),]) 
}

rec_id <- sort(rep(unique(contact_name$rec_id), 30))
hh_member_id <- rep(1:30, length(unique(contact_name$rec_id)))
contact_name_full <- data.frame(rec_id, hh_member_id)

contact_name_full <- contact_name_full %>%
  left_join(contact_name, by=c("rec_id", "hh_member_id"))
```

```{r}
for (i in 1:30) {
  nam <- paste("c", i, sep = ".")
  assign(nam, data %>%
           dplyr::filter(redcap_event_name == "day_1_diary_arm_1") %>%
           dplyr::select("rec_id","individual_id","redcap_event_name","redcap_repeat_instrument","redcap_repeat_instance", ends_with(paste0("_d1_hh_",i)), starts_with(paste0("location_contact_d1_hh_",i, "___")), paste0("location_contact_other_d1_", i)) %>%
    dplyr::filter(redcap_repeat_instrument == "") %>%
    left_join(contact_name_full[which(contact_name_full$hh_member_id==i),], by="rec_id"))
}


names(c.1) <- str_remove(names(c.1), "_1") 
names(c.2) <- str_remove(names(c.2), "_2") 
names(c.3) <- str_remove(names(c.3), "_3") 
names(c.4) <- str_remove(names(c.4), "_4") 
names(c.5) <- str_remove(names(c.5), "_5") 
names(c.6) <- str_remove(names(c.6), "_6") 
names(c.7) <- str_remove(names(c.7), "_7") 
names(c.8) <- str_remove(names(c.8), "_8") 
names(c.9) <- str_remove(names(c.9), "_9") 
names(c.10) <- str_remove(names(c.10), "_10") 
names(c.11) <- str_remove(names(c.11), "_11") 
names(c.12) <- str_remove(names(c.12), "_12") 
names(c.13) <- str_remove(names(c.13), "_13") 
names(c.14) <- str_remove(names(c.14), "_14") 
names(c.15) <- str_remove(names(c.15), "_15") 
names(c.16) <- str_remove(names(c.16), "_16") 
names(c.17) <- str_remove(names(c.17), "_17") 
names(c.18) <- str_remove(names(c.18), "_18") 
names(c.19) <- str_remove(names(c.19), "_19") 
names(c.20) <- str_remove(names(c.20), "_20") 
names(c.21) <- str_remove(names(c.21), "_21") 
names(c.22) <- str_remove(names(c.22), "_22") 
names(c.23) <- str_remove(names(c.23), "_23") 
names(c.24) <- str_remove(names(c.24), "_24") 
names(c.25) <- str_remove(names(c.25), "_25")
names(c.26) <- str_remove(names(c.26), "_26") 
names(c.27) <- str_remove(names(c.27), "_27") 
names(c.28) <- str_remove(names(c.28), "_28") 
names(c.29) <- str_remove(names(c.29), "_29") 
names(c.30) <- str_remove(names(c.30), "_30") 

cont_d1_hh <- rbind(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20,c.21,c.22,c.23,c.24,c.25,c.26,
   c.27,c.28,c.29,c.30)
cont_d1_hh <- cont_d1_hh[which(!is.na(cont_d1_hh$contact_id_d1_hh)),]

```

```{r}
for (i in 1:30) {
  nam <- paste("c", i, sep = ".")
  assign(nam, data %>%
           dplyr::filter(redcap_event_name == "day_2_diary_arm_1") %>%
           dplyr::select("rec_id","individual_id","redcap_event_name","redcap_repeat_instrument","redcap_repeat_instance", ends_with(paste0("_d2_hh_",i)), starts_with(paste0("location_contact_d2_hh_",i, "___")), paste0("location_contact_other_d2_", i)) %>%
    dplyr::filter(redcap_repeat_instrument == "") %>%
    left_join(contact_name_full[which(contact_name_full$hh_member_id==i),], by="rec_id"))
}


names(c.1) <- str_remove(names(c.1), "_1") 
names(c.2) <- str_remove(names(c.2), "_2") 
names(c.3) <- str_remove(names(c.3), "_3") 
names(c.4) <- str_remove(names(c.4), "_4") 
names(c.5) <- str_remove(names(c.5), "_5") 
names(c.6) <- str_remove(names(c.6), "_6") 
names(c.7) <- str_remove(names(c.7), "_7") 
names(c.8) <- str_remove(names(c.8), "_8") 
names(c.9) <- str_remove(names(c.9), "_9") 
names(c.10) <- str_remove(names(c.10), "_10") 
names(c.11) <- str_remove(names(c.11), "_11") 
names(c.12) <- str_remove(names(c.12), "_12") 
names(c.13) <- str_remove(names(c.13), "_13") 
names(c.14) <- str_remove(names(c.14), "_14") 
names(c.15) <- str_remove(names(c.15), "_15") 
names(c.16) <- str_remove(names(c.16), "_16") 
names(c.17) <- str_remove(names(c.17), "_17") 
names(c.18) <- str_remove(names(c.18), "_18") 
names(c.19) <- str_remove(names(c.19), "_19") 
names(c.20) <- str_remove(names(c.20), "_20") 
names(c.21) <- str_remove(names(c.21), "_21") 
names(c.22) <- str_remove(names(c.22), "_22") 
names(c.23) <- str_remove(names(c.23), "_23") 
names(c.24) <- str_remove(names(c.24), "_24") 
names(c.25) <- str_remove(names(c.25), "_25")
names(c.26) <- str_remove(names(c.26), "_26") 
names(c.27) <- str_remove(names(c.27), "_27") 
names(c.28) <- str_remove(names(c.28), "_28") 
names(c.29) <- str_remove(names(c.29), "_29") 
names(c.30) <- str_remove(names(c.30), "_30") 

cont_d2_hh<- rbind(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20,c.21,c.22,c.23,c.24,c.25,c.26,
   c.27,c.28,c.29,c.30)
cont_d2_hh <- cont_d2_hh[which(!is.na(cont_d2_hh$contact_id_d2_hh)),]

rm(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20,c.21,c.22,c.23,c.24,c.25,c.26,
   c.27,c.28,c.29,c.30)
```





```{r}
cont_d1_hh <- cont_d1_hh[which(cont_d1_hh$contact_id_d1_hh == 1),]
cont_d2_hh <- cont_d2_hh[which(cont_d2_hh$contact_id_d2_hh == 1),]

names(cont_d1_hh)[grep("_d1_hh", names(cont_d1_hh))] <-  gsub("_d1_hh", "", names(cont_d1_hh)[grep("_d1_hh", names(cont_d1_hh))])
names(cont_d1_hh)[25] <- "location_contact_other"
names(cont_d2_hh)[grep("_d2_hh", names(cont_d2_hh))] <-  gsub("_d2_hh", "", names(cont_d2_hh)[grep("_d2_hh", names(cont_d2_hh))])
names(cont_d2_hh)[25] <- "location_contact_other"

#names(cont_d1_hh);names(cont_d2_hh)
#names(cont_d1_hh) == names(cont_d2_hh)

```
```{r}
cont_d1_hh$Day1or2 <- 1
cont_d2_hh$Day1or2 <- 2

contact_hh_all <- rbind(cont_d1_hh, cont_d2_hh)

hh_member = data %>% 
  dplyr::select("rec_id",'redcap_repeat_instrument',hh_member_hoh,hh_member_name,hh_member_id,hh_member_sensor,hh_member_sex,hh_member_sex_outro,hh_member_age,hh_member_relationship,hh_member_relationship_other,share_room,share_bed,cook_food,hh_member_hhform,hh_member_instance,informaes_de_agregado_familiar_e_casa_complete) %>% 
  dplyr::filter(redcap_repeat_instrument == "informaes_sobre_os_membros_da_famlia")

contact_hh_all <- contact_hh_all %>% 
  left_join(hh_member, by=c("rec_id","hh_member_name")) %>%
  distinct(rec_id, hh_member_id.y, Day1or2, .keep_all = TRUE) %>%
  filter(!is.na(hh_member_name))


contact_hh_repeat <- contact_hh_all %>%
  group_by(rec_id, hh_member_name, hh_member_id.y) %>%
  summarise(contact_count=n())

study_site <- data %>%
  filter(redcap_event_name=="household_survey_arm_1") %>%
  select(rec_id, study_site, aim)

contact_hh_all <- contact_hh_all %>%
  left_join(contact_hh_repeat, by=c("rec_id","hh_member_name","hh_member_id.y")) %>%
  mutate(repeat_contact_d2 = ifelse(contact_count == 2 & Day1or2 == 2, "repeat", 
                                       ifelse(contact_count == 1 & Day1or2 == 2, "unique", NA))) %>%
  left_join(study_site, by="rec_id") %>%
  mutate(fromdayone = ifelse(((contact_count == 2 & Day1or2 == 2) | (Day1or2 == 1 & contact_count == 2)), "Both Days",
                             ifelse(contact_count == 1 & Day1or2 == 2, "Day2 Only",
                                    ifelse(contact_count == 1 & Day1or2 == 1, "Day1 Only", NA))))
```

```{r}
cont_d1 = data %>% dplyr::filter(redcap_repeat_instrument == "dirio_de_contato_dia_1") %>% dplyr::select("rec_id","individual_id","redcap_event_name","redcap_repeat_instance","redcap_repeat_instrument","contact_id_d1","contact_age_yn_d1","age_contact_d1","age_group_contact_d1","sex_contact_d1","touch_contact_d1","where_contact_d1","location_contact_d1___0","location_contact_d1___1","location_contact_d1___2","location_contact_d1___3","location_contact_d1___4","location_contact_d1___5","location_contact_d1___6","location_contact_d1___7","location_contact_d1___8","location_contact_d1___9","location_contact_d1___10","location_contact_d1___11","location_contact_other_d1","contact_mask_d1","duration_contact_d1","frequency_contact_d1","known_contact_d1","dirio_de_contato_dia_1_complete")

cont_d2 = data %>% dplyr::filter(redcap_repeat_instrument == "dirio_de_contato_dia_2") %>% dplyr::select("rec_id","individual_id","redcap_event_name","redcap_repeat_instance","redcap_repeat_instrument","contact_id_d2","contact_age_yn_d2","age_contact_d2","age_group_contact_d2","sex_contact_d2","touch_contact_d2","where_contact_d2","location_contact_d2___0","location_contact_d2___1","location_contact_d2___2","location_contact_d2___3","location_contact_d2___4","location_contact_d2___5","location_contact_d2___6","location_contact_d2___7","location_contact_d2___8","location_contact_d2___9","location_contact_d2___10","location_contact_d2___11","location_contact_other_d2","contact_mask_d2","duration_contact_d2","frequency_contact_d2","known_contact_d2","dirio_de_contato_dia_1_complete")

names(cont_d1)[grep("_d1", names(cont_d1))] <-  gsub("_d1", "", names(cont_d1)[grep("_d1", names(cont_d1))])
names(cont_d2)[grep("_d2", names(cont_d2))] <-  gsub("_d2", "", names(cont_d2)[grep("_d2", names(cont_d2))])

#names(cont_d1) == names(cont_d2)
cont_d1$Day1or2 <- 1
cont_d2$Day1or2 <- 2
cont_d2$repeat_contact_d2 <- "unique"
cont_d1$repeat_contact_d2 <- NA
cont_d1d2_norep <- rbind(cont_d1, cont_d2)

cont_d1d2_norep <- cont_d1d2_norep %>%
  select("rec_id","individual_id","redcap_event_name","redcap_repeat_instrument","redcap_repeat_instance","contact_id","touch_contact","where_contact","contact_mask","duration_contact","frequency_contact","known_contact","location_contact___0","location_contact___1","location_contact___2","location_contact___3","location_contact___4","location_contact___5","location_contact___6","location_contact___7","location_contact___8","location_contact___9","location_contact___10","location_contact___11","location_contact_other","Day1or2","repeat_contact_d2","contact_age_yn","age_contact","age_group_contact","sex_contact")
```

```{r}
contact_name_d1 <- data %>% filter(redcap_repeat_instrument == "dirio_de_contato_dia_1") %>%
             group_by(rec_id) %>%
             select(rec_id, contact_id_d1,"contact_age_yn_d1","age_contact_d1","age_group_contact_d1","sex_contact_d1")

contact_name_d1$contact_sequence_id <- NA
for (i in unique(contact_name_d1$rec_id)) {
  contact_name_d1$contact_sequence_id[which(contact_name_d1$rec_id==i)] <- 1:nrow(contact_name_d1[which(contact_name_d1$rec_id==i),]) 
}

rec_id <- sort(rep(unique(contact_name_d1$rec_id), 20))
contact_sequence_id <- rep(1:20, length(unique(contact_name_d1$rec_id)))
contact_name_d1_full <- data.frame(rec_id, contact_sequence_id)

contact_name_d1_full <- contact_name_d1_full %>%
  left_join(contact_name_d1, by=c("rec_id", "contact_sequence_id"))

for (i in 1:20) {
  nam <- paste("c", i, sep = ".")
  assign(nam, data %>%
           dplyr::filter(redcap_event_name == "day_2_diary_arm_1") %>% 
           dplyr::select("rec_id","individual_id","redcap_event_name","redcap_repeat_instrument","redcap_repeat_instance", ends_with(paste0("_d2_rep_",i)), starts_with(paste0("location_contact_d2_rep_",i)))%>%
    dplyr::filter(redcap_repeat_instrument == "")%>%
    left_join(contact_name_d1_full[which(contact_name_d1_full$contact_sequence_id==i),], by="rec_id"))
}

c.1 <- c.1[,c(1:25,146:151)]
c.2 <- c.2[,c(1:25,38:43)]


names(c.1) <- str_remove(names(c.1), "_1") 
names(c.2) <- str_remove(names(c.2), "_2") 
names(c.3) <- str_remove(names(c.3), "_3") 
names(c.4) <- str_remove(names(c.4), "_4") 
names(c.5) <- str_remove(names(c.5), "_5") 
names(c.6) <- str_remove(names(c.6), "_6") 
names(c.7) <- str_remove(names(c.7), "_7") 
names(c.8) <- str_remove(names(c.8), "_8") 
names(c.9) <- str_remove(names(c.9), "_9") 
names(c.10) <- str_remove(names(c.10), "_10") 
names(c.11) <- str_remove(names(c.11), "_11") 
names(c.12) <- str_remove(names(c.12), "_12") 
names(c.13) <- str_remove(names(c.13), "_13") 
names(c.14) <- str_remove(names(c.14), "_14") 
names(c.15) <- str_remove(names(c.15), "_15") 
names(c.16) <- str_remove(names(c.16), "_16") 
names(c.17) <- str_remove(names(c.17), "_17") 
names(c.18) <- str_remove(names(c.18), "_18") 
names(c.19) <- str_remove(names(c.19), "_19") 
names(c.20) <- str_remove(names(c.20), "_20") 


cont_d2_rep <- rbind(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20)
cont_d2_rep <- cont_d2_rep[which(cont_d2_rep$repeat_contact_d2_rep == 1),]

rm(c.1,c.2,c.3,c.4,c.5,c.6,c.7,c.8,c.9,c.10,c.11,c.12,c.13,c.14,
   c.15,c.16,c.17,c.18,c.19,c.20)

cont_d2_rep$Day1or2 <- 2
cont_d2_rep$repeat_contact_d2 <- "repeat"

names(cont_d2_rep)[grep("_d2_rep", names(cont_d2_rep))] <-  gsub("_d2_rep", "", names(cont_d2_rep)[grep("_d2_rep", names(cont_d2_rep))])
names(cont_d2_rep)[grep("_d1", names(cont_d2_rep))] <-  gsub("_d1", "", names(cont_d2_rep)[grep("_d1", names(cont_d2_rep))])

cont_d2_rep <- cont_d2_rep %>%
  select("rec_id","individual_id","redcap_event_name","redcap_repeat_instrument","redcap_repeat_instance","contact_id","touch_contact","where_contact","contact_mask","duration_contact","frequency_contact","known_contact","location_contact___0","location_contact___1","location_contact___2","location_contact___3","location_contact___4","location_contact___5","location_contact___6","location_contact___7","location_contact___8","location_contact___9","location_contact___10","location_contact___11","location_contact_other","Day1or2","repeat_contact_d2","contact_age_yn","age_contact","age_group_contact","sex_contact")


#names(cont_d2_rep)==names(cont_d1d2_norep)
cont_all <- rbind(cont_d1d2_norep, cont_d2_rep)

cont_repeat <- cont_all %>%
  group_by(rec_id, contact_id) %>%
  summarise(contact_count=n())



cont_all <- cont_all %>%
  left_join(study_site, by="rec_id") %>% 
  left_join(cont_repeat, by=c("rec_id","contact_id")) %>%
  mutate(fromdayone = ifelse(((contact_count == 2 & Day1or2 == 2) | (Day1or2 == 1 & contact_count == 2)), "Both Days",
                             ifelse(((contact_count == 1 & Day1or2 == 2)), "Day2 Only", 
                                    ifelse((Day1or2 == 1 & contact_count == 1), "Day1 Only", NA))))

cont_all$fromdayone[which(cont_all$contact_count>2 & cont_all$repeat_contact_d2=="unique" & cont_all$Day1or2==2)] <- "Day2 Only"
cont_all$fromdayone[which(cont_all$contact_count>2 & cont_all$repeat_contact_d2=="repeat" & cont_all$Day1or2==2)] <- "Both Days"


cont_repeat_dup <- cont_all %>%
  filter(contact_count > 2) %>%
  group_by(rec_id, redcap_repeat_instance, Day1or2, contact_id, fromdayone) %>%
  summarise(contact_count=n())

```


```{r}
contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(contact_id = case_when(contact_id == 0 ~ "No",
                                         contact_id == 1 ~ "Yes",
                                         contact_id == 2 ~ "Not applicable")) #the data dic only says 0, No | 1, Yes, but actually there are 3 levels in this variable 
label(contact_hh_all$contact_id) <- "Did you have contact with [household_survey_arm_1][hh_member_name][1]?"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(touch_contact = case_when(touch_contact == 0 ~ "No",
                                         touch_contact == 1 ~ "Yes",
                                         touch_contact == 2 ~ "Do not remember")) 
label(contact_hh_all$touch_contact) <- "Did you touch?"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(where_contact = case_when(where_contact == 0 ~ "Indoors",
                                         where_contact == 1 ~ "Outdoors",
                                         where_contact == 2 ~ "Both")) 
label(contact_hh_all$where_contact) <- "Did the contact occur indoors or outdoors?"

label(contact_hh_all$location_contact___0) <- "My home"
label(contact_hh_all$location_contact___1) <- "Other home"
label(contact_hh_all$location_contact___2) <- "School"
label(contact_hh_all$location_contact___3) <- "Work"
label(contact_hh_all$location_contact___4) <- "Transport/Hub"
label(contact_hh_all$location_contact___5) <- "Market/Shop"
label(contact_hh_all$location_contact___6) <- "Street"
label(contact_hh_all$location_contact___7) <- "Well"
label(contact_hh_all$location_contact___8) <- "Agricultural Field"
label(contact_hh_all$location_contact___9) <- "Playground"
label(contact_hh_all$location_contact___10) <- "Place of worship"
label(contact_hh_all$location_contact___11) <- "Other"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(contact_mask = case_when(contact_mask == 0 ~ "No, no mask was worn during the encounter",
                                        contact_mask == 1 ~ "Yes, for the entire encounter",
                                        contact_mask == 2 ~ "Yes, during parts of encounter",
                                        contact_mask == 3 ~ "I don't remember"))  
label(contact_hh_all$contact_mask) <- "Was this individual wearing a mask when you had contact?"

contact_hh_all = contact_hh_all %>%
  dplyr::mutate(duration_contact = case_when(duration_contact == 0 ~ "< 5 mins",
                                               duration_contact == 1 ~ "5-15 mins",
                                               duration_contact == 2 ~ "16-30 mins",
                                               duration_contact == 3 ~ "31 mins - 1 hr",
                                               duration_contact == 4 ~ "1-4 hrs",
                                               duration_contact == 5 ~ ">4 hrs"))
label(contact_hh_all$duration_contact) <- "What was the total time spent with the contact on this day?"

contact_hh_all = contact_hh_all %>%
  dplyr::mutate(frequency_contact = case_when(frequency_contact == 0 ~ "Never met before",
                                               frequency_contact == 1 ~ "Rarely",
                                               frequency_contact == 2 ~ "Daily or almost daily",
                                               frequency_contact == 3 ~ "1-3 times per week",
                                               frequency_contact == 4 ~ "Once every 2 weeks",
                                               frequency_contact == 5 ~ "Once per month",
                                               frequency_contact == 6 ~ "Once every 3 months"))
label(contact_hh_all$frequency_contact) <- "In the past 6 months, how often have you had contact with this person?"

contact_hh_all = contact_hh_all %>%
  dplyr::mutate(known_contact = case_when(known_contact == 0 ~ "Never met before",
                                               known_contact == 1 ~ "Less than a year",
                                               known_contact == 2 ~ "1-2 years",
                                               known_contact == 3 ~ "3-5 years",
                                               known_contact == 4 ~ "6-10 years",
                                               known_contact == 5 ~ "More than 10 years"))
label(contact_hh_all$known_contact) <- "How long have you known this person?"

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(hh_member_sex = case_when(hh_member_sex == 0 ~ "Female",
                                        hh_member_sex == 1 ~ "Male",
                                        hh_member_sex == 2 ~ "Transsexual Female",
                                        hh_member_sex == 3 ~ "Transsexual Male",
                                        hh_member_sex == 4 ~ "Other"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(hh_member_relationship = case_when(hh_member_relationship == 0 ~ "Spouse",
                                        hh_member_relationship == 1 ~ "Sibiling",
                                        hh_member_relationship == 2 ~ "Child",
                                        hh_member_relationship == 3 ~ "Parent",
                                        hh_member_relationship == 4 ~ "Grandparent",
                                        hh_member_relationship == 5 ~ "Uncle/Aunt",
                                        hh_member_relationship == 6 ~ "Grandchild",
                                        hh_member_relationship == 7 ~ "Nephew",
                                        hh_member_relationship == 8 ~ "Other relative",
                                        hh_member_relationship == 9 ~ "Not relative",
                                        hh_member_relationship == 10 ~ "Not applicable (it is the head of the household himself)"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(share_room = case_when(share_room == 0 ~ "No",
                                         share_room == 1 ~ "Yes"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(share_bed = case_when(share_bed == 0 ~ "No",
                                        share_bed == 1 ~ "Yes"))

contact_hh_all = contact_hh_all %>% 
  dplyr::mutate(cook_food = case_when(cook_food == 0 ~ "No",
                                        cook_food == 1 ~ "Yes"))
```

```{r}

cont_all = cont_all %>% 
  dplyr::mutate(touch_contact = case_when(touch_contact == 0 ~ "No",
                                         touch_contact == 1 ~ "Yes",
                                         touch_contact == 2 ~ "Do not remember")) 
label(cont_all$touch_contact) <- "Did you touch?"

cont_all = cont_all %>% 
  dplyr::mutate(where_contact = case_when(where_contact == 0 ~ "Indoors",
                                         where_contact == 1 ~ "Outdoors",
                                         where_contact == 2 ~ "Both")) 
label(cont_all$where_contact) <- "Did the contact occur indoors or outdoors?"

label(cont_all$location_contact___0) <- "My home"
label(cont_all$location_contact___1) <- "Other home"
label(cont_all$location_contact___2) <- "School"
label(cont_all$location_contact___3) <- "Work"
label(cont_all$location_contact___4) <- "Transport/Hub"
label(cont_all$location_contact___5) <- "Market/Shop"
label(cont_all$location_contact___6) <- "Street"
label(cont_all$location_contact___7) <- "Well"
label(cont_all$location_contact___8) <- "Agricultural Field"
label(cont_all$location_contact___9) <- "Playground"
label(cont_all$location_contact___10) <- "Place of worship"
label(cont_all$location_contact___11) <- "Other"

cont_all = cont_all %>% 
  dplyr::mutate(contact_mask = case_when(contact_mask == 0 ~ "No, no mask was worn during the encounter",
                                        contact_mask == 1 ~ "Yes, for the entire encounter",
                                        contact_mask == 2 ~ "Yes, during parts of encounter",
                                        contact_mask == 3 ~ "I don't remember"))  
label(cont_all$contact_mask) <- "Was this individual wearing a mask when you had contact?"

cont_all = cont_all %>%
  dplyr::mutate(duration_contact = case_when(duration_contact == 0 ~ "< 5 mins",
                                               duration_contact == 1 ~ "5-15 mins",
                                               duration_contact == 2 ~ "16-30 mins",
                                               duration_contact == 3 ~ "31 mins - 1 hr",
                                               duration_contact == 4 ~ "1-4 hrs",
                                               duration_contact == 5 ~ ">4 hrs"))
label(cont_all$duration_contact) <- "What was the total time spent with the contact on this day?"

cont_all = cont_all %>%
  dplyr::mutate(frequency_contact = case_when(frequency_contact == 0 ~ "Never met before",
                                               frequency_contact == 1 ~ "Rarely",
                                               frequency_contact == 2 ~ "Daily or almost daily",
                                               frequency_contact == 3 ~ "1-3 times per week",
                                               frequency_contact == 4 ~ "Once every 2 weeks",
                                               frequency_contact == 5 ~ "Once per month",
                                               frequency_contact == 6 ~ "Once every 3 months"))
label(cont_all$frequency_contact) <- "In the past 6 months, how often have you had contact with this person?"

cont_all = cont_all %>%
  dplyr::mutate(known_contact = case_when(known_contact == 0 ~ "Never met before",
                                               known_contact == 1 ~ "Less than a year",
                                               known_contact == 2 ~ "1-2 years",
                                               known_contact == 3 ~ "3-5 years",
                                               known_contact == 4 ~ "6-10 years",
                                               known_contact == 5 ~ "More than 10 years"))
label(cont_all$known_contact) <- "How long have you known this person?"

cont_all = cont_all %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 

cont_all = cont_all %>% 
  dplyr::mutate(contact_age_yn = case_when(contact_age_yn == 0 ~ "No",
                                         	contact_age_yn == 1 ~ "Yes")) 
label(cont_all$contact_age_yn) <- "Do you know the contact age?"

cont_all = cont_all %>% 
  dplyr::mutate(age_group_contact = case_when(age_group_contact == 0 ~ "< 6 months",
                                               age_group_contact == 1 ~ "6-11 months",
                                               age_group_contact == 2 ~ "1-4 yrs",
                                               age_group_contact == 3 ~ "5-9 yrs",
                                               age_group_contact == 4 ~ "10-19 yrs",
                                               age_group_contact == 5 ~ "20-29 yrs",
                                               age_group_contact == 6 ~ "30-39 yrs",
                                               age_group_contact == 7 ~ "40-49 yrs",
                                               age_group_contact == 8 ~ "50-59 yrs",
                                               age_group_contact == 9 ~ "60+ yrs",
                                               age_group_contact == 10 ~ "I don't know",
                                               age_contact == 0 ~ "6-11 months",
                                               age_contact %in% 1:4 ~ "1-4 yrs",
                                               age_contact %in% 5:9 ~ "5-9 yrs",
                                               age_contact %in% 10:19 ~ "10-19 yrs",
                                               age_contact %in% 20:29 ~ "20-29 yrs",
                                               age_contact %in% 30:39 ~ "30-39 yrs",
                                               age_contact %in% 40:49 ~ "40-49 yrs",
                                               age_contact %in% 50:59 ~ "50-59 yrs",
                                               age_contact >=60 ~ "60+ yrs"))

cont_all$age_group_contact = factor(cont_all$age_group_contact, 
                   levels = c("< 6 months", "6-11 months", "1-4 yrs", "5-9 yrs", "10-19 yrs", "20-29 yrs", "30-39 yrs", "40-49 yrs", "50-59 yrs", "60+ yrs", "I don't know"))

cont_all = cont_all %>% 
  dplyr::mutate(sex_contact = case_when(sex_contact == 0 ~ "Female",
                                        sex_contact == 1 ~ "Male",
                                        sex_contact == 2 ~ "Transsexual Female",
                                        sex_contact == 3 ~ "Transsexual Male",
                                        sex_contact == 4 ~ "Other"))
```

```{r}
contact_hh_rural <- contact_hh_all[which(contact_hh_all$study_site=="Manhiça"),]

library(gtsummary)
contact_hh_summary <- contact_hh_rural %>%
  select("hh_member_sex","hh_member_age","hh_member_relationship","fromdayone","touch_contact","where_contact","contact_mask","duration_contact","frequency_contact","known_contact","location_contact___0","location_contact___1","location_contact___2","location_contact___3","location_contact___4","location_contact___5","location_contact___6","location_contact___7","location_contact___8","location_contact___9","location_contact___10","location_contact___11") %>%
  tbl_summary(percent="column",
              digits = all_categorical() ~ 1) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Household Contact Information in Manhiça**")
#contact_hh_summary
```
```{r}
cont_rural <- cont_all[which(cont_all$study_site=="Manhiça"),]

contact_summary <- cont_rural %>%
  select("sex_contact","age_contact","age_group_contact","fromdayone","touch_contact","where_contact","contact_mask","duration_contact","frequency_contact","known_contact","location_contact___0","location_contact___1","location_contact___2","location_contact___3","location_contact___4","location_contact___5","location_contact___6","location_contact___7","location_contact___8","location_contact___9","location_contact___10","location_contact___11") %>%
  tbl_summary(percent="column",
              digits = all_categorical() ~ 1) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Non-Household Contact Information in Manhiça**")
#contact_summary
```




## Individual enrolment
```{r individual_enrolment, echo=FALSE}
ind <- data %>% 
  dplyr::filter(redcap_event_name == "individual_enrollm_arm_1") %>% 
  dplyr::select("rec_id", "date_enrolled", "sex", "sex_other", "birthdate","age", "read_write", "occupation___0", "occupation___1", "occupation___2", "occupation___3", "occupation___4", "occupation___5", "occupation___6", "occupation___7", "occupation___8", "occupation___9", "occupation_other", "enrolled_school", "highest_educ", "school_level", "transport_use", "hh_resp_exposure", "child_breastfeed", "num_simbling", "inscrio_complete", "sensor_id","child", "redcap_repeat_instrument") %>%
    dplyr::filter(redcap_repeat_instrument == "") %>%
  left_join(study_site, by="rec_id")
## Individual enrollment records

ind = ind %>% 
  dplyr::mutate(study_site = case_when(study_site == 1 ~ "Manhiça",
                                         study_site == 2 ~ "Polana Caniço")) 
ind = ind %>% 
  dplyr::mutate(aim = case_when(aim == 0 ~ 1,
                                 aim == 1 ~ 2)) 
ind  = ind %>% 
  dplyr::mutate(highest_educ = case_when(highest_educ == 0 ~ "No schooling", 
                                           highest_educ == 1 ~ "Primary School (1-7)", 
                                           highest_educ == 2 ~ "Basic Secondary school (8-10)",
                                           highest_educ == 3 ~ "Middle Secondary (11-12)", 
                                           highest_educ == 4 ~ "1-3 years of college/university", 
                                           highest_educ == 5 ~ "Bacherols",
                                           highest_educ == 6 ~ "More than Bachelors")) ## check spelling, initially "Bacherols"
label(ind$highest_educ) <- "What is the highest level of education that you have attained?"

ind = ind %>% 
  dplyr::mutate(age = case_when(age < 1 ~ "<1", 
                                  age >=1 & age <= 4 ~ "1 - 4y", 
                                  age >=5 & age <=9 ~ "5 - 9y", 
                                  age >=10 & age <=14 ~ "10 - 14y", 
                                  age >=15 & age <=19 ~ "15 - 19y", 
                                  age >=20 & age <=29 ~ "20 - 29y", 
                                  age >=30 & age <=39 ~ "30 - 39y", 
                                  age >=40 & age <=59 ~ "40 - 59y", 
                                  age >=60 ~ "60y+"))

ind = ind %>% 
  dplyr::mutate(sex = case_when(sex == 0 ~ "Female", sex == 1 ~ "Male"))

ind$age = factor(ind$age, 
                   levels = c("<1", "1 - 4y", "5 - 9y", "10 - 14y", "15 - 19y", "20 - 29y", "30 - 39y", "40 - 59y", "60y+"))


ind  = ind %>% 
  dplyr::mutate(read_write = case_when(read_write == 0 ~ "No", 
                                         read_write == 1 ~ "Yes"))
label(ind$read_write) <- "Can the participant read and write on their own?"


label(ind$occupation___0) <- "Unemployed"
label(ind$occupation___1) <- "Student"
label(ind$occupation___2) <- "Office worker"
label(ind$occupation___3) <- "Business person"
label(ind$occupation___4) <- "Casual labor"
label(ind$occupation___5) <- "Farmer"
label(ind$occupation___6) <- "Fishing"
label(ind$occupation___7) <- "Retired"
label(ind$occupation___8) <- "Homemaker/ Housewife"
label(ind$occupation___9) <- "Other"

ind  = ind %>% 
  dplyr::mutate(enrolled_school = case_when(enrolled_school == 0 ~ "No", 
                                         enrolled_school == 1 ~ "Yes"))
label(ind$enrolled_school) <- "Are you currently enrolled in school?"

ind  = ind %>% 
  dplyr::mutate(school_level = case_when(school_level == 0 ~ "No schooling", 
                                           school_level == 1 ~ "Primary School (1-7)", 
                                           school_level == 2 ~ "Basic Secondary school (8-10)",
                                           school_level == 3 ~ "Middle Secondary (11-12)", 
                                           school_level == 4 ~ "1-3 years of college/university", 
                                           school_level == 5 ~ "Bacherols",
                                           school_level == 6 ~ "More than Bachelors"))
label(ind$school_level) <- "What school level are you in?"

ind  = ind %>% 
  dplyr::mutate(transport_use = case_when(transport_use == 0 ~ "Never", 
                                            transport_use == 1 ~ "Rarely", 
                                            transport_use == 2 ~ "Daily or almost daily",
                                            transport_use == 3 ~ "1-3 times per week", 
                                            transport_use == 4 ~ "1 time per month"))
label(ind$transport_use) <- "How often did you use mass transport in the past 3 months?"

ind  = ind %>% 
  dplyr::mutate(hh_resp_exposure = case_when(hh_resp_exposure == 0 ~ "No", 
                                               hh_resp_exposure == 1 ~ "Yes",
                                               hh_resp_exposure == 2 ~ "I don't know"))
label(ind$hh_resp_exposure) <- "Were you exposed to persons with respiratory complaints within your household in the past one week?"
 
ind  = ind %>% 
  dplyr::mutate(child_breastfeed = case_when(child_breastfeed == 0 ~ "No", 
                                               child_breastfeed == 1 ~ "Yes",
                                               child_breastfeed == 2 ~ "Not applicable"))
label(ind$child_breastfeed) <- "Are you breastfeeding?"

ind  = ind %>% 
  dplyr::mutate(child = case_when(child == 0 ~ "No", 
                                    child == 1 ~ "Yes",
                                    child == 2 ~ "Not applicable"))
label(ind$child) <- "Do you have a infant ?"

ind_contact_hh <- contact_hh_all %>%
  left_join(ind[,-which(names(ind) %in% c("aim","study_site"))], by = "rec_id")

ind_contact <- cont_all %>%
  left_join(ind[,-which(names(ind) %in% c("aim","study_site"))], by = "rec_id")

ind_summary <- ind %>%
  filter(study_site == "Manhiça") %>%
  select("sex", "sex_other", "birthdate","age", "read_write", "occupation___0", "occupation___1", "occupation___2", "occupation___3", "occupation___4", "occupation___5", "occupation___6", "occupation___7", "occupation___8", "occupation___9", "occupation_other", "enrolled_school", "highest_educ", "school_level", "transport_use", "hh_resp_exposure", "child_breastfeed", "num_simbling","child") %>%
  tbl_summary(percent="column",
              digits = all_categorical() ~ 1) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  modify_caption("**Particiant Individual Information in Manhiça**")
#ind_summary
```
```{r}
ind_summary
contact_summary
contact_hh_summary
```

```{r}
ind_contact$aim[which(ind_contact$aim==1)] <- 2 
ind_contact$aim[which(ind_contact$aim==0)] <- 1

ind_contact_hh$aim[which(ind_contact_hh$aim==1)] <- 2
ind_contact_hh$aim[which(ind_contact_hh$aim==0)] <- 1 

saveRDS(ind, "../Data/individual_info.RDS")
saveRDS(ind_contact_hh, "../Data/ind_contact_hh_rural.RDS")
saveRDS(ind_contact, "../Data/ind_contact_nonhh_rural.RDS")
```